### ISSUE TITLE
[Bug] Crash when rapidly updating the list

### ISSUE THREAD

**Issue by zyrouge** [zyrouge/symphony#10]
New crashing issue with logs here: https://paste.evolution-x.org/cPzrLO

_Originally posted by @slipsby in https://github.com/zyrouge/symphony/issues/8#issuecomment-1336087701_

**Comment by slipsby** [comment]
might be when it scans my library only have 5k songs. Seems like it rescans everytime i open the app

**Comment by zyrouge** [comment]
> might be when it scans my library only have 5k songs. Seems like it rescans everytime i open the app

Ah, I'll look into a fix.

**Comment by zyrouge** [comment]
Does this still occur in v2022.12.40?

**Comment by slipsby** [comment]
Now it doesnt scan music even if you clear the app cache, new crash log though: https://paste.evolution-x.org/lvb7VW

**Comment by zyrouge** [comment]
> Now it doesnt scan music even if you clear the app cache, new crash log though: https://paste.evolution-x.org/lvb7VW

Could you try v2022.12.44?

**Comment by slipsby** [comment]
> > Now it doesnt scan music even if you clear the app cache, new crash log though: https://paste.evolution-x.org/lvb7VW
> 
> Could you try v2022.12.44?

Installed when i start from zero and open the app i need to close it so it can start scanning (not much of an issue). Works fine until you overwhelm it by spamming the next button and switching to shuffle. Oh and i have a wma file that when it encounters it doesnt play but who cares wma is old anyway.(crashlog for the shuffle spam: https://paste.evolution-x.org/6cwHlj)

**Comment by zyrouge** [comment]
Could you try v2022.12.51? Let me know if there are anymore issues.

**Comment by slipsby** [comment]
worked perfectly after it scanned my music in the previous version but when i reset app data and cache it now stays frozen on the splash screen/logo. Does not crash so i cant provide logs this time sorry

**Comment by zyrouge** [comment]
> worked perfectly after it scanned my music in the previous version but when i reset app data and cache it now stays frozen on the splash screen/logo. Does not crash so i cant provide logs this time sorry

Probably it's stuck scanning. I did encounter this once. I'll find a workaround for this.

**Comment by zyrouge** [comment]
> worked perfectly after it scanned my music in the previous version but when i reset app data and cache it now stays frozen on the splash screen/logo. Does not crash so i cant provide logs this time sorry

Should be fixed in v2022.12.52.

**Comment by slipsby** [comment]
works now though it does the shuffle spam thing but not as often takes like 20 tries which no one really does day to day but heres the logs :https://paste.evolution-x.org/Td3hNP


oh and thank you for the quick fixes much appreciated

**Comment by zyrouge** [comment]
> works now though it does the shuffle spam thing but not as often takes like 20 tries which no one really does day to day but heres the logs :https://paste.evolution-x.org/Td3hNP
> 
> oh and thank you for the quick fixes much appreciated

There are still issues related to spamming because of concurrency and frequent recompositions by compose. But, as you said, we don't really spam anything in everyday use. Appreciate you for the quick responses and for testing the app consistently. I'll be closing this issue I guess.
