### ISSUE TITLE
[Feature Request] Double-click album to view it

### ISSUE THREAD

**Issue by dietmarczekay** [zyrouge/symphony#100]
is it possible to integrate a function to jump to album by double click on album cover in player view

**Comment by zyrouge** [comment]
Implemented as of v2023.4.80.

**Comment by dietmarczekay** [comment]
Works Like a Charm, many thanks

Am 11. April 2023 17:29:54 MESZ schrieb ZYROUGE ***@***.***>:
>Implemented as of v2023.4.80.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/zyrouge/symphony/issues/100#issuecomment-1503617524
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde mit K-9 Mail gesendet.
