### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [zyrouge/symphony#103]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/4016950601#L849

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/93bfa50169d023ba9f8106b2282b70de3f540470

**Comment by zyrouge** [comment]
Opened a MR [here](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12829).
