### ISSUE TITLE
[Bug] Crashing on play

### ISSUE THREAD

**Issue by rajhalder073** [zyrouge/symphony#11]
Blink screen when I play any song and my device not working

**Comment by zyrouge** [comment]
Could you confirm if this is happening in v2022.12.51?

**Comment by zyrouge** [comment]
Closing this as it is stale. Feel free to reopen if needed.

**Comment by trustosas** [comment]
This happened on my phone (Vivo Y12s, Android 11) on the latest version. Had to uninstall.
