### ISSUE TITLE
[Feature Request] Customizable speed and pitch

### ISSUE THREAD

**Issue by genux1** [zyrouge/symphony#111]
As the title says, it would be great if you add an option to have customizable speed and pitch, such as adding a slider or type the custom value (e.g. 1.05 or 1.1). It would be more useful.

**Comment by RustoMCSpit** [comment]
whys this been pushed back so much? is this that hard of a fix? thanks for all the work you do @zyrouge

**Comment by zyrouge** [comment]
> whys this been pushed back so much? is this that hard of a fix? thanks for all the work you do @zyrouge

I am a bit busy as of now, that's why the updates are getting delayed.

**Comment by RustoMCSpit** [comment]
> > whys this been pushed back so much? is this that hard of a fix? thanks for all the work you do @zyrouge
> 
> I am a bit busy as of now, that's why the updates are getting delayed.

can this be prioritised as it doesnt seem to be a hard fix? also tysm for everything!
