### ISSUE TITLE
[Feature Request] Separate song list sorting from album track list sorting

### ISSUE THREAD

**Issue by phw** [zyrouge/symphony#115]
Currently when you change the sorting of the main song list to "title" this also affects the track list when viewing individual albums (so the tracks of the album also end up alphabetically). Same if you change the sorting of the album track list to "track number" this will cause the main song list to be sorted by track numbers (so all tracks 1 first, then all second tracks etc.),

It would be better if this would be separate settings and one can control the sorting of album track list separately from the main song list.

**Comment by zyrouge** [comment]
Just realised that this is already implemented. Closing this.

**Comment by phw** [comment]
Cool, thanks for taking care of that. Can't test it right now, I have some other trouble with loading the song list. But I need to check, will open an issue if this problem stays.
