### ISSUE TITLE
"Clear song cache" also removes playlists

### ISSUE THREAD

**Issue by phw** [zyrouge/symphony#116]
If one uses "Clear song cache" this also removes all playlists. Not sure if this is intentional, but at least it was very unexpected. I assumed it would just rescan the music information but keep playlists.

**Comment by zyrouge** [comment]
The playlists seems to just load up after it finishes scanning the library. Let me know if it is actually a bug.

**Comment by phw** [comment]
Ok, I'll test again. This time I have backed up my playlists :)
