### ISSUE TITLE
[Bug] Scanning library crashes and repeats

### ISSUE THREAD

**Issue by ctha42** [zyrouge/symphony#117]
First of all, I want to say that this (when it works) is the FOSS android player I've dreamed of, so thank you.

This issue affects (and breaks) the entire app. Whenever launching for the first time, I go through the welcome messages and it scans my media. Throughout the scan (I have a very large library), the app completely freezes and crashes with the android "not responding" message. This happens consistently every launch. The next launch, it begins to rebuild the library from scratch, until the crash happens again. This issue is consistent until version 2023.3.73, where it seems fixed. I'll give any other info I can. TIA.

**Comment by ctha42** [comment]
It seems that updating after the db is generated is also fine. Also, off topic, is the favorites button not implemented yet? It does nothing for me.

**Comment by zyrouge** [comment]
> It seems that updating the app after the db is generated is also fine. Also, off topic, is the favorites button not implemented yet? It does nothing for me.

Some one did say the favorites doesn't work for them. I don't have any steps to reproduce that issue. Logs would help a lot in these cases.

**Comment by zyrouge** [comment]
Also for the scanning issue, it's Compose which cannot seem to handle rapid refreshes, I tried my best to prevent that, yet it seem to decide to crash.

**Comment by ctha42** [comment]
You need a computer to capture logs right? I'm out of town for the next few days so I won't be able to get anything. Also, that doesn't explain why downgrading the app works.

**Comment by zyrouge** [comment]
Understandable.

**Comment by zyrouge** [comment]
Fixed as of v2023.4.82, let me know if you still face this issue.

**Comment by Rmtony** [comment]
> Fixed as of v2023.4.82, let me know if you still face this issue.

I am using this version, latest, and it crash \ freeze when scanning library...

**Comment by zyrouge** [comment]
> > Fixed as of v2023.4.82, let me know if you still face this issue.
> 
> I am using this version, latest, and it crash \ freeze when scanning library...

Could you possibly attach a clip of that happening so I can try reproducing the issue.

**Comment by Rmtony** [comment]
Sorry, about after 10 scans and crash now works.

**Comment by fried-motherboards** [comment]
Using v2023.4.82, started crashing after increasing the size of my local library quite a bit (~52 GiB of files, stored on SD card). The issue did not happen with my smaller library with less files and less big files stored onto the phone's built-in storage.

**Comment by zyrouge** [comment]
> Using v2023.4.82 from F-Droid, started crashing after increasing the size of my local library quite a bit (~52 GiB of files, stored on SD card). The issue did not happen with my smaller library with less files and less big files stored onto the phone's built-in storage.

That is a large library, I might have to find new solutions then. Maybe like a seperate loading screen instead of the current implementation. Compose struggles to handle these large lists.

**Comment by phw** [comment]
Same thing happens here (with 2023.4.82 installed from Github release page). I have something around ~4500 MP3 files on my SD. When I originally installed Symphony it scanned all songs successfully. But at least with the 2023.4.80 and 2023.4.82 the app stops responding and eventually gets killed after reading ~1600 files.

**Comment by ctha42** [comment]
> With v2023.3.73 the import went smooth without hanging

This is how it was with me as well, but it seems that the library updates automatically after a while and the issue reappears.

**Comment by ctha42** [comment]
Hmm. I have a OnePlus 8 Pro with LineageOS. Not weak hardware at all. I don't understand how the framework can be the issue? Is the library scanning code yours or a library or something?

**Comment by Rmtony** [comment]
> > With v2023.3.73 the import went smooth without hanging
> 
> This is how it was with me as well, but it seems that the library updates automatically after a while and the issue reappears.

I confirm, this is the last "stable" version

**Comment by fried-motherboards** [comment]
Sorry to bring it back up, issue has happened when using the latest version (2023.5.91). Muaic imports and app functions normally until hitting some arbitrary number of songs, which then crashes the app entirely.

A log screen did generate though, see attachment.

![Screenshot_2023-05-28-08-47-59-10_c328a126cb0fb561391a2f6f61559b68.jpg](https://github.com/zyrouge/symphony/assets/68259282/1a3286bc-4850-4c4d-b9d8-6968bb76d6be)

**Comment by zyrouge** [comment]
> Sorry to bring it back up, issue has happened when using the latest version (2023.5.91). Muaic imports and app functions normally until hitting some arbitrary number of songs, which then crashes the app entirely.
> 
> A log screen did generate though, see attachment.
> 
> ![Screenshot_2023-05-28-08-47-59-10_c328a126cb0fb561391a2f6f61559b68.jpg](https://user-images.githubusercontent.com/68259282/241571528-1a3286bc-4850-4c4d-b9d8-6968bb76d6be.jpg)

Could you possibly attach a clip of it happening? Also with some more information like when it occurs, how often does it happen, etc. Also this seems like something happened when sorting but seems like it's from internal libraries. This might require a new issue rather than re-opening this.

**Comment by fried-motherboards** [comment]
> Could you possibly attach a clip of it happening? Also with some more information like when it occurs, how often does it happen, etc. Also this seems like something happened when sorting but seems like it's from internal libraries. This might require a new issue rather than re-opening this.

Interestingly, I can't actually re-create the issue anymore. The app is now working as it should, despite retracing my steps and exact behaviors (installed the app, opened it, saw songs importing, played one song for a period of time in the background with my screen off while the songs were importing before the crash).

Things to note:
- My installation of v2023.5.91 was an upgrade from v2023.3.79, and I happened to entirely reinstall the app between my last post and this one
- I'm using a Nord N20 5G running Android 12 (OnePlus' 'OxygenOS')

Thanks for your work in developing this app!

**Comment by zyrouge** [comment]
> > Could you possibly attach a clip of it happening? Also with some more information like when it occurs, how often does it happen, etc. Also this seems like something happened when sorting but seems like it's from internal libraries. This might require a new issue rather than re-opening this.
> 
> Interestingly, I can't actually re-create the issue anymore. The app is now working as it should, despite retracing my steps and exact behaviors (installed the app, opened it, saw songs importing, played one song for a period of time in the background with my screen off while the songs were importing before the crash).
> 
> Things to note:
> 
> * My installation of v2023.5.91 was an upgrade from v2023.3.79, and I happened to entirely reinstall the app between my last post and this one
> * I'm using a Nord N20 5G running Android 12 (OnePlus' 'OxygenOS')
> 
> Thanks for your work in developing this app!

Cheers!
