### ISSUE TITLE
[Feature Request] Use thumbnails directly from song metadata

### ISSUE THREAD

**Issue by ghost** [zyrouge/symphony#118]
![Screenshot_20230404-121958_Symphony~2.jpg](https://user-images.githubusercontent.com/128434089/229855713-e49184f4-0bed-45e4-9fe6-e22ce56dd576.jpg)

**Comment by zyrouge** [comment]
It might take some time for Media Store to cache them. This should get fixed automatically.

**Comment by TheValidUser** [comment]
Do I need to stay on the app for it to get cached ?

**Comment by zyrouge** [comment]
Nope, it is handled by Android itself.

**Comment by TheValidUser** [comment]
Do we have a way of using the thumbnails already saved in the song file instead of using the Media Store.

**Comment by TheValidUser** [comment]
Yeah I think so to. Plus I saw on an other music app that it's not 100% reliable?

**Comment by zyrouge** [comment]
This comes with the cost of caching all the covers of the songs in the library which is really inefficient and high in memory consumption depending on the size of the library.

**Comment by TheValidUser** [comment]
Smartphones are getting better every years and that other music apps already use this feature, I think it can be possible.

**Comment by shynline** [comment]
Are you working on this? @zyrouge 
If not i'll open a PR and we can discuss about it.

**Comment by zyrouge** [comment]
> Are you working on this? @zyrouge If not i'll open a PR and we can discuss about it.

Don't work on this yet. The better way to solve this would be implementing custom metadata decoders, which will be implemented in the next update or two.
