### ISSUE TITLE
[Feature Request] Replace androidx.media with androidx.media2

### ISSUE THREAD

**Issue by FriederHannenheim** [zyrouge/symphony#12]
Media is deprecated. Using media2 would make the notification which shows what music is playing a bit nicer

**Comment by zyrouge** [comment]
> Media is deprecated.

It is actually not.

> Using media2 would make the notification which shows what music is playing a bit nicer

The notification displayed has nothing to do with media player.

I'll be closing this since there are no significant benefits with using media2. Feel free to reopen if needed.
