### ISSUE TITLE
[Feature Request] Ability to add custom fonts or system font.

### ISSUE THREAD

**Issue by NUCLEARxDYNAMO** [zyrouge/symphony#120]
App would be much better if users get to pick their own font.

**Comment by zyrouge** [comment]
> Developer Resource: https://developer.android.com/reference/kotlin/android/graphics/fonts/SystemFonts?hl=en#getAvailableFonts().

**Comment by zyrouge** [comment]
I did implement this but it was really usable due to how Android managed system fonts. There is no standardized API to do it either. It is possible but is not really practical.
