### ISSUE TITLE
Improve UI Experience

### ISSUE THREAD

**Issue by ismaelbachicha** [zyrouge/symphony#121]
/![Screenshot_2023-04-06-19-42-43-471_io github zyrouge symphony-edit](https://user-images.githubusercontent.com/130060028/230369800-767e1d3c-2b7d-4538-a022-09d78f36c28c.jpg)
![Screenshot_2023-04-06-19-43-49-344_com miui home-edit](https://user-images.githubusercontent.com/130060028/230369830-6ca5e809-8524-4ee4-aa6e-bbbb279d3460.jpg)
.
Hello good day, I just wanna suggest if you want to make the "Header Style" More Bigger for us to use w/ appealing. And I hope you adapt Android 13 Monet Icons to adjust your icons in wallpaper changes, thank you and Godbless. 
.
#120

**Comment by zyrouge** [comment]
The header follows the Material Design guidelines and will not be changed since it looks pretty good. Monet Icons are requested in #120, so I'll just close this since it's a duplicate.
