### ISSUE TITLE
[Bug] Music player controls not showing in notification panel

### ISSUE THREAD

**Issue by sharmas1ddharth** [zyrouge/symphony#122]

**Comment by zyrouge** [comment]
Screenshot please?

**Comment by MrFoxPro** [comment]
@zyrouge this happens on EMUI with some players and this too. As you can see VKX works well.
![image](https://user-images.githubusercontent.com/17229619/230722705-48176c76-64b2-432a-8833-666eaa364462.png)

**Comment by zyrouge** [comment]
Not sure what's going wrong. I don't have EMUI to test with.

**Comment by zyrouge** [comment]
Closing this as stale. Feel free to create a new issue.
