### ISSUE TITLE
[Feature Request] Add codec to audio info to complete the Holy Trinity

### ISSUE THREAD

**Issue by opusforlife2** [zyrouge/symphony#124]
Hi, I'm so glad that this is one of the rare FOSS players to have a toggle to expose audio track info in the main UI. The two that are already there, bitrate and sampling rate, are usually accompanied by the codec. Could you add that, please?

**Comment by zyrouge** [comment]
Surely.

**Comment by zyrouge** [comment]
Implemented as of v2023.4.82.
