### ISSUE TITLE
[Bug] Music starts playing after ending a phone call

### ISSUE THREAD

**Issue by thesh4de** [zyrouge/symphony#127]
Even if there was no song playing before the phone call, the app starts playing previously played music when a phone call ends.

**Comment by pabloscloud** [comment]
I am using v2023.4.80 and this doesn't happen for me in android 13; calyxos 4.7.5

**Comment by zyrouge** [comment]
Anyways the patch fixes playing when the audio focus was not lost.

**Comment by zyrouge** [comment]
Fixed as of v2023.4.82, let me know if you still face this issue.
