### ISSUE TITLE
[Feature Request] Delete songs and albums

### ISSUE THREAD

**Issue by pabloscloud** [zyrouge/symphony#128]
I want to be able to delete a song that is currently playing as well as songs and albums from all other views where there is a 3-dot-menu.

**Comment by zyrouge** [comment]
Any type of interaction with the filesystem is considered as out of scope for this project. This was also mentioned in a similar issue. Closing this since it's unplanned.

**Comment by pabloscloud** [comment]
ok

**Comment by pabloscloud** [comment]
And if I donate haha

**Comment by zyrouge** [comment]
> And if I donate haha

I'd just steal the money. :>

**Comment by pabloscloud** [comment]
😅
