### ISSUE TITLE
[Bug] Songs order of Album not respected

### ISSUE THREAD

**Issue by Rmtony** [zyrouge/symphony#129]
### Description

Reproduction order of songs of albums not respected (random). It happens with every albums of my library.

 

### Device

-   Device:  Pixel 3
-   OS:  Android 13
-   Version v2023.4.82

**Comment by zyrouge** [comment]
> Reproduction order of songs of albums not respected (random). It happens with every albums of my library.

Could you explain what you mean? Also, remove the unneeded lines from the template.

**Comment by Rmtony** [comment]
> > > > Reproduction order of songs of albums not respected (random). It happens with every albums of my library.
> > > 
> > > 
> > > Could you explain what you mean? Also, remove the unneeded lines from the template.
> > 
> > 
> > Example, if an album has 5 songs I expect order playing as track number 1,2,3,4,5. Instead the app playing 2,5,3,1,4, this happen for every album of my library.....
> 
> Did you sort it by track number?

I did not found how to do it.....Excuse me

**Comment by zyrouge** [comment]
![Screenshot_2023-04-14-09-48-29-042_io github zyrouge symphony-edit](https://user-images.githubusercontent.com/50770114/231940671-0693464c-92a7-4b14-b49b-98587d4e0b4b.jpg)

**Comment by Rmtony** [comment]
Oh thank you! I clicked on left arrow thinking that is the only option....

**Comment by zyrouge** [comment]
Closing this as it's already implemented.
