### ISSUE TITLE
[Bug] Music resumes after calls end, even if music was not on when call started

### ISSUE THREAD

**Issue by autodistries** [zyrouge/symphony#132]
### Description

Music is automatically resumed after a voice call ends, whether or not music was playing before the call started

### Steps to Reproduce

1. Have the app opened and have a playlist or anything ready to play (you can play then pause to make sure music is ready)
2. Go to your phone app or receive a call
3. End the call and hear music

### Expected Behavior

After calls, music should resume only if it was playing before the call started

### Screenshots

NA

### Device

-   Device: Redmi Note 5 Pro
-   OS: Android 11
-   Version: 2023.4.82

### Additional Context

None

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
:tada: Fixed as of v2023.5.89.

**Comment by zyrouge** [comment]
:tada: Fixed as of v2023.7.104!
