### ISSUE TITLE
[Feature Request] Show notification for library scans

### ISSUE THREAD

**Issue by opusforlife2** [zyrouge/symphony#133]
### Description

Currently, the app performs its library scanning silently. The number of songs seen in the list just increases sporadically. It's difficult to tell how long it will take for the whole thing to finish.

Sometimes, the app also stops responding and the OS repeatedly shows the ANR dialogue. Does the scanning happen on the main thread?

### Solution

Show an ongoing notification while a library scan is being performed. This is how other music apps do it. Not sure if they use a different thread for it, but it seems like a good idea.

### Alternatives

Show the scan status in-app via a progress bar.

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
This has already been implemented in dev which should be released within next week.
