### ISSUE TITLE
Fastlane changelog over limit

### ISSUE THREAD

**Issue by IzzySoft** [zyrouge/symphony#135]
Fastlane's per-release changelogs are limited to 500 char per definition. Your current one (`79.txt`) has 896 chars and thus will be truncated mid-sentence. Can you please keep it within limits? Thanks!

**Comment by zyrouge** [comment]
I'll make sure it's under that limit for further releases.

**Comment by IzzySoft** [comment]
> I'll make sure it's under that limit for further releases.

@zyrouge please do that, yes :see_no_evil: 

```
! io.github.zyrouge.symphony/en-US/changelogs/113.txt has 676 chars
! io.github.zyrouge.symphony/en-US/changelogs/115.txt has 703 chars
```

**Comment by zyrouge** [comment]
> > I'll make sure it's under that limit for further releases.
> 
> @zyrouge please do that, yes 🙈
> 
> ```
> ! io.github.zyrouge.symphony/en-US/changelogs/113.txt has 676 chars
> ! io.github.zyrouge.symphony/en-US/changelogs/115.txt has 703 chars
> ```

Done! :)

**Comment by IzzySoft** [comment]
Thanks!
