### ISSUE TITLE
[Bug] Favorite song icon acting weird

### ISSUE THREAD

**Issue by SunBreaker1** [zyrouge/symphony#136]
### Description

When liking a song, the icon doesn't change color, but when backing out and re-opening the song in now playing window, or checking queue, it shows song is in favorites

### Steps to Reproduce

 Video attached

### Expected Behavior

Icon should change right off the bat

### Screenshots

https://user-images.githubusercontent.com/85519676/232820149-616e338e-cb7c-4b59-8718-b8a4b661d9b2.mp4

### Device

-   Device: Samsung S23+
-   OS: One UI 5.1
-   Version v2023.4.82

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by SunBreaker1** [comment]
Context: This video was taken immediately after unlocking my phone. I've noticed that if you open the queue before hitting the "like" icon, the icon works normally

**Comment by zyrouge** [comment]
:tada: Fixed as of v2023.5.89.
