### ISSUE TITLE
[Bug] Dropdown UI freeze on 1 song

### ISSUE THREAD

**Issue by zeex4** [zyrouge/symphony#137]
### Description
Homescreen and dropdown UI freezes on one song. Controls and progress bar work fine. Tested Auxio/Spotify/Tidal and these apps work fine
### Steps to Reproduce

1. Play song "A"
2. Turn off your screen, turn on & change song
3. Play song "B"
4. UI displays improper song

### Expected Behavior

Change song name, artist & cover to currently playing.

### Screenshots

![IMG_20230418_192644](https://user-images.githubusercontent.com/93828310/232858622-ca24c958-6c8e-4992-b919-b71935362774.jpg)

![_20230418_192750](https://user-images.githubusercontent.com/93828310/232858691-f2f9f634-2031-4deb-bb35-c092ccf370c4.JPG)

### Device

-   Device: Pixel 6 series
-   OS: Android 13 up2date

### Checklist

-   [X] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
:tada: Fixed as of v2023.5.89.
