### ISSUE TITLE
[Feature Request] Show visual that song is in playlist

### ISSUE THREAD

**Issue by SunBreaker1** [zyrouge/symphony#138]
### Description

After adding a song to a playlist, when opening the "add to playlist" for the song, there should be a visual icon/mark that let's you know what playlists the song is in

### Solution

If song is already in playlist, show a checkmark in what playlist the song is in when selecting what palylist to put the song in

### Alternatives

Can't think of any

### Additional Context

https://user-images.githubusercontent.com/85519676/233054539-8c7c1398-b759-4a7e-8427-93034f4a3cd2.mp4

### Checklist

-   [X] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
:tada: Implementation as of v2023.6.93.
