### ISSUE TITLE
[Bug] Music keeps playing when bluetooth is turned off

### ISSUE THREAD

**Issue by Heus-Sueh** [zyrouge/symphony#139]
### Description

Music keeps playing when bluetooth is turned off

### Steps to Reproduce

play a song and turn off bluetooth

### Expected Behavior

the natural thing would be for the music to pause when the bluetooth is turned off

### Screenshots

.

### Device

-   Device: Xiaomi Mi A2 Lite
-   OS: LineageOS Android 13
-   Version: 2023.03.22

### Additional Context

the toggle to pause the music when the headphone is disconnected doesn't seem to be working

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
:tada: Fixed as of v2023.5.89.
