### ISSUE TITLE
[Feature Request] Gapless Playback

### ISSUE THREAD

**Issue by ghost** [zyrouge/symphony#140]
### Description

It would be nice for the app to support gapless playback for albums with songs flowing into one another. Good examples are Nonagon Infinity and Origin of Symmetry, which sound weird when there is silnce between songs.

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
Closing in favor of #594.
