### ISSUE TITLE
Unresolved reference: ITranslations in Symphony.kt

### ISSUE THREAD

**Issue by Sory-Noroc** [zyrouge/symphony#141]
### Description

I wanted to contribute to this great repo but I get an error which I can't understand...

### Steps to Reproduce

1. Clone repo, main branch
2. Build
3. Error in utils/Symphony.kt "Unresolved reference: ITranslations"

### Device

-   Device: Pixel 3A

### Additional Context

There might be a simple fix, I'm just not familiar with the repo yet

**Comment by zyrouge** [comment]
[This](https://github.com/zyrouge/symphony/wiki/Developer-Guide) should help you.

**Comment by zyrouge** [comment]
Closing this.
