### ISSUE TITLE
[Feature Request] Add support for synchronised lyrics

### ISSUE THREAD

**Issue by Ampnbsp** [zyrouge/symphony#144]
Add support for synchronised lyrics, for example, with this format :
[0:18.12] First line
[0:22.31] Second line
[0:31.09] Third line

**Comment by zyrouge** [comment]
This would probably require allowing access to all files and folders, so I'm bit hesitant to implement this. Let me know you thoughts.

**Comment by Ampnbsp** [comment]
I do not mind. However for me the main thing is to be able read embedded synchronised lyrics in the music tags.

**Comment by xmha97** [comment]
I want this feature too!

![Screenshot_2023-11-10-19-08-38-993_io.github.zyrouge.symphony.jpg](https://github.com/zyrouge/symphony/assets/23485114/44794789-5439-4166-a147-7ff2b2d6aa5e)
