### ISSUE TITLE
[Bug] App freezes on start

### ISSUE THREAD

**Issue by swishkin** [zyrouge/symphony#145]
### Description

Whenever I start the app, it freezes, sometimes immediately, sometimes up to five seconds later. This behavior began several versions ago.

### Steps to Reproduce

1. Tap on Symphony icon in your launcher
2. App freezes during DB build (?)

### Expected Behavior

Opening the app should not freeze the app

### Screenshots

![Screenshot_20230429-212150_Symphony](https://user-images.githubusercontent.com/19404743/235332508-f6b77fd9-76f4-40d1-ade9-b07e79915286.png)

### Device

-   Device: OnePlus 7 Pro
-   OS: LineageOS Android 13 (20-20230416-NIGHTLY-guacamole)
-   Version: 2023.4.82

### Additional Context

Attempted clearing cache, tried after a few updates pushed, no change in behavior.

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by phw** [comment]
Probably same issue as #117

**Comment by zyrouge** [comment]
:tada: Fixed as of v2023.5.89.
