### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Vishal-09-00** [zyrouge/symphony#153]
### Description

App freeze on startup. 

### Steps to Reproduce

App gets freezed on startup or after 5 seconds of scanning for songs. 

### Expected Behavior

Should work without any freeze while scanning. 

### Device

-   Device: [Vivo Z1 Pro]
-   OS: [Android 11]

### Additional Context

App works fine with version 2023.3.73 but is having this issue with later versions.

**Comment by zyrouge** [comment]
Duplicate of #117. Tracked at #152.
