### ISSUE TITLE
[Bug] Playlists don't have cover

### ISSUE THREAD

**Issue by SunBreaker1** [zyrouge/symphony#154]
### Description

Before one of the recent updates, created playlists and favorites playlists would have a song cover of the first song added

### Steps to Reproduce

1. Favorite a song
2. Go to playlists
3. Open favorites playlist, song is inside, but playlist cover is missing

### Expected Behavior

The first song added to a playlist should be the cover image of the playlist

### Screenshots

https://github.com/zyrouge/symphony/assets/85519676/7d50503d-dcaa-4499-9308-80b3c577ecca

### Device

-   Device: S23+
-   OS: OneUI 5.1

### Additional Context

None

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
:tada: Fixed as of v2023.5.89.
