### ISSUE TITLE
option to remove songs in playlists from the songs tap

### ISSUE THREAD

**Issue by FarisArabia** [zyrouge/symphony#155]
i had an interesting thought while i was organizing my playlists.

can i simply just remove them from the songs tap while keeping them in a playlist in the app?

idk of any music app that does this so it could be really amazing.

**Comment by zyrouge** [comment]
> i had an interesting thought while i was organizing my playlists.
> 
> can i simply just remove them from the songs tap while keeping them in a playlist in the app?
> 
> idk of any music app that does this so it could be really amazing.

The songs tab is supposed to show all the songs. This will stay as the intended behaviour. You wouldn't like the song to disappear once you remove it from songs tab and the playlist.
