### ISSUE TITLE
[Bug] Playlists disappeared 

### ISSUE THREAD

**Issue by SunBreaker1** [zyrouge/symphony#158]
### Description

The newest update removed almost every created playlist, even though the app says how many there are

### Steps to Reproduce

1. Open app
2. Go to playlists
3. Almost every single playlist is gone

### Expected Behavior

The playlists should appear with all the songs saved to them

### Screenshots

![Screenshot_20230528_151554_Symphony.jpg](https://github.com/zyrouge/symphony/assets/85519676/763d5f0e-fcae-4621-8e34-e9b30e45bdb1)

### Device

-   Device: Samsung S23+
-   OS: One Ui
-   Version 2023.5.89

### Additional Context

While most of my playlists were empty ( I'm working on building my song collection and playlists) all but one playlist disappeared, even the few with songs in them. Strangely enough, the app knows that I have 13 playlists but only shows one.

### Checklist

-   [X] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
Could you try going into settings and coming back to home?

**Comment by SunBreaker1** [comment]
> Could you try going into settings and coming back to home? This should refresh the list.

I also noticed that favorites songs are marked, but the playlist doesn't appear. I show this at the very start of the video.

https://github.com/zyrouge/symphony/assets/85519676/08152109-ba75-4c18-9aad-170a9489216c

**Comment by SunBreaker1** [comment]
Should I just delete the app and re-install? I'd rather not lose all my playlists, but if that's what it takes, I might as well.

**Comment by zyrouge** [comment]
> Should I just delete the app and re-install? I'd rather not lose all my playlists, but if that's what it takes, I might as well.

Don't. This has already been fixed in main. Will be releasing it under an hour.

**Comment by zyrouge** [comment]
Fixed as of v2023.5.91.
