### ISSUE TITLE
[Feature Request] Option to delete tracks

### ISSUE THREAD

**Issue by soymadip** [zyrouge/symphony#159]
### Description

There is one thing missing in this app, we cannot delete tracks within the app.

### Solution

If a delete button will be added

### Alternatives

For now we have to delete tracks from phone's file manager.

### Checklist

-   I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
Will not be implemented. Refer [#66](https://github.com/zyrouge/symphony/issues/66#issuecomment-1474829364).
