### ISSUE TITLE
[Feature Request] Tree view?

### ISSUE THREAD

**Issue by obibon** [zyrouge/symphony#16]
Hi, fistt of all, thanks for the work.

I'd like to like the app, but I can't use any that doesn't show a tree view. Is it possible to implement a view like in SicMu Player?
In case you don't know it, it basically shows a list of every song, sorted by tree.

Domething like
Folder A - 1
Folder A - 2
Folder A - 3
Folder A - 4
Folder B - 1
Folder B - 2
...
And so on.

Maybe there is already, and I missed it?

Thanks! 😃

**Comment by zyrouge** [comment]
Could you explain it a bit more so I can look if I can implement it. I saw that SicMu does a tree view using genres? Or is it customisable?

**Comment by obibon** [comment]
It has 3 ways of sorting the playlist, but I use only one, which is the one I can't find anywhere else...

The way it works is that you have to have your songs organized, and then it'll show that in a list.

I have one large "Music" folder, with a folder for each album, and the tracks in each, numbered. So, for instance, for my Queen albums, it goes like this:

Queen - 1973 - Queen (that's the name of the folder) / "1 - Keep Yourself Alive" "2 - Doing All Right" and so on will be the names of the files within that folder.

Queen - 1974 - Queen II (name of the next album/folder) / "1 - Procession" "2 - Father to Son" "3 - White Queen"...

Queen - 1974 - Sheer Heart Attack / "1 - Brighton Rock" "2 - Killer Queen"...


Once I have all my albums organized to my liking, what I'd like to see is a list that organizes the songs according to my way of sorting. Otherwise, I find it very difficult to scroll around and find a song.
In SicMu, I get a list from folders A to Z in alphabetical order of folders, according to how they are within this big "Music" folder.

Here's a screenshot of my phone:

https://imgur.com/a/XyvHwCL

As you see, it shows the folders in alphabetical order, and then the tracks within them, also alphabetically, but showing the metadata instead of the filename.

It's kinda hard to explain in writing... I guess it's a way of letting me sort the songs to my liking, and the app should just show that, instead of doing the work of sorting them itself.

I hope I could make it a bit clearer.

**Comment by zyrouge** [comment]
Basically, a tree view with already existing sort formats should imitate that functionality. Will be implemented.

**Comment by NeeRaj-2401** [comment]
This tree view will be implemented under folder tab ?

**Comment by obibon** [comment]
Perfect; thanks! :-)

**Comment by zyrouge** [comment]
Implemented as of v2023.2.59.
