### ISSUE TITLE
[Feature Request] add a like button to a notification

### ISSUE THREAD

**Issue by Wjxfi** [zyrouge/symphony#162]
### Description

![0b9c89ca-8583-4731-b07d-6a3488c580af.jpg](https://github.com/zyrouge/symphony/assets/113500363/00715094-51f5-444c-ac70-73e745e7b6be)

![dfce9c3c-4313-4ea7-85be-0848a96fe51c.jpg](https://github.com/zyrouge/symphony/assets/113500363/2a8aeb08-974d-48c6-9eae-eb29e053d8be)

-

![5f4478eb-3bfb-419d-9b2f-04b00e8bd6a1.jpg](https://github.com/zyrouge/symphony/assets/113500363/92ad89da-7f6f-4ebd-a0f6-bb55ab9e1e03)

in the [retro music player](https://www.f-droid.org/packages/io.github.muntashirakon.Music/) [(metro music player)](https://www.f-droid.org/packages/io.github.muntashirakon.Music/) this is done. You can see how it's done there and do the same. I find this feature very useful because I use it very often. For example, when it is inconvenient to enter the application, on a locked screen or during a game.

### Alternatives

Add a repeat button...
![edcf658b-aeec-47b2-9722-28b3417eebfc.jpg](https://github.com/zyrouge/symphony/assets/113500363/724d479d-d853-4c28-bdf4-c207d682d3a4)

**Comment by zyrouge** [comment]
Will not be implemented. Refer [#147](https://github.com/zyrouge/symphony/issues/147#issuecomment-1566053348).
