### ISSUE TITLE
[Bug] German is not an option in language settings

### ISSUE THREAD

**Issue by Krintni** [zyrouge/symphony#164]
### Description

There is no option in settings to set language to German even though strings were translated into German.

### Steps to Reproduce

1. Go to Settings
2. Click on 'Language'
3. German can not be set as language

### Expected Behavior

There should be an option to set German as the app language / German should be the default if German is the system default.

### Screenshots

![screenshot](https://github.com/zyrouge/symphony/assets/132835834/a16062f0-327a-41d6-8e14-bcb9b5d656eb)

### Device

-   Version 2023.5.91

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
Ah, I did forget to add it in the files.
