### ISSUE TITLE
[Bug] behaviour of Notification media controls

### ISSUE THREAD

**Issue by NeeRaj-2401** [zyrouge/symphony#17]
Half visible:
<img src="https://user-images.githubusercontent.com/88180887/208943943-abe0f123-c1d8-4827-ba65-f352141c6468.jpg" width="50%">

Repeated controls:
<img src="https://user-images.githubusercontent.com/88180887/208943934-3d40ed3a-0db5-48ec-9bb6-a02b747c7abf.jpg" width="50%">

Additional info:
App version: v2022.12.56
Android version: 12 ( Realme ui 3.0)
Device : Realme 7

**Comment by zyrouge** [comment]
> Half visible: <img alt="" width="50%" src="https://user-images.githubusercontent.com/88180887/208943943-abe0f123-c1d8-4827-ba65-f352141c6468.jpg">
> 
> Repeated controls: <img alt="" width="50%" src="https://user-images.githubusercontent.com/88180887/208943934-3d40ed3a-0db5-48ec-9bb6-a02b747c7abf.jpg">
> 
> Additional info: App version: v2022.12.56 Android version: 12 ( Realme ui 3.0) Device : Realme 7

Does this occur everytime? I was able to reproduce this but it required too much of spamming to actually happen for me.

**Comment by NeeRaj-2401** [comment]
> Does this occur everytime?

For me, Yes.

**Comment by zyrouge** [comment]
Can I get steps to reproduce no controls (half controls)?

**Comment by NeeRaj-2401** [comment]
> Can I get steps to reproduce no controls (half controls)?

it happens with any song i m trying to play
so the general steps would also reproduce this

**Comment by zyrouge** [comment]
> > Can I get steps to reproduce no controls (half controls)?
> 
> it happens with any song i m trying to play so the general steps would also reproduce this

That does not seem to occur for me. Could you upload a clip of that happening?

**Comment by zyrouge** [comment]
I'll look into this.
