### ISSUE TITLE
[Bug] Shuffle play shows wrong titles

### ISSUE THREAD

**Issue by Chr0matic1** [zyrouge/symphony#174]
### Description

When pressing shuffle in the top right, the album is played in a random order but the titles in now playing are all still in the albums original order and not the shuffled one, meaning every song played is shown as another wrong one while playing. The same happens for folder shuffle, artist shuffle etc

### Steps to Reproduce

1. Go to albums/folders/artists on the bottom row
2. Open an album
3. Press shuffle play

### Expected Behavior

The song shown in now playing should correspond to the actual song being played, not to the original album/list order.

### Device

-   Device: Galaxy A52s 5G
-   OS: Android 13
-   Version 2023.05.91

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
Fixed as of v2023.5.92.
