### ISSUE TITLE
[Bug] values change all the time. It should say 1876, but it's 6, then 160, then 77, and so on.

### ISSUE THREAD

**Issue by Wjxfi** [zyrouge/symphony#176]
### Description

 values change all the time. It should say 1876, but it's 6, then 160, then 77, and so on.

### Steps to Reproduce

click shuffle and look at "listen to 1 of 66" and others

### Screenshots

values change all the time. It should say 1876, but it's 6, then 160, then 77, and so on.

look at the place where "listen 1 of 66" and others
https://github.com/zyrouge/symphony/assets/113500363/00601d70-b78a-49cd-90fb-6ae549821532

### Device

-   Device: [poco x3 pro]
-   OS: [Android 12]
-   Version [forgot]

**Comment by zyrouge** [comment]
Was the songs still being scanned. Seems like that's the issue. I don't think this is a bug if that is the case.

**Comment by zyrouge** [comment]
> > Was the songs still being scanned. Seems like that's the issue. I don't think this is a bug if that is the case.
> 
> other applications do not have this problem. If it's not a bug, is it supposed to make me wait 2 minutes every time I start the app?

The app caches the songs once it finishes scanning fully. The next time you open the app, the cache will be used. Could you try allow it to cache it fully?

**Comment by zyrouge** [comment]
Unless I can reproduce the issue, I cannot help.

**Comment by zyrouge** [comment]
Possible solution was provided.
