### ISSUE TITLE
[Feature Request] Full LRC support 

### ISSUE THREAD

**Issue by WX580** [zyrouge/symphony#177]
Please add full support for .LRC files. While LRC files are recognized and lyrics are displayed they sadly aren't synced to the time to show lyrics as they are spoken. It would also be nice to be able to tap on a lyric and have it jump to that point in the song

**Comment by zyrouge** [comment]
> Please add full support for .LRC files. While LRC files are recognized and lyrics are displayed they sadly aren't synced to the time to show lyrics as they are spoken. It would also be nice to be able to tap on a lyric and have it jump to that point in the song

The lyrics are not read from the lyric file. The lyrics embedded in the music file is used. There is an issue regarding this #109. Closing this as duplicate.
