### ISSUE TITLE
[Feature Request] Gestures Support 

### ISSUE THREAD

**Issue by ghost** [zyrouge/symphony#18]
Hi,

I think adding gestures support will be awesome.

**For example** -

- Swipe down from the **Now Playing** screen to go to **Library**.
- Swipe up **Mini player** to open **Now Playing** screen.
- Swipe left or right in **Now Playing** to change previous/next song.
- Swipe up **Playing XX out of XX** from **Now Playing** to open songs queue.
- Swipe Left or Right from **Library** to go to left or right screens (to switch between **For You** and **Songs / Album etc** screens.)

For reference see **Black Player**

Thanks! ❤️

**Comment by zyrouge** [comment]
Animations and Gestures will be worked on after stable release.

**Comment by InsaneShukla** [comment]
> Animations and Gestures will be worked on after stable release.

Great! Looking forward to it 😀

**Comment by zyrouge** [comment]
Moved to #37.
