### ISSUE TITLE
[Bug] Covers not showing

### ISSUE THREAD

**Issue by phw** [zyrouge/symphony#188]
### Description
This is a bit odd: I have Symphony v2023.6.93 installed on two devices, one running Android 12 and one running Android 9. Both have a copy of the exact same music library with around ~4600 tracks on the SD card.

On the Android 12 system everything is fine. On the Android 9 system all the covers are missing. I already tried clearing the app data and reading the library fresh.

I also cross-checked on the device with the Metro and Simple Music Player apps (both installed from f-droid), and both of those show the library with all album covers.

### Steps to Reproduce

Fresh start of the app. Wait for the library sync to complete.

All the cover images show the black default fallback.

### Expected Behavior
Album covers being shown

### Screenshots

![Screenshot_20230609_140118_io github zyrouge symphony](https://github.com/zyrouge/symphony/assets/29852/9031890b-6f8c-457b-892e-99b41e7869f0)

This is what shows up in Simple Music Player

![Screenshot_20230609_140452_com simplemobiletools musicplayer](https://github.com/zyrouge/symphony/assets/29852/bdf967a2-4de8-496b-803a-e53a9ef33a09)

### Device

-   Device: Huawei p-smart 2019
-   OS: Android 9
-   Version: v2023.6.93

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by siggi1984** [comment]
> 

I have the same problem that the covers are not displayed.

Samsung Galaxy a8
Android 9

**Comment by zyrouge** [comment]
I guess this happens only in Android 9. MediaStore implementations older than Android 10 pretty much not good as the newer ones.

**Comment by zyrouge** [comment]
Is this still relevant?

**Comment by phw** [comment]
@zyrouge I can't say for sure, I don't have the Android 9 device available anymore.

**Comment by zyrouge** [comment]
> Hi,
> 
> I am on Android 12.
> 
> Covers embedded in files show as expected.
> 
> But I have an album with FLAC where the cover is at album directory level (`cover.jpg` and `front.jpg`). In this case the cover does not show in the player.

Those are not supported.

**Comment by jej** [comment]
Ok. Do you think it may be implemented easily? I don't know kotlin a lot but can have a look if you give some hints...

**Comment by zyrouge** [comment]
> Ok. Do you think it may be implemented easily? I don't know kotlin a lot but can have a look if you give some hints...

I guess it would be using MediaStore to gather images, you will need to identify if the folder the images lies in is an album, if so, you would have found the image. This is the only hardest part, modifying the application to use it is pretty easy.

**Comment by jej** [comment]
Ok. And starting from the audio file? Looking at the same path level if a conventional 'cover' file exists?

**Comment by zyrouge** [comment]
> Ok. And starting from the audio file? Looking at the same path level if a conventional 'cover' file exists?

That could work too. But you have to make sure that it not too slow. Probably, checking directory once should not be too bad. Also, we should probably consider if there are existing standards/specifications to do this (ex: M3U files to create a playlist).

**Comment by zyrouge** [comment]
This should be fixed along with the implementation of metadata decoder.
