### ISSUE TITLE
[Feature Request] Song loading from SD card

### ISSUE THREAD

**Issue by Harith163** [zyrouge/symphony#192]
### Description

Currently, when songs are loaded from an SD card into the playable list, they are loaded in what i'm assuming is alphabetical order. This leads to partially full albums. Since loading takes time and since most albums have titles through the alphabet, this means having to wait a long time before you can start playing your albums
### Solution

In my case, the music is already categorized into folders corresponding to the album. Maybe load folder by folder?

### Alternatives

Do the same process, but allow to force load a folder/album by tapping on it, giving it priority.

### Additional Context

none

### Checklist

-   [yes] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
There is no way of prioritizing folders. All the things like sorting are only done after reading files in order MediaStore indexed them. Closing this since there is no viable solution. Feel free to let in your thoughts.

**Comment by Harith163** [comment]
ok. Thank you!
