### ISSUE TITLE
[Feature Request] Export playlists

### ISSUE THREAD

**Issue by SimoLRepo** [zyrouge/symphony#204]
### **Description**
Hi, I noticed that Symphony doesn't have an option to export playlists (import option only). Is it possible to implement it? Thank you

### **Solution**
I click the three vertical dots at the top right on a playlist and then click "Export playlist". A screen appears to be able to decide where to save the m3u file.

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by SunBreaker1** [comment]
I would definitely help when people get new phones and don't want to manually go through their songs and re-create their playlists

**Comment by SimoLRepo** [comment]
@zyrouge I don't care the implementation of such a feature (if it is ever implemented), I no longer need to use Symphony having found a better alternative. I sincerely feel sorry for users @SunBreaker1  and @Wjxfi , unfortunately I have to close this issue as it has been too many months since it was opened without any implementation (there are plenty of other feature requests opened by other users but not yet implemented).

**Comment by zyrouge** [comment]
> @zyrouge I don't care the implementation of such a feature (if it is ever implemented), I no longer need to use Symphony having found a better alternative. I sincerely feel sorry for users @SunBreaker1 and @Wjxfi , unfortunately I have to close this issue as it has been too many months since it was opened without any implementation (there are plenty of other feature requests opened by other users but not yet implemented).

Not sure who hurt your feelings but that's alright. It's true that I don't actively work on Symphony because I am a college student who doesn't just sit at home and maintain his projects full-time. I barely get any time to work on my projects (around an hour every day). If you think it's very easy to do these things, you should try implementing and making a PR for it.

Tracked at #243.

**Comment by SimoLRepo** [comment]
> > @zyrouge I don't care the implementation of such a feature (if it is ever implemented), I no longer need to use Symphony having found a better alternative. I sincerely feel sorry for users @SunBreaker1 and @Wjxfi , unfortunately I have to close this issue as it has been too many months since it was opened without any implementation (there are plenty of other feature requests opened by other users but not yet implemented).
> 
> Not sure who hurt your feelings but that's alright. It's true that I don't actively work on Symphony because I am a college student who doesn't just sit at home and maintain his projects full-time. I barely get any time to work on my projects (around an hour every day). If you think it's very easy to do these things, you should try implementing and making a PR for it.
> 
> Tracked at #243.

@zyrouge Nothing personal 😕, I just found an alternative which meets my needs (Moreover the developer of that app has a similar university situation to yours).

PS. I am aware that programming is complicated (I also know some programming and scripting languages)...

Goodbye.
