### ISSUE TITLE
[Bug] CJK text does not display correctly (sometimes)

### ISSUE THREAD

**Issue by BenDundon** [zyrouge/symphony#205]
### Description

CJK text does not display.

### Steps to Reproduce

1. add an album with either an artist or a song that has CJK characters in it (Hiragana, Katakana, Kanji, Hanzi, or Hangul)
2. View the album in the library
3. Text is replaced with questionmarks

### Expected Behavior

Text is displayed as normal

### Screenshots

![Screenshot_2023-06-25-19-58-28-19_c328a126cb0fb561391a2f6f61559b68.jpg](https://github.com/zyrouge/symphony/assets/30951911/59806bcc-1b21-4947-9bf8-2b3768a55a2f)

![Screenshot_2023-06-25-19-59-12-16_c328a126cb0fb561391a2f6f61559b68.jpg](https://github.com/zyrouge/symphony/assets/30951911/4d55c24d-1b07-4ac2-bf16-4518bd8485c7)

### Device

-   Device: OnePlus 10 Pro
-   OS: Oxygen OS 13.1 (Android 13)
-   Version 2023.05.05

### Additional info

Not *all* CJK text is missing. For example ![Screenshot_2023-06-25-20-00-03-04_c328a126cb0fb561391a2f6f61559b68.jpg](https://github.com/zyrouge/symphony/assets/30951911/9131ffd6-6f52-4550-8d16-98ee17a60e7b)

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
Could you try changing fonts?

**Comment by zyrouge** [comment]
This could potentially be the font not supporting those characters.

**Comment by zyrouge** [comment]
Another possibility is that, the metadata provided by MediaStore doesn't support those characters.

**Comment by BenDundon** [comment]
> Could you try changing fonts?
> This could potentially be the font not supporting those characters.

Unfortunately it looks to be font-independent - at least in the fonts Symphony supports. It could be MediaStore-related, actually, as the titles show up fine on my PC even when displaying in, say, Roboto. Doesn't quite make sense to me why this would only affect _some_ text, though...

**Comment by zyrouge** [comment]
> > Could you try changing fonts?
> > This could potentially be the font not supporting those characters.
> 
> Unfortunately it looks to be font-independent - at least in the fonts Symphony supports. It could be MediaStore-related, actually, as the titles show up fine on my PC even when displaying in, say, Roboto. Doesn't quite make sense to me why this would only affect _some_ text, though...

Could you upload a song file that has this issue? I could try testing.

**Comment by BenDundon** [comment]
Hmm, this isn't an issue with Symphony. I tested on a similar app, [Auxio](https://github.com/OxygenCobalt/Auxio), and it has the same issue. MediaStore looks very likely. Would you still like me to send you a sample file for testing?

**Comment by zyrouge** [comment]
> Hmm, this isn't an issue with Symphony. I tested on a similar app, [Auxio](https://github.com/OxygenCobalt/Auxio), and it has the same issue. MediaStore looks very likely. Would you still like me to send you a sample file for testing?

Yeah.

**Comment by BenDundon** [comment]
I've requested to be your friend on Discord, I'll send it to you there.

**Comment by zyrouge** [comment]
Seems to work just fine for me.

![Screenshot_2023-08-02-22-39-22-337_io github zyrouge symphony debug](https://github.com/zyrouge/symphony/assets/50770114/f1a3e59f-c49e-4eff-b18d-432ae03c9d72)

**Comment by BenDundon** [comment]
That's really strange. Do you mind sharing details about your device? (Make/model/OS version?) Mine is a OnePlus 10 imported from mainland China, so I'd have expected that it would have support for these characters, however this, combined with the fact that Auxio has the same issue, seems to suggest that it's an Android or OnePlus issue rather than a Symphony issue. Feel free to close if you don't want to investigate further.

**Comment by zyrouge** [comment]
> That's really strange. Do you mind sharing details about your device? (Make/model/OS version?) Mine is a OnePlus 10 imported from mainland China, so I'd have expected that it would have support for these characters, however this, combined with the fact that Auxio has the same issue, seems to suggest that it's an Android or OnePlus issue rather than a Symphony issue. Feel free to close if you don't want to investigate further.

Mi 11 Lite NE 5G running MIUI 14.

**Comment by zyrouge** [comment]
Closing this since it seems like an device specific issue.
