### ISSUE TITLE
[Bug] - Crash error and edit playlist songs

### ISSUE THREAD

**Issue by SimoLRepo** [zyrouge/symphony#208]
### Description

Hi, when I open the Symphony application and click on a song to play it, I get a full screen red error message.

I also wanted to report out that it is currently not possible to remove <sup>[[1]](https://github.com/zyrouge/symphony/issues/89)</sup>, add <sup>[2]</sup> and reorder <sup>[[3]](https://github.com/zyrouge/symphony/issues/130)</sup> songs with in a playlist. These options either have not been implemented or do not appear.

Thank you.

[2] - By clicking the "Add to playlist" option, the imported playlists will not appear in the list. Only "Favorites" appears.

### Steps to Reproduce

1. I open the application Symphony
2. I go to a playlist (in this case imported)
3. I click on a song to play it
4. The error appears
5. I close the application and repeat the previous procedure, the error no longer appears. By restarting the device and repeating the procedure again, the error reappears.

### Expected Behavior

The error should not appear. The required features should appear.

### Screenshots

<a href="https://drive.google.com/file/d/1U8KrGWUz2UK5MGa1AZ0BEgsDMr_gO5RP/view?usp=sharing">Here is the screenshot of the error</a>

### Device

-   Device: Oppo Reno2 Z
-   OS: Android 11
-   Version: v2023.6.93

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
Imported playlists do not support any modifications. Only playlists created within the app can be modified. This is the intended behaviour.

**Comment by SimoLRepo** [comment]
> Imported playlists do not support any modifications. Only playlists created within the app can be modified. This is the intended behaviour.

@zyrouge I don't agree, music players usually allow you to import and even edit such playlists. It will mean that I will use another music player. Thank you all the same.
