### ISSUE TITLE
[Bug] Playlists don't have cover

### ISSUE THREAD

**Issue by SunBreaker1** [zyrouge/symphony#209]
### Description

The bug related to #154 still persists

### Steps to Reproduce

Refer to video

### Expected Behavior

Playlists should show covers

### Screenshots

https://github.com/zyrouge/symphony/assets/85519676/0d1c96e3-e527-4540-9036-436f16abd344

### Device

-   Device: [Galaxy S23+]
-   OS: [Android 13; One Ui 5.1]
-   Version  [2023.6.93]

### Additional Context

Also applies when adding full albums to playlists

### Checklist

-   [X] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
Are you sure that you are on latest version? That seems like an older version.

**Comment by SunBreaker1** [comment]
> Are you sure that you are on latest version? That seems like an older version.

I'm (always) on the latest release

**Comment by zyrouge** [comment]
> > Are you sure that you are on latest version? That seems like an older version.
> 
> I'm (always) on the latest release

I cannot seem to reproduce this issue.

**Comment by SunBreaker1** [comment]
> > > Are you sure that you are on latest version? That seems like an older version.
> > 
> > I'm (always) on the latest release
> 
> I cannot seem to reproduce this issue.

I'll wait for the next release, if bit maybe I'll try a clean install, I won't loose much from my playlists since I put off making them because of this bug

**Comment by zyrouge** [comment]
> > > > Are you sure that you are on latest version? That seems like an older version.
> > > 
> > > 
> > > I'm (always) on the latest release
> > 
> > 
> > I cannot seem to reproduce this issue.
> 
> I'll wait for the next release, if bit maybe I'll try a clean install, I won't loose much from my playlists since I put off making them because of this bug

Clean install would probably not fix this issue. On the other side, I am not able to reproduce this issue.

**Comment by SunBreaker1** [comment]
> > > > > Are you sure that you are on latest version? That seems like an older version.
> > > > 
> > > > 
> > > > I'm (always) on the latest release
> > > 
> > > 
> > > I cannot seem to reproduce this issue.
> > 
> > I'll wait for the next release, if bit maybe I'll try a clean install, I won't loose much from my playlists since I put off making them because of this bug
> 
> Clean install would probably not fix this issue. On the other side, I am not able to reproduce this issue.

Yeah, I don't know what else I can help with, I updated to the newest release and re-scaned, it's still happening

**Comment by zyrouge** [comment]
Is this still relevant?
