### ISSUE TITLE
[Feature Request] Toggle for black theme with system

### ISSUE THREAD

**Issue by kanishk-upadhyay** [zyrouge/symphony#213]
### Description

When i set the theme to system, it turns on dark mode whenever the system dark mode is turned on however i want it to set to black 

### Solution

Add a toggle/checkbox for the black theme

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
:tada: Implemented as of v2023.7.104!
