### ISSUE TITLE
[Bug] App crashes when changing system theme

### ISSUE THREAD

**Issue by kanishk-upadhyay** [zyrouge/symphony#214]
### Description

Whenever i change the system light mode to dark mode in the app, it crashes.

### Steps to Reproduce

See on screen recording 

### Screen recording 

https://github.com/zyrouge/symphony/assets/66172350/8074c954-1fa5-4774-8022-ada2301ca1f1

### Device

-   Device: realme x7 max
-   OS: Android 13
-   Version: RMX3031_11_F.13

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
:tada: Fixed as of v2023.7.104!
