### ISSUE TITLE
[Bug] Symphony stuck while trying to reproduce m4a using alac encoder

### ISSUE THREAD

**Issue by DomHeadroom** [zyrouge/symphony#219]
### Description

Symphony isn't able to reproduce a m4a file that uses the alac encoder.

### Steps to Reproduce

1. Add a m4a file using alac encoder to your library
2. Try to reproduce the file

### Expected Behavior

To be able to play the song

### Device

-   Device: PocoX3 NFC
-   OS: Android 13, LineageOS 20 
(but it was happening on MIUI Android 12 too)
-   Version: 2023.6.93

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

https://cdn.discordapp.com/attachments/465234818352021524/1133842942784712786/sample.m4a
This is a test file (I couldn't upload it on github because it gave me an error for some reason)

**Comment by zyrouge** [comment]
I'm not sure if Android supports ALAC format. Refer [this](https://developer.android.com/guide/topics/media/platform/supported-formats#audio-formats).

**Comment by Domefemia** [comment]
> I'm not sure if Android supports ALAC format. Refer [this](https://developer.android.com/guide/topics/media/platform/supported-formats#audio-formats).

Mpv play the file on Android without any problem, soo.

**Comment by zyrouge** [comment]
> > I'm not sure if Android supports ALAC format. Refer [this](https://developer.android.com/guide/topics/media/platform/supported-formats#audio-formats).
> 
> Mpv play the file on Android without any problem, soo.

MPV has it's own implementation of decoders. Symphony uses Android Media3.

**Comment by zyrouge** [comment]
Seems like I could play the file just fine.

**Comment by Domefemia** [comment]
Uploading VID_20230727_185005_148.mp4 …

That's not the case for me as you can see on this video.

**Comment by zyrouge** [comment]
> 

Seems like I have higher bitrate (2116kbps) instead of the one displayed in yours. This issue could be device specific at this point.

**Comment by Domefemia** [comment]
I have trying reproducing the same sample audio on another app that use android.media.MediaPlayer (https://f-droid.org/packages/ch.blinkenlights.android.vanilla/) and it doesn't work there too, I'm gonna try with another devices when I get home in some days.

**Comment by zyrouge** [comment]
Could you possibly try on some other device and see if this occurs there as well?

**Comment by zyrouge** [comment]
Is this still relevant?

**Comment by DomHeadroom** [comment]
The problem is still there for me, but I need an android 9 or higher phone to test if does happen elsewhere too.

**Comment by zyrouge** [comment]
> The problem is still there for me, but I need an android 9 or higher phone to test if does happen elsewhere too.

I already test on Android 13. Will try reproducing this on Android 9.

**Comment by DomHeadroom** [comment]
Ok, I did some testing,  and I found the root cause of the problem, you are probably testing the app with an avd of android with google's api, I have tested if the song get played on an avd withoutthem (like my phone where I use microg) and I able to reproduce the problem. 
But I pretty much sure it's not a symphony problem

**Comment by zyrouge** [comment]
> Ok, I did some testing, and I found the root cause of the problem, you are probably testing the app with an avd of android with google's api, I have tested if the song get played on an avd without them (like my phone where I use microg) and I able to reproduce the problem. But I pretty much sure it's not a symphony problem.

I guess I'll go ahead and close this. Any PRs are welcome nonetheless.

**Comment by rahul-gill** [comment]
exo player with ffmpeg extension can play ALAC files that android MediaPlayer can't
