### ISSUE TITLE
[Feature] Sort songs by 'track number' tag when playing album

### ISSUE THREAD

**Issue by foldfree** [zyrouge/symphony#22]
Using 2022.12.56,
When playing an album, the default track order is alphabetical name.

 A sane default would be according to 'disc number', 'track number' tags of files that have the same 'album artist' field. (In case there is 2 different releases that have the same 'album' name, 'album artist' would set them apart)

 Right now I use filename because I have my files named with track numbers in the beginning but it would be a PITA for someone that doesn't have track number in the filename of their audio library.

**Comment by zyrouge** [comment]
Implemented as of v2023.2.59.
