### ISSUE TITLE
[Bug] Random pauses in music

### ISSUE THREAD

**Issue by fillwithjoy1** [zyrouge/symphony#223]
### Description
Playing music, but the player randomly pauses. I am not pausing the music in any way and the app is pausing the music by itself at random intervals. I'm using a Pixel 6 Pro

### Steps to Reproduce

1. Play music
2. Be pissed after a couple of minutes because the music stops by itself

### Expected Behavior
To play

### Screenshots

> Attached below.

### Device

-   Device: Google Pixel 6 Pro
-   OS: Android 13
-   Version: 2023.6.93

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by fillwithjoy1** [comment]
Okay, now the app is randomly resuming the music after playing the music....

**Comment by fillwithjoy1** [comment]
https://github.com/zyrouge/symphony/assets/29514446/31ac64dc-4ca4-4c57-a568-03991a4cdde7

Some more footage.

**Comment by fillwithjoy1** [comment]
Could this be possibly due to bluetooth connection?

**Comment by fillwithjoy1** [comment]
Yep, just found the error - my smartwatch periodically disconnects and reconnects to my phone. The app is automatically resuming/pausing media based on that. Maybe that could be fixed?

**Comment by fillwithjoy1** [comment]
I will say this though - If NEARBY_DEVICES permission is denied, the app still pauses whenever headphones disconnect.

**Comment by zyrouge** [comment]
> I will say this though - If NEARBY_DEVICES permission is denied, the app still pauses whenever headphones disconnect.

Kindly open a new issue for this. This should be fixable.
