### ISSUE TITLE
[Bug] Auto pause/play setting triggered by unwanted accessories

### ISSUE THREAD

**Issue by fillwithjoy1** [zyrouge/symphony#224]
### Description
In the app there are 2 settings that rely on the NEARBY_DEVICES permission
1. Play on headphones connect
2. Pause on headphones disconnect

These 2 permissions rely on the NEARBY_DEVICES permission to know when a bluetooth accessory has been connected/disconnected.
However **any** accessory can trigger it, which ends up being annoying for people who connect their watches to their phones.
Basically, the setting is working _too_ well

### Steps to Reproduce

1. Enable 2 settings "Play on headphones connect" and "Pause on headphones disconnect"
2. Grant NEARBY_DEVICES permission
3. Play music
4. Disconnect the watch from the phone
5. Music pauses
6. Reconnect the phone
7. Music resumes

### Expected Behavior
Disconnecting watch shouldn't pause the music and same goes for reconnecting

### Screenshots
Don't really have any

### Device

-   Device: Google Pixel 6 Pro
-   OS: Android 13
-   Version: v2023.7.104

### Additional Context
Possibly laptops could trigger it and other phones as well 🤷

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by th1nhhdk** [comment]
I have the same problem, thanks for reporting it!
