### ISSUE TITLE
Magnifier icon should be on the right side when unused.

### ISSUE THREAD

**Issue by foldfree** [zyrouge/symphony#23]
For the sake of consistency with android material language, the magnifier lens icon should be on the right side of the screen.
It would move to the left when the input search box is activated.

See for reference: newpipe, odyssey, auxio, bitwarden, harmonic.

**Comment by zyrouge** [comment]
Design choices are subjective. Consistency does matter but here, if the search icon is moved, the left side would be left blank since there is no sidebar. Closing this since it's really just subjective.
