### ISSUE TITLE
[Feature Request] Support m4b format

### ISSUE THREAD

**Issue by BradNut** [zyrouge/symphony#230]
### Description

As the title states the app is unable to find audio file with m4b extension (an audio book format).

### Steps to Reproduce

1. Put a file of extension type m4b in a directory Symphony has access to
2. Refresh the app song index
3. The audio file will not be shown

### Expected Behavior

Be able to see and play audio files of this file extension.

### Device

-   Device: Google Pixel 7 Pro
-   OS: Android 13
-   Version 2023.8.105

### Checklist

-   [X] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
Seems like mp3, m4a and m4b uses same format, so this should be easy to implement.

> Use `audio/mp4a-latm` filter (for my reference)

**Comment by zyrouge** [comment]
I'm on Android 13 and it seems like both `.m4a` and `.m4b` files are recognized.
