### ISSUE TITLE
Accessing music files from apps private storage

### ISSUE THREAD

**Issue by 133usr** [zyrouge/symphony#232]
### Description

Can it access files from  
Or
```java
/data/data/io.github.sympho.../files
``` 
That is private storage of the app itself? 
### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
What do you actually mean?

**Comment by 133usr** [comment]
Reading music files from /data/data/app/files
context.getFilesDir()

**Comment by zyrouge** [comment]
> Reading music files from /data/data/app/files context.getFilesDir()

It can, but it current implementation may or may not scan them since it scans only enternal files.

**Comment by zyrouge** [comment]
Closing this due to uncertainty. Feel free to open a new issue.
