### ISSUE TITLE
[Bug] File scanning is limited to 1 folder only

### ISSUE THREAD

**Issue by fillwithjoy1** [zyrouge/symphony#233]
### Description
The app's ability to scan folders for music is limited to the very first folder it sees in the 'Music' folder, ignoring any other that may reside in the "Music" directory. This also impacts my ability to use blacklist or whitelist to fix an issue like this.

### Steps to Reproduce
1. Open files
2. Create 2 folders in Music
3. Put some music in both
4. Reinstall app
5. App only sees the first folder (alphabetically) and only shows that folder's music

### Expected Behavior
See all the music 

### Screenshots
![image](https://github.com/zyrouge/symphony/assets/29514446/06218baf-68ba-4341-a306-05216a8ffdf0)
2 folders are contained here

![image](https://github.com/zyrouge/symphony/assets/29514446/16d3fc55-1b9a-4cab-9561-e26d64cfb358)
However the app only sees the first folder. Cannot update whitelists or blacklists manually

### Device
-   Device: Windows Subsystem for Android
-   OS: Android 13
-   Version: 2023.07.104

### Additional Context
Also impacts my Pixel 6 Pro

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by fillwithjoy1** [comment]
Updated to 2023.07.105, still persists

**Comment by fillwithjoy1** [comment]
Okay, turns out I somehow reinstalled the wrong version. 2023.08.105 fixes the issue now

**Comment by zyrouge** [comment]
Alright.
