### ISSUE TITLE
[Feature Request] Add albums, artist and other playlist to playlists

### ISSUE THREAD

**Issue by BioRider17** [zyrouge/symphony#24]
I think an awesome qol feature would be to add an entire album to a playlist.

**Comment by zyrouge** [comment]
Would do it for artist and playlists as well.

**Comment by sojusnik** [comment]
Don't forget about folders (in folders view). You can already add songs from the folders view, but not whole folders, because the 3-dot menu on the right is missing on folders.

**Comment by sojusnik** [comment]
Thanks for the new version! Folders received a 3-dot menu, but it's only shown properly, if the name of the folder is not longer than one line. Else it's barely visible or displaced. You can easily check that when changing from vertical to horizontal view.

**Comment by zyrouge** [comment]
Implemented as of v2023.2.68.

> Thanks for the new version! Folders received a 3-dot menu, but it's only shown properly, if the name of the folder is not longer than one line. Else it's barely visible or displaced. You can easily check that when changing from vertical to horizontal view.

Fix had been implemented in dev and should be expected to be released in next update.
