### ISSUE TITLE
[Bug] Music control panel not showing in notifications 

### ISSUE THREAD

**Issue by Lujixe** [zyrouge/symphony#250]
Hello everyone,

I think the title is pretty self-explanatory, the classic notification on the notifications panel indicating the music actually playing and the commands with it are not showing

I cannot really screen as there's literally nothing on the panel despite the fact that a music is currently running through Symphony in the background

Do you have any idea ?

PS : Oppo phone

**Comment by zyrouge** [comment]
Could you attach a screenshot?

**Comment by Lujixe** [comment]
I'm kinda blind actually..

I close it, I'm sorry.
