### ISSUE TITLE
Release on Google Play

### ISSUE THREAD

**Issue by sojusnik** [zyrouge/symphony#26]
Your music player looks awesome! May I ask why it's still not released on F-Droid or Google Play?

**Comment by zyrouge** [comment]
> Your music player looks awesome! May I ask why it's still not released on F-Droid or Google Play?

I am planning for a Google Play release if enough donations rack up. Also once stable version is released, I would definitely release it in F-droid.

**Comment by Jose14** [comment]
Good morning, I would love to see the artist, genre, composer separator function in the application. Also the feature of high quality cover art and synchronized lyrics. But in the future next

**Comment by zyrouge** [comment]
I guess this is the end of the issue. Symphony is now on Play Store! 🎉
