### ISSUE TITLE
[Feature Request] Dedicated Favorites Playlist

### ISSUE THREAD

**Issue by SunBreaker1** [zyrouge/symphony#27]
Add the option to favorite a song into a dedicated favorites playlist with out having to create a manual playlist.

The Favorites should also be able to appear on the bottom taskbar and have a quick add on the song, have like a heart icon to quick add

**Comment by sojusnik** [comment]
Great idea! A "heart" button in the "now playing" view would be awesome to quickly add a song to the "favourites" playlist.

**Comment by zyrouge** [comment]
Implemented as of v2023.2.68.
