### ISSUE TITLE
[Bug] Once dismissed, playback notification doesn't come back

### ISSUE THREAD

**Issue by gradha** [zyrouge/symphony#273]
[Moving to GitHub as requested on reddit forum](https://www.reddit.com/r/symphony_app/comments/15qnq4i/once_dismissed_playback_notification_doesnt_come/)

### Description

Trying the app at some point I pressed the stop button on the notification and it made the notification close. However, after going into the app and playing again the music, the notification doesn't appear again. It seems to be gone forever and nothing I do other than force stopping the app makes it come back (and if I force stop the app my playlists are gone).

### Steps to Reproduce

https://github.com/zyrouge/symphony/assets/101927/497952c7-f775-45ec-857d-1fdb4f7b7546

### Expected Behavior

I'd expect starting to play music again to bring back the playback notification.

### Device

Running on Poco F3, xiaomi-eu 13.0.9 Android 12.

### Checklist

-   [X] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
Closing this since it has been fixed in recent versions.
