### ISSUE TITLE
[Bug] blacklisted folders still checked when you rescan library

### ISSUE THREAD

**Issue by RustoMCSpit** [zyrouge/symphony#287]
i blacklisted a voice recordings folder that has files named after the number date they were recorded and i can tell it's still being scanned even if its contents dont show because only my songs that start with numbers show after a rescan for the first minute

**Comment by zyrouge** [comment]
> i blacklisted a voice recordings folder that has files named after the number date they were recorded and i can tell it's still being scanned even if its contents dont show because only my songs that start with numbers show after a rescan for the first minute

It is scanned since the app wouldn't know what entities it has access to. But could you be clear on "does it still show the blacklisted songs?"

**Comment by RustoMCSpit** [comment]
> > i blacklisted a voice recordings folder that has files named after the number date they were recorded and i can tell it's still being scanned even if its contents dont show because only my songs that start with numbers show after a rescan for the first minute
> 
> It is scanned since the app wouldn't know what entities it has access to. But could you be clear on "does it still show the blacklisted songs?"

it doesnt show rhe blaxklisted songs no, but it shpuldnt scan a blacklisted folders's contents

**Comment by zyrouge** [comment]
Ok, I'll explain why scanning all the folders are necessary. The app cannot know what folders it has access to without scanning everything since it uses `MediaStore`. Even if the app does not scan them, the feature of whitelisting and blacklisting folders would not be usable since the folder explorer would not show the un-scanned folders.

**Comment by RustoMCSpit** [comment]
> Ok, I'll explain why scanning all the folders are necessary. The app cannot know what folders it has access to without scanning everything since it uses `MediaStore`.

it's not the folders, it's the folders' contents. it can scan the foldwr, know it's blacklisred, and skip scanning its contents

**Comment by zyrouge** [comment]
> > Ok, I'll explain why scanning all the folders are necessary. The app cannot know what folders it has access to without scanning everything since it uses `MediaStore`.
> 
> it's not the folders, it's the folders' contents. it can scan the foldwr, know it's blacklisred, and skip scanning its contents

The app queries all songs. It does not directly scan on filesystem. The path is used to manually build a virtual file structure using which things work.

https://github.com/zyrouge/symphony/blob/6cb44d89b159dc34e61d641405dcbbe00bcc3cf2/app/src/main/java/io/github/zyrouge/symphony/services/groove/MediaStoreExposer.kt#L26
https://github.com/zyrouge/symphony/blob/6cb44d89b159dc34e61d641405dcbbe00bcc3cf2/app/src/main/java/io/github/zyrouge/symphony/services/groove/MediaStoreExposer.kt#L53

**Comment by RustoMCSpit** [comment]
any reason why the app re-scans every time you open it? could it not just rescan only manually

**Comment by RustoMCSpit** [comment]
> The app queries all songs. It does not directly scan on filesystem. The path is used to manually build a virtual file structure using which things work.

define '...things [which] work', im not following?

**Comment by zyrouge** [comment]
> any reason why the app re-scans every time you open it? could it not just rescan only manually

That's a bug, it will be fixed.

**Comment by zyrouge** [comment]
> > The app queries all songs. It does not directly scan on filesystem. The path is used to manually build a virtual file structure using which things work.
> 
> define '...things [which] work', im not following?

Blacklisting, whitelisting, M3U playlist songs, folder view, Tree view, etc.

**Comment by RustoMCSpit** [comment]
> > > The app queries all songs. It does not directly scan on filesystem. The path is used to manually build a virtual file structure using which things work.
> > 
> > 
> > define '...things [which] work', im not following?
> 
> Blacklisting, whitelisting, M3U playlist songs, folder view, tree view, etc.

can the virtual file structure not pass by folders it doesnt need to scan

**Comment by zyrouge** [comment]
> > > > The app queries all songs. It does not directly scan on filesystem. The path is used to manually build a virtual file structure using which things work.
> > > 
> > > 
> > > define '...things [which] work', im not following?
> > 
> > 
> > Blacklisting, whitelisting, M3U playlist songs, folder view, tree view, etc.
> 
> can the virtual file structure not pass by folders it doesnt need to scan

Virtual file structure is built on top of the result of the scan query. The scan query doesn't know what to skip until it scans it.

**Comment by zyrouge** [comment]
> > > > > > The app queries all songs. It does not directly scan on filesystem. The path is used to manually build a virtual file structure using which things work.
> > > > > 
> > > > > 
> > > > > define '...things [which] work', im not following?
> > > > 
> > > > 
> > > > Blacklisting, whitelisting, M3U playlist songs, folder view, tree view, etc.
> > > 
> > > 
> > > can the virtual file structure not pass by folders it doesnt need to scan
> > 
> > 
> > Virtual file structure is built on top of the result of the scan query. The scan query doesn't know what to skip until it scans it.
> 
> can there be a csv or something that the scanner reads beforehand to know what file names are whitelisted then

That's not a practical solution.

**Comment by RustoMCSpit** [comment]
> > > > > > > The app queries all songs. It does not directly scan on filesystem. The path is used to manually build a virtual file structure using which things work.
> > > > > > 
> > > > > > 
> > > > > > define '...things [which] work', im not following?
> > > > > 
> > > > > 
> > > > > Blacklisting, whitelisting, M3U playlist songs, folder view, tree view, etc.
> > > > 
> > > > 
> > > > can the virtual file structure not pass by folders it doesnt need to scan
> > > 
> > > 
> > > Virtual file structure is built on top of the result of the scan query. The scan query doesn't know what to skip until it scans it.
> > 
> > 
> > can there be a csv or something that the scanner reads beforehand to know what file names are whitelisted then
> 
> That's not a practical solution.

but this is an even more impractical implementation so it'd be a net good, can you think of any better implementations?
