### ISSUE TITLE
[Feature Request]  Split artist and album-artist tags with (, & ;) separators.

### ISSUE THREAD

**Issue by bouletteewok** [zyrouge/symphony#29]
dream on this feature because last fm do not recognise tracks with ~

**Comment by zyrouge** [comment]
> dream on this feature because last fm do not recognise tracks with ~

What do you mean? Also, this app depends upon the MediaStore API, thus, this should be easily fixable by having proper meta tags. Anything that does post-processing within the app is highly discouraged due to additional complexity. Closing this now but let me know you need some answers.

**Comment by Icarus-Xu** [comment]
Hi @zyrouge ,

Not sure if my issue has something to do with this, but plz check out my screenshot below:

![1677951306901](https://user-images.githubusercontent.com/11155311/222920531-8d9a8c6b-deba-4b9e-b0b0-238e20c84c6d.jpg)

In this page shows some "artists" with several actual artist names combined, and when I click into that "artist", take "Alan Walker/Benjamin Ingrosso" for example, shows this:

![1677951306896](https://user-images.githubusercontent.com/11155311/222920595-2e472257-bf03-4e5a-848c-fedc446ad072.jpg)

so I checked the details of these 4 songs, they are from the same file with metadata like this:

![image](https://user-images.githubusercontent.com/11155311/222920638-733a38bc-8cd0-415f-b454-6911a9b98a7f.png)

i would very much like to know what has gone abnormal on this file, FYI another app named [muche](https://github.com/moritz-weber/mucke) works good on this file

[02 - Man On The Moon.zip](https://github.com/zyrouge/symphony/files/10889278/02.-.Man.On.The.Moon.zip)

Thank you in advance

**Comment by zyrouge** [comment]
> Hi @zyrouge ,
> 
> Not sure if my issue has something to do with this, but plz check out my screenshot below:
> 
> ![1677951306901](https://user-images.githubusercontent.com/11155311/222920531-8d9a8c6b-deba-4b9e-b0b0-238e20c84c6d.jpg)
> 
> In this page shows some "artists" with several actual artist names combined, and when I click into that "artist", take "Alan Walker/Benjamin Ingrosso" for example, shows this:
> 
> ![1677951306896](https://user-images.githubusercontent.com/11155311/222920595-2e472257-bf03-4e5a-848c-fedc446ad072.jpg)
> 
> so I checked the details of these 4 songs, they are from the same file with metadata like this:
> 
> ![image](https://user-images.githubusercontent.com/11155311/222920638-733a38bc-8cd0-415f-b454-6911a9b98a7f.png)
> 
> i would very much like to know what has gone abnormal on this file, FYI another app named [muche](https://github.com/moritz-weber/mucke) works good on this file
> 
> [02 - Man On The Moon.zip](https://github.com/zyrouge/symphony/files/10889278/02.-.Man.On.The.Moon.zip)
> 
> Thank you in advance

That's how MediaStore actually stores multiple artists. May I know what were you expecting to happen? The album artist page could be used to kinda fix this. Let me know your thoughts on this.

**Comment by Icarus-Xu** [comment]
Hey @zyrouge 

Thanks for your reply. I was expecting like, categorize musics according to "album artist", like the "Alan Walker" field in the last screenshot, and show multiple artists in music details.

Best
Icarus

**Comment by zyrouge** [comment]
> Hey @zyrouge
> 
> Thanks for your reply. I was expecting like, categorize musics according to "album artist", like the "Alan Walker" field in the last screenshot, and show multiple artists in music details. I'll look into mediastore sometime to check if that is possible, not quite familiar with that part.
> 
> Best Icarus

Could you toggle the Album Artists page in settings and try that?

**Comment by Icarus-Xu** [comment]
Right, I discovered that after reading source code XD, so that is what I wanted. But, regarding the "artist" page, is that proper to combine multiple artists as one, rather than treating artists seperately?

**Comment by TaleWatcher** [comment]
[Mediastore API doesn't support multiple artists](https://github.com/VinylMusicPlayer/VinylMusicPlayer/pull/345/commits/e3f92f75aee58d5d6fdf4b06fa387015617e5cb8#diff-1bc77aa46dd8248c454046be00350012bc95ed753f2c8cd74fbee54dfbdac17cL200) so it's not really possible to have multiple artists in symphony without post-processing or using a separate id3 extractor.
Also the example file given uses id3v2.3, which to my knowledge, doesn't actually have a way of separating multiple artists, different music players just use their own delimiters. id3v2.4 supports this with null separators but then symphony only shows the first artist so i'm assuming mediastore only gives that.

**Comment by zyrouge** [comment]
> Right, I discovered that after reading source code XD, so that is what I wanted. But, regarding the "artist" page, is that proper to combine multiple artists as one, rather than treating artists seperately? I mean, like this alan walker case, I thought it would be easier to understand to add this song to 3 seperate artists, rather than connecting their name into one.

I'm not sure either. Seperating artist does sound appropriate. Maybe implementing an option to optionally seperate artists would work. This might need further discussion.

**Comment by Icarus-Xu** [comment]
> Maybe implementing an option to optionally seperate artists would work

Yes, that was my suggestion, but after some time I realized that the format to split artist is not defined like some kind of "standard" so splitting requires some fine tune, e.g. "Alan/Walker", "Alan;Walker", "Alan&Walker" could all represents some sort of cooperated artists, the format is upon to the preference of software / person that wrote the metadata.
