### ISSUE TITLE
[Bug] App doesn't recognise multiple artists in Vorbis comments

### ISSUE THREAD

**Issue by RustoMCSpit** [zyrouge/symphony#293]
unlike id3, opus files (using vorbis comments) can have multiple artist tags. this isnt interpeted by the app

**Comment by RustoMCSpit** [comment]
https://github.com/zyrouge/symphony/issues/93
related but this is for opus files

**Comment by RustoMCSpit** [comment]
why's it blocked?

**Comment by zyrouge** [comment]
> why's it blocked?

There is no viable solution as of now.

**Comment by RustoMCSpit** [comment]
> > why's it blocked?
> 
> There is no viable solution as of now.

is there one now?

**Comment by zyrouge** [comment]
> > > why's it blocked?
> > 
> > 
> > There is no viable solution as of now.
> 
> is there one now?

#417 can fix this.

**Comment by zyrouge** [comment]
Closing as #567 has been merged.
