### ISSUE TITLE
[Bug] App re-scans music library every time you open it

### ISSUE THREAD

**Issue by RustoMCSpit** [zyrouge/symphony#294]
shpuld be a manual process or work like auxio

**Comment by RustoMCSpit** [comment]
can we have a pre-release with this fix, without it the app is unusable for me

**Comment by zyrouge** [comment]
> can we have a pre-release with this fix, without it the app is unusable for me

I'll probably try making a release in a day or two. There are some critical issues that are needed to be fixed.
