### ISSUE TITLE
Duplicated songs every rescan

### ISSUE THREAD

**Issue by RustoMCSpit** [zyrouge/symphony#299]
![Screenshot_20231023-204114](https://github.com/zyrouge/symphony/assets/134429563/65910ed4-400c-47d9-895b-f708d917ea02)

**Comment by zyrouge** [comment]
This is probably MediaStore being bugged. Could you try restarting your phone?

**Comment by RustoMCSpit** [comment]
i reloaded and it went back to one but i think it is duplicating every time i open the app for a rescan

**Comment by RustoMCSpit** [comment]
> > i reloaded and it went back to one but i think it is duplicating every time i open the app for a rescan
> 
> Which version are you on?
latest

**Comment by zyrouge** [comment]
Is this still relevant?

**Comment by RustoMCSpit** [comment]
havent noticed, it might be though

**Comment by zyrouge** [comment]
> havent noticed, it might be though

You can always open a new issue if you face this again. Closing this since it's not relevant.
