### ISSUE TITLE
[Bug] Extended controls within notification bar

### ISSUE THREAD

**Issue by timothykumm** [zyrouge/symphony#30]
Currently you can only skip songs by opening the App but it would be good if we could do it from the notification bar.

**Comment by zyrouge** [comment]
![Screenshot_2023-02-20-06-33-37-826_com brave browser](https://user-images.githubusercontent.com/50770114/219987292-0182ae95-7cd5-4049-9fb3-bb90c4c48081.png)

Could you post a screenshot of your notification?

**Comment by timothykumm** [comment]
![Screenshot_20230220-095604~2](https://user-images.githubusercontent.com/27158937/220072958-b5fdccb9-e907-47ce-b1d0-5575ff27ba1c.png)

**Comment by zyrouge** [comment]
Aight I'll look into it.

**Comment by zyrouge** [comment]
Does this still occur after v2023.2.68?

**Comment by timothykumm** [comment]
> Does this still occur after v2023.2.68?

Yes. Nothing changed.

**Comment by zyrouge** [comment]
Fixed as of v2023.2.69.
