### ISSUE TITLE
[Bug] Incorrect or duplicate Thumbnails 

### ISSUE THREAD

**Issue by Heus-Sueh** [zyrouge/symphony#303]
### Description

My songs have wrong/changed thumbnails, this bug has been present for a while, but I always forgot to report it, but I finally remembered.

### Wrong Thumbnails:
![Screenshot_20231026-213508_Symphony](https://github.com/zyrouge/symphony/assets/98482469/fa9b5986-db95-45c8-b3d4-8a1fdba30ef0)

### Correct Thumbnails:
![Screenshot_20231026-213540_Namida](https://github.com/zyrouge/symphony/assets/98482469/bb320e8e-d9c4-4669-b14e-0fef29b52b34)

### Steps to Reproduce

I don't know, to be honest.

### Correct Thumbnails:
![Screenshot_20231026-213540_Namida](https://github.com/zyrouge/symphony/assets/98482469/bb320e8e-d9c4-4669-b14e-0fef29b52b34)

### Device

-   Device: Xiamo Mi A2 Lite
-   OS: Android 13

### Additional Context

I have a lot of music and they are stored on the SD card, I don't know if that's a problem, but here's some context.

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
It could be due to the SD card since they tend to be slower. Needs further investigation though. If this is a MediaStore issue, rebooting might fix this.

**Comment by Heus-Sueh** [comment]
> It could be due to the SD card since they tend to be slower. Needs further investigation though. If this is a MediaStore issue, rebooting might fix this. This only fix might be https://github.com/zyrouge/symphony/issues/118.

unfortunately restarting doesn't help, I think using the direct metadata of the songs is the best option or having an option to enable it at least

**Comment by zyrouge** [comment]
Closing this in favour of #118.
