### ISSUE TITLE
[Feature Request] Context-sensitive search

### ISSUE THREAD

**Issue by Currrupted** [zyrouge/symphony#308]
### Description

Searching for music (i.e. albums, files, artists or songs) currently includes all categories by default. When selecting specific tabs and searching for something, the tab selected does not influence this. Users could expect that when they are currently viewing and/or playing ther albums, 

### Solution

It would be great to have the option to make search context dependent, in the way that the current tab defines what to search for initially. In the for "For you" tab, everything is searched by default.

### Alternatives

Alternatively, the way the search results are displayed could respect the current tab or be configured in the settings in more detail.

### Additional Context

I think Spotify definitely handles searching well, especially regarding the separation between the local library and an open catalogue search.

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by Currrupted** [comment]
Thank you for implementing this feature! On the latest nightly, the search now only includes thencurrent category by default. However, when I tried this out the app crashed. Here is a screenshot:

![Screenshot_20231119-093218_Symphony](https://github.com/zyrouge/symphony/assets/13292623/8ab27205-a31e-444e-beb2-6e81480499b8)

**Comment by zyrouge** [comment]
> Thank you for implementing this feature! On the latest nightly, the search now only includes thencurrent category by default. However, when I tried this out the app crashed. Here is a screenshot:
> 
> ![Screenshot_20231119-093218_Symphony](https://user-images.githubusercontent.com/13292623/284045834-8ab27205-a31e-444e-beb2-6e81480499b8.png)

Could you attach a screen record? I don't seem to have that issue.

**Comment by Currrupted** [comment]
I uploaded a recording of the phone I used here: https://upload.nolog.cz/download/4baae246103cf0f5/#GtynK5WobuoDq5uOiUODNQ

I am not so sure anymore that it is related to searching, as it niw appears before I can even go to the search.

**Comment by zyrouge** [comment]
> I uploaded a recording of the phone I used here: https://upload.nolog.cz/download/4baae246103cf0f5/#GtynK5WobuoDq5uOiUODNQ
> 
> I am not so sure anymore that it is related to searching, as it niw appears before I can even go to the search.

Tracked in #344.
