### ISSUE TITLE
[Bug] Corrupted or otherwise faulty tracks cannot be skipped

### ISSUE THREAD

**Issue by Currrupted** [zyrouge/symphony#309]
### Description

On my phone, I have several files/tracks, which for some reason do not work in Symphony. While I cannot find out why, they will reproducibly crash playback when using the app. When Symphony attempts to play them and fails, playback just stops working and has to be restarted (either by manually selecting a new (working) track or shuffling all songs again. Both the "skip" and "back" buttons inside the app do not work, they will not do anything once playing any song fails.

### Steps to Reproduce

1. Go to any song that fails to play
2. wait for some time
3. attempt to skip, play/pause and go back
4. correctly play a working song

### Expected Behavior

Faulty songs should simply be skippable or be skipped automatically, when playing the song cannot be started.

### Screenshots

![signal-2023-10-31-19-05-36-864](https://github.com/zyrouge/symphony/assets/13292623/7e612b4c-3b16-432d-97e5-c27273deab7a)

### Device

-   Device: Sony Xperia XA2 (pioneer)
-   OS: Lineage OS 19.1

### Additional Context

This seems to be related to the files mainly. Using the stock AOSP music player, the respective files cannot be played either, however an error message will be displayed. 

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
Could you attach a faulty file here?

**Comment by Currrupted** [comment]
> Could you attach a faulty file here?

Thanks! I tried downloading a song from YouTube where the download process crashed, the corresponding file leads to the same error. It should be [here](https://upload.nolog.cz/download/f1448fe94cc42c0b/#mgsr036dRbaKc_fRB6RIwg). Unfortunately GitHub does not allow uploading WMA files directly.

**Comment by zyrouge** [comment]
> > Could you attach a faulty file here?
> 
> Thanks! I tried downloading a song from YouTube where the download process crashed, the corresponding file leads to the same error. It should be [here](https://upload.nolog.cz/download/f1448fe94cc42c0b/#mgsr036dRbaKc_fRB6RIwg). Unfortunately GitHub does not allow uploading WMA files directly.

That file seems to play for me just fine. Do you have issues playing it? I should probably try that myself.

**Comment by Currrupted** [comment]
I managed to record the error happening on another phone. I opened Symphony and started by shuffling all of the songs I just added for testing. After skipping several times, I reached a track which causes the error. The app gets stuck and I have to manually select new tracks to resume playing.

https://github.com/zyrouge/symphony/assets/13292623/d6dcb965-d40d-4f7f-b3f7-90a34b8f7847

**Comment by zyrouge** [comment]
Alright I'll look into it.

**Comment by Currrupted** [comment]
> Alright I'll look into it.

Thanks a lot! I uploaded the screengrab [here](https://upload.disroot.org/r/NByzEZWX#UvlGuWNovC7QMNM706yQ7znVKJ7DwXOiZSKlSRV9OLc=), you can download it once.
