### ISSUE TITLE
[Bug] Skipping songs with earbuds not working

### ISSUE THREAD

**Issue by timothykumm** [zyrouge/symphony#31]
With my Galaxy buds pro 2, I can normally skip songs by double tapping the touch panel but it is not working on symphony (pausing songs is possible tho). I also tried another music player aswell as YouTube and there it is working just fine.

**Comment by zyrouge** [comment]
> With my Galaxy buds pro 2, I can normally skip songs by double tapping the touch panel but it is not working on symphony (pausing songs is possible tho). I also tried another music player aswell as YouTube and there it is working just fine.

Could confirm that I totally forgot that.

**Comment by zyrouge** [comment]
Implemented as of v2023.2.68.
