### ISSUE TITLE
[Bug] Queue list and playback options not visible when song information shown

### ISSUE THREAD

**Issue by Currrupted** [zyrouge/symphony#312]
### Description

I have been noticing that the button for the current queue (or song list or playlist) is not always visible, especially for songs with longer titles and audio information. Often, the button in the corner in the bottom left is not always shown completely or not visible entirely. With some songs, this does not occur. When I tried disabling displaying audio information, this does not haplen that much anymore. However, I would like to be able to use both.

### Steps to Reproduce

1. Go to 'Settings' - 'Now Playing'
2. Click on 'Show audio information' or make sure that it is enabled
3. Go back to the main screen and then to the 'Songs' tab
4. Trigger the 'Shuffle' button to start playing all songs
5. Go to the main player interface and try to find the area/button with the song queue
6. See error
7. Go to 'Settings' and disable 'Show audio information'
8. Go back to the main player again and click on the queue

### Expected Behavior

All important/offered options and functionailities in the audio should be usable, regardless of how the song itself is currently displayed. When the audio information is enabled, the queue/list and other buttons should still be accessible and visible. Enabling this option should not displace the bottom options in the player.

### Screenshots

Here are three screenshots which show the issue. Each shows a different track/file being played, with being different in title length and other information. That this does not happen with one song seems to stem from the file not being playable, which results in no audio information being there, that could be displayed.

![signal-2023-11-02-10-05-45-470](https://github.com/zyrouge/symphony/assets/13292623/e9a71793-61df-4ebe-9b74-dd82e73d8aa1)
![signal-2023-11-02-10-04-47-067](https://github.com/zyrouge/symphony/assets/13292623/06ad9b59-a208-4572-a5e2-7bedd687a007)
![signal-2023-11-02-10-03-56-418](https://github.com/zyrouge/symphony/assets/13292623/6c3449a4-7bb8-4fb5-bb65-bb21c099e2b3)

### Device

-   Device: Sony Xperia XA2 (pioneer)
-   OS: LineageOS 19.1 (Android 12L)
-   Version: n.a.

### Additional Context

The way the player (i.e. the interface with its functionalities) is displayed seems to change a lot, it depends entirely on the current file that is being played.

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
Yeah, I did notice this in your previous issue. Seems like the cover tries to fit the width but ends up occupying too much height. Could you try playing around with content scale and text scale in settings?

**Comment by Currrupted** [comment]
Sorry for the delays. I tried it out and was able to show different visibilities of the bottom control bar.
![signal-2023-11-02-10-04-47-067](https://github.com/zyrouge/symphony/assets/13292623/69d28413-841c-478c-b4ab-9cb971e278ca)
![signal-2023-11-02-10-03-56-418](https://github.com/zyrouge/symphony/assets/13292623/2c3eed06-7544-42dd-84bd-3d0c76e4c1de)
![signal-2023-11-02-10-05-45-470](https://github.com/zyrouge/symphony/assets/13292623/ca05a7ae-5f24-442f-83da-97f81478617f)

**Comment by Currrupted** [comment]
Sorry again, here are the different settings for the scale.

**Default settings (Font scale: x1.0, Content scale: x1.0)**
![photo_2023-11-13_16-33-56](https://github.com/zyrouge/symphony/assets/13292623/abc08623-02e4-47a5-b5cd-242b620f6bde)

**Content scale reduced (x0.9):**
![photo_2023-11-13_16-34-07](https://github.com/zyrouge/symphony/assets/13292623/d169a289-4c29-4d07-ab0e-a1bb2f6489f8)

**Font scale reduced (x0.9):**
![photo_2023-11-13_16-34-12](https://github.com/zyrouge/symphony/assets/13292623/7b9d8744-2c14-41b8-a9d4-df3148b2a702)
