### ISSUE TITLE
[Bug] Don't bump versionCode for nightles as F-Droid autoupdate will pick them up

### ISSUE THREAD

**Issue by licaon-kter** [zyrouge/symphony#319]
ref: https://github.com/zyrouge/symphony/blob/v2023.11.6-6d48d7f/app/build.gradle.kts#L15-L16

ref: https://gitlab.com/fdroid/fdroiddata/-/commit/a7069df2fb4e09ea25a57bc1f89db354b0adc4c0

And they'll fail since your upstream APK can't be found: https://github.com/zyrouge/symphony/releases/tag/v2023.11.6-6d48d7f

If you want to have nightles/betas/alphas etc, maybe you can have your tags end up in `-nightly` and F-Droid could avoid those or something?

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/6b316e293c38b16a2e4c4ae94f78639ead149c4f

**Comment by licaon-kter** [comment]
On that thought I've already updated the pattern to exclude non-numbers-only tags: https://gitlab.com/fdroid/fdroiddata/-/commit/23404f7e32de09d322c2e8a8e9dc61b38dcab946

**Comment by zyrouge** [comment]
I did not want nightly to be available on F-droid since they are often really buggy. v2023.11.106 was not meant to be available as stable yet. But yeah, ignoring such tags should be good enough. Thank you!
