### ISSUE TITLE
[Bug] F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [zyrouge/symphony#320]
pulling `esbuild` binaries: https://github.com/zyrouge/symphony/commit/840b7514f1bd5f3bb5cb3b150d502c83bc16e92b#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519R579

I'll look into rebuilding esbuild locally first: https://esbuild.github.io/getting-started/#build-from-source

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/81144d8947a832c546465adaf72eeaa6dc169b09

**Comment by licaon-kter** [comment]
I didn't get a chance to test, I've added scandelete preemtively.

I've guessed it will fail later if esbuild is missing, did I guess wrong and esbuild is not actually used?

**Comment by zyrouge** [comment]
> I didn't get a chance to test, I've added scandelete preemptively, but also disabled it in case the next cycle starts in the mean time.
> 
> I've guessed it will fail later if `esbuild` is missing, did I guess wrong and `esbuild` is not actually used?

esbuild is required for `prebuild` command. It is not required for building the actual app.

**Comment by licaon-kter** [comment]
> esbuild is required for prebuild command. 

Please explain? How it is used?

**Comment by zyrouge** [comment]
> > esbuild is required for prebuild command.
> 
> Please explain then how/when it is used?
> 
> /LE: it builds fine and repro with those two scandelete lines, but we need to know which role esbuild plays during the whole build process.

Scripts in [`cli`](https://github.com/zyrouge/symphony/tree/main/cli) folder use Typescript and they are [invoked](https://github.com/zyrouge/symphony/blob/main/package.json#L6-L16) using [tsx](https://www.npmjs.com/package/tsx). It depends on [esbuild](https://www.npmjs.com/package/tsx) under the hood.

**Comment by licaon-kter** [comment]
Ok, so we need to run npm install, delete prebuilds esbuild, rebuild esbuild, then run the other steps I guess.

**Comment by zyrouge** [comment]
> Ok, so we need to run npm install, delete prebuilds esbuild, rebuild esbuild, then run the other steps I guess.

Pretty much that's the solution if we don't want prebuilt binaries. But where exactly is it documented? The binary should more or less be the same if it's installed via `npm` or locally built.

**Comment by licaon-kter** [comment]
https://f-droid.org/en/docs/Inclusion_Policy/

> Binary dependencies such as JAR files have to be built from source or installed from Debian repos.
> Though we tried to build everything from source, we still need some prebuild binaries. Therefore we have some exceptions:
> ...

**Comment by licaon-kter** [comment]
Ummm
```
    prebuild:
      - rm ../node_modules/@esbuild/linux-x64/bin/esbuild
      - rm ../node_modules/esbuild/bin/esbuild
      - npm run prebuild
```
...so it is not used in `npm run prebuild` ?

**Comment by zyrouge** [comment]
> Ummm this builds fine too:
> 
> ```
>     prebuild:
>       - rm ../node_modules/@esbuild/linux-x64/bin/esbuild
>       - rm ../node_modules/esbuild/bin/esbuild
>       - npm run prebuild
> ```
> 
> ...so it is not used in `npm run prebuild` ?

That's because `prebuild` does not invoke any local scripts in `./cli`. Thus, `tsx` is never used.

**Comment by zyrouge** [comment]
I guess you can go ahead and ignore building `esbuild` locally, at least temporarily it is not being used.

**Comment by zyrouge** [comment]
Closing this since 106 is out on F-droid.
