### ISSUE TITLE
[Bug] App freezes in folder view

### ISSUE THREAD

**Issue by eleius** [zyrouge/symphony#322]
### Description

I've been using v2023.8.105 from F-Droid without issues on my main phone (Android 13), but today after updating to v2023.11.106 I can't use it anymore, so I had to revert to the previous version. I'm using the "folder" view -- as soon as I "tap" a folder, the app freezes and after a while Android asks me if I want to kill it. I've already tried re-scanning, clearing the app cache, uninstalling & reinstalling it.

### Steps to Reproduce

1. Launch app and configure it to show the folders button
2. Tap any folder
3. It should freeze (no error shown)

### Device

-   Device: Xiaomi 11 Lite 5G NE
-   OS: LineageOS (Android 13) + GApps

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
Seems like I can enter folders just fine but crashes when I try to exit the folder. I'll have to investigate this.

**Comment by eleius** [comment]
I forgot to mention, I can tap storage > emulated > 0 > Music, it only freezes when I tap any folder inside "Music".

**Comment by zyrouge** [comment]
> I forgot to mention, I can tap storage > emulated > 0 > Music, it only freezes when I tap any folder inside "Music".

Is it possible to get logs of what's happening? It might be helpful in identifying what's happening for you.

**Comment by Joshaby** [comment]
This problem is also happening to me, as I search for songs in folders, I am unable to use the app

**Comment by Joshaby** [comment]
@zyrouge ![Screenshot_20231110_004856_Symphony.jpg](https://github.com/zyrouge/symphony/assets/56325844/9aa8e5d9-b305-45c0-beae-a273a100c2c1)

**Comment by Joshaby** [comment]
I took a screenshot of the log, but it's not complete, I don't know if this alone can help you

**Comment by Joshaby** [comment]
![Screenshot_20231110_005648_Symphony.jpg](https://github.com/zyrouge/symphony/assets/56325844/c689b3ae-1c3f-4b64-99a9-77fd649e5d53)

**Comment by zyrouge** [comment]
Oh now I get it. It's an issue with Android Compose. It should be fixed when https://github.com/zyrouge/symphony/pull/305 is merged.

**Comment by gourdcaptain** [comment]
This is happening for me too when I click on any folder in Music.

**Comment by Currrupted** [comment]
> This is happening for me too when I click on any folder in Music.

For me too! Also, when I start the app and immediately play any track (while the library is still being scanned), the app often behaves in a similar manner.

**Comment by zyrouge** [comment]
> > This is happening for me too when I click on any folder in Music.
> 
> For me too! Also, when I start the app and immediately play any track (while the library is still being scanned), the app often behaves in a similar manner.

For some reason most of the Compose versions are having this issue. They have fixed this upstream but it has been released. Not sure why there taking so long.
