### ISSUE TITLE
[Bug] Missing songs

### ISSUE THREAD

**Issue by SunBreaker1** [zyrouge/symphony#334]
### Description

I recently updated the app and now I'm seeing around 20 less songs in my app, as well as unable to go through the file browsing folder structure without the app hanging and giving a android "App has stopped working". Rescaning didn't help.

Strangely enough, some of my other song apps are also showing less songs than normal.

I'll have to double check and verify on my computer that no songs were deleted unintentionally.

### Steps to Reproduce

No real steps to reproduce, just update and check aonglist and browse folder structure in app

### Expected Behavior

Number os songs should match the initial amount before and after.

Folder structure should also allow browsing through the folder structure without crashing 

### Screenshots

![Screenshot_20231114_101401_Symphony.jpg](https://github.com/zyrouge/symphony/assets/85519676/6b776289-14a3-4c0a-8821-1c0bda067a31)

Happens when I try to open folders in the folder browser

### Device

-   Device: Samsung 23+
-   OS: One Ui 5.1
-   Version [e.g. 2023.11.106]

### Additional Context

May be a phone problem, but I know for sure I didn't delete any music and the app is showing 20 less songs

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
Folder view crashing is tracked at #322. For the missing songs, I'm not sure if anyone has reported it nor do I have that issue.

**Comment by SunBreaker1** [comment]
> Folder view crashing is tracked at #322. For the missing songs, I'm not sure if anyone has reported it nor do I have that issue.

I checked my music folders and the songs are listed in the storage, however, they aren't appearing in the app. It's possible that my recent phone update has changed things and made it so that the app doesn't display certain songs.

**Comment by SunBreaker1** [comment]
Upon deeper investigation, I gave found at least one case of a folder containing an album has had its music files deleted but not the album jpg.

**Comment by zyrouge** [comment]
As far as I know, nothing related to scanning songs has been changed in the recent release. Check if they're blacklisted.

**Comment by SunBreaker1** [comment]
> As far as I know, nothing related to scanning songs has been changed in the recent release. Check if they're blacklisted.

Nothing blacklisted, it seems that songs inside several folder have been deleted, how or for what reason I truly don't know, I guess I'll have to re-import my backup

**Comment by zyrouge** [comment]
> > As far as I know, nothing related to scanning songs has been changed in the recent release. Check if they're blacklisted.
> 
> Nothing blacklisted, it seems that songs inside several folder have been deleted, how or for what reason I truly don't know, I guess I'll have to re-import my backup

Is this issue relevant anymore?
