### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Shivamhobbyist** [zyrouge/symphony#335]
### Description

Idk wht is thiss

### Steps to Reproduce

Maybe random

### Screenshots

![Screenshot_20231115_164321_Symphony.png](https://github.com/zyrouge/symphony/assets/78287172/39306697-810b-4776-9cd4-0e039caace09)

### Device

-   Device: [Galaxy a34 5g]
-   OS: [Android 14 One UI 6]
-   Version [e.g. 2023.11.106]

**Comment by Currrupted** [comment]
It is probably related to #322

**Comment by zyrouge** [comment]
> It is probably related to #322

It is probably not. Let me know if it occurs often and when. Cannot fix them without steps to reproduce this issue.
