### ISSUE TITLE
[Bug] Wrong song in notification

### ISSUE THREAD

**Issue by DragoniteChamp** [zyrouge/symphony#336]
### Description

When playing a song, the playback notification displays the wrong track.

### Steps to Reproduce

1. Play a track.
2. View notification center.

### Expected Behavior

The correct track will be displayed.

### Screenshots

https://github.com/zyrouge/symphony/assets/76917579/e16cb0da-5d1e-4683-9985-cea596f196e9

### Device

-   Device: Google Pixel 7 Pro
-   OS: Android 14
-   Version Security Update 10.5.2023

### Checklist

-   [X] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by Currrupted** [comment]
This hasbeen happening for me too. Sometimes the notification will simply freeze outright, or even become hidden.

**Comment by zyrouge** [comment]
> This has been happening for me too. Sometimes the notification will simply freeze outright, or even become hidden.

Notification being hidden has been fixed. Maybe try the recent nightly version?

**Comment by zyrouge** [comment]
Closing this as stale. Kindly re-open this if this still occurs.
