### ISSUE TITLE
[Feature Request] 能否考虑接入navidrome

### ISSUE THREAD

**Issue by Ghd-0802** [zyrouge/symphony#343]
navidrome一直没有一款美观的播放器,希望能有一个国产的播放器支持

**Comment by zyrouge** [comment]
I had to use translator to understand what you said. I hope you meant support for navidrome ("navidrome has never had a beautiful player. I hope there will be a domestic player to support it."). We do not have plans to support anything other sources except local playback. This would be out of scope for this project. Sorry. Closing this as it's beyond the scope.
