### ISSUE TITLE
[Bug] F-droid reproducible build failed

### ISSUE THREAD

**Issue by linsui** [zyrouge/symphony#348]
[diff.zip](https://github.com/zyrouge/symphony/files/13466238/diff.zip)

This seems to be caused by kotlin. See https://github.com/anilbeesetti/nextplayer/issues/739.

**Comment by linsui** [comment]
Please update Compose Compiler to 1.5.6 which should fix the problem. See https://gitlab.com/fdroid/fdroiddata/-/issues/3138

**Comment by zyrouge** [comment]
Closing this since build passed.
