### ISSUE TITLE
Accurately changing the pitch and speed 

### ISSUE THREAD

**Issue by b1owulf** [zyrouge/symphony#352]
### Description

I noticed that the app has an option to change the pitch and speed of the audio, however of the available options only 0.5x, 1.0x, 2.0x and 3.0x.

### Solution

Make it so that the pitch and speed can be changed more accurately

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
This is already being tracked at #111. Closing this as duplicate.
