### ISSUE TITLE
[Feature Request] when importing a new album, import by track number

### ISSUE THREAD

**Issue by RustoMCSpit** [zyrouge/symphony#356]
makes the 'sort by date added' part much cleaner

**Comment by zyrouge** [comment]
What do you mean by "import by track number"? If you mean scan using a track's track number metadata, it is not possible. Scanning is done in the order, fetch all music files -> read metadata -> store it in cache. It is impossible to "scan" that way. You could create a new issue with more information if that's not what you meant.
