### ISSUE TITLE
[Bug]  When song name or artist name long, bottom bar couldn't be displayed

### ISSUE THREAD

**Issue by asandikci** [zyrouge/symphony#365]
### Description

When song name or artist name long, bottom bar couldn't be displayed

### Steps to Reproduce

1. Open any song/music with long name/artist
2. Couldn't scroll down to see bottom bar (see screenshots below)

### Expected Behavior

Either:
1. App should fit all song name / artist name / thumbnail photo / bottom bar to fixed size in screen (Could be implemented with limiting song name / artist name or resizing thumbnail name)
2. App should be scrollable if content is not fit 

### Screenshots
No Problem<br>
<img src="https://github.com/zyrouge/symphony/assets/94538585/041a1bb2-26c8-4bbd-aeb5-5d5ca848c60a" width="300">

<br><br>
Problem Examples<br>
<img src="https://github.com/zyrouge/symphony/assets/94538585/0aaa81d3-0f98-4d23-9be8-1bc49ea871dc" width="300">  <img src="https://github.com/zyrouge/symphony/assets/94538585/44c24a2b-e5a5-463d-b4e0-a7791d53b379" width="300">

### Device

-  Device: Samsung J7Prime2 (SM-G611F)
-  OS: Android 9
-  Version: v2023.11.107

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
This has been fixed in the latest nightly build. The issue was tracked in #312.

**Comment by asandikci** [comment]
I didn't realize that, sorry. Thanks for fix and quick reply.
