### ISSUE TITLE
[Bug] Audio thumbnails quality drop

### ISSUE THREAD

**Issue by Banh7** [zyrouge/symphony#367]
Idk why only Symphony behave like that, others don't 

![Screenshot_2023-12-17-09-46-12-22_c328a126cb0fb561391a2f6f61559b68.jpg](https://github.com/zyrouge/symphony/assets/94868053/7ca691dd-afe5-4caa-9972-2d22a93cee2a)

![Screenshot_2023-12-17-09-46-05-01_01c085aa929b1599fddd4ea6d6812c2d.jpg](https://github.com/zyrouge/symphony/assets/94868053/42e0c6cc-5fa8-4178-bb8d-66f778a6121c)

I usually use Seal (by Junkfood) to download music
-   Version: 2023.11.107

**Comment by Banh7** [comment]
It doesn't have any effect on music, but it looks pretty annoying.

**Comment by zyrouge** [comment]
This may or may not be fixed. Let me know if this still occurs in the next version.

**Comment by Banh7** [comment]
I'm using v2023.12.108-nightly+ebea9d4 but it still occur
I think it because yt-dl --embed-thumbnail 

https://www.reddit.com/r/youtubedl/comments/no6jff/youtubedl_embedthumbnail_bad_image_quality/

But some how only Symphony is affected. I tried every setting on Seal, YTDLnis but it make no progress...

**Comment by zyrouge** [comment]
> I'm using v2023.12.108-nightly+ebea9d4 but it still occur I think it because yt-dl --embed-thumbnail
> 
> https://www.reddit.com/r/youtubedl/comments/no6jff/youtubedl_embedthumbnail_bad_image_quality/
> 
> But some how only Symphony is affected. I tried every setting on Seal, YTDLnis but it make no progress...

Could you name some FOSS apps which are not affected by this? Since Symphony uses thumbnails that are cached by your system, it is possible that those cached images by itself are of bad quality.

**Comment by Banh7** [comment]
Only VLC looks fine, but the quality of some images is still low, probably because --embed thumbnail were 1280 × 720 and the app crop the photo square, so its quality dropped.
![IMG_20240102_102525.jpg](https://github.com/zyrouge/symphony/assets/94868053/0a6e34ec-c0fb-4098-ad09-7c1143be4b27)

**Comment by zyrouge** [comment]
> Only VLC looks fine, but the quality of some images is still low, probably because --embed thumbnail were 1280 × 720 and the app crop the photo square, so its quality dropped. ![IMG_20240102_105019.jpg](https://private-user-images.githubusercontent.com/94868053/293624018-987c37d9-b943-49ef-9127-5c3ab2d67119.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNjg5MzMsIm5iZiI6MTcwNDE2ODYzMywicGF0aCI6Ii85NDg2ODA1My8yOTM2MjQwMTgtOTg3YzM3ZDktYjk0My00OWVmLTkxMjctNWMzYWIyZDY3MTE5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDA0MTAzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2MDZjYjAwNDFjODIxMzdiOWFjNmJlZjJjMjgwODM1NDM0NzkyOWRlOWJmMzg2NTUyNjAwMWM1NzkwOThkZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7JA1ms39JnsdC4ZVGN8SQoSTIy2bCPIV-Ai0SSLG85o)

#118 *might* fix this issue.

**Comment by zyrouge** [comment]
Closing this as the related issue has been fixed.
