### ISSUE TITLE
[Bug] After the end of the album, when you play video/music content on any app Symphony will play instead

### ISSUE THREAD

**Issue by th1nhhdk** [zyrouge/symphony#368]
### Description

After the end of a album Symphony will go back to the start, if you play a YouTube/Facebook video or play a song in Spotify, Symphony will play instead

### Steps to Reproduce

1. Go to the final song of any album and skip to the end
2. Go to any app that have video/music content (YouTube/Facebook/Spotify)
3. Press play
4. Symphony will play the first song of the album, causing the current video/music to pause

### Expected Behavior

Symphony does nothing

### Screenshots

none

### Device

-   Device: Sony Xperia 1 II
-   OS: LineageOS 20/Android 13
-   Version: 2023-07-27

### Additional Context

It happened in Symphony v2023.12.108-nightly+0e30f90

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by th1nhhdk** [comment]
Still happens in v2023.12.108-nightly+a7fbeed

**Comment by zyrouge** [comment]
> ### Description
> After the end of a album Symphony will go back to the start, if you play a YouTube/Facebook video or play a song in Spotify, Symphony will play instead
> 
> ### Steps to Reproduce
> 1. Go to the final song of any album and skip to the end
> 2. Go to any app that have video/music content (YouTube/Facebook/Spotify)
> 3. Press play
> 4. Symphony will play the first song of the album, causing the current video/music to pause
> 
> ### Expected Behavior
> Symphony does nothing
> 
> ### Screenshots
> none
> 
> ### Device
> * Device: Sony Xperia 1 II
> * OS: LineageOS 20/Android 13
> * Version: 2023-07-27
> 
> ### Additional Context
> It happened in Symphony v2023.12.108-nightly+0e30f90
> 
> ### Checklist
> * [x]  I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

Could you attach a video clip?

**Comment by th1nhhdk** [comment]
also, in the video although I set it to display via the track numbers, when you press the play button on the album cover it will still play alphabetically

**Comment by zyrouge** [comment]
> also, in the video although I set symphony to sort songs via the track numbers, when you press the play button on the album cover it will still play songs alphabetically, should I open a bug report or is this intended?

You can go ahead and open an issue.

**Comment by th1nhhdk** [comment]
> You can go ahead and open an issue.

See #371
