### ISSUE TITLE
[Bug] Now Playing bottom controls are squashed in small resolution

### ISSUE THREAD

**Issue by Minkiu** [zyrouge/symphony#372]
### Description
The controls at the bottom of the "Now Playing" view seems to be squashed down, and sometimes they do not show up, this is probably due to the smaller screen/resolution.

### Steps to Reproduce

1. Play any song
2. Click on the "Now Playing" widget at the bottom
3. See error (below)

### Expected Behavior

I would expect seeing all controls in a "normal" size.

### Screenshots

![image](https://github.com/zyrouge/symphony/assets/1800151/15043da3-9bc1-4225-bf57-292a16088066)

Compare it with the repo screenshots:

### Device

-   Device: Sony XZ1 Compact
-   OS: Android 9
-   Version  2023.11.107

**Comment by zyrouge** [comment]
Already has been fixed in nightly.
