### ISSUE TITLE
[Bug] Crash - NullPointerException

### ISSUE THREAD

**Issue by MrXBear** [zyrouge/symphony#374]
### Description

There is music file which I have deleted months ago.
I install symphony app today.
But I see that deleted-music in Albums Tab.
I try Re-scan but it still appear.
I click the 'play button' try to play it.
But the app crash.

![Screenshot](https://github.com/zyrouge/symphony/assets/47053993/e4724c45-22b1-41a5-a51e-27a6955f1812)

![Albums](https://github.com/zyrouge/symphony/assets/47053993/77bfa776-642c-4d3b-a747-82cc79b49e6f)

### Steps to Reproduce

1. Go to 'Albums'
2. Click on 'play button'
3. See error

### Expected Behavior

Show toast: The file doesn't exist. 

### Device

-   Device: Redmi
-   OS: Android 12
-   Version symphony v2023.11.107

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
Does the song show up in songs tab?

**Comment by MrXBear** [comment]
> Does the song show up in songs tab?

Yes, it does.

I click it in songs tab, 
app jump over this file directly, and play the next one (which do exist)

**Comment by zyrouge** [comment]
> > Does the song show up in songs tab?
> 
> Yes, it does.
> 
> I click it in songs tab, app jump over this file directly, and play the next one (which do exist)

The app does not cache anything. The only possibility is MediaStore not detecting this deletion. This should be partially when #93 is resolved. That said, could you try restarting your phone. This might fix this issue.
