### ISSUE TITLE
[Feature Request] Lock the size of control panel in notification

### ISSUE THREAD

**Issue by MrXBear** [zyrouge/symphony#375]
### Description

The size of control panel in notification is random.
Sometime it's large square,
sometime it's small rectangle.

### Alternatives

There is a switch or option to set the size of control panel in 'Settings'.

### Additional Context

![IMG_20231222_141342](https://github.com/zyrouge/symphony/assets/47053993/13efe765-3562-4db7-aa39-fa7047134ce6)

![IMG_20231222_141435](https://github.com/zyrouge/symphony/assets/47053993/e617c886-15e8-4ada-949b-15a896a3b4cd)

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
I test on MIUI 14 and I never have this issue. This might be an issue of older MIUI.

**Comment by zyrouge** [comment]
Seems like this issue does not affect any one. Closing this since there is no fix/workaround.
