### ISSUE TITLE
[Bug] Mini-player marquee high GPU usage

### ISSUE THREAD

**Issue by owosoup** [zyrouge/symphony#379]
### Description

When a song is played, the name shows up, and if it's too long, it scrolls automatically like any other audio app. This makes the GPU of my phone constantly render new frames for this at a high rate, and consumes a lot of battery. When in the background, the app consumes way less. 

### Steps to Reproduce

1. Play a song with a relatively long name
2. Name scrolling happens (for song name and also artist!)

### Expected Behavior

An option to disable titles altogether in the small integrated player to just show the album cover, since I can just open the full screen player if I want to see the name of the song or artist.

### Screenshots

![IMG_20231228_130734](https://github.com/zyrouge/symphony/assets/95828007/f06f5e67-d41c-4aba-afbb-018f3568521b)

### Device

-   Device: realme 9
-   OS: realms ui 4.0, android 13
-   Version 2023.11.106

### Checklist

-   [√] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
Hiding the text might be ugly. What if the title was truncated like "Really long title..."? This solves this issue too.

**Comment by owosoup** [comment]
yeah, that could be great! thanks for the fast answer.
