### ISSUE TITLE
[Bug] When click at "Re-scan" button too quickly causes app crash

### ISSUE THREAD

**Issue by LokKol17** [zyrouge/symphony#384]
### Description

When click at "Re-scan" button too quickly causes app crash

### Steps to Reproduce

1. Open the app
2. Click on the "More" button ( 3 dots )
3. Keep clicking the button "Re-scan" quickly
4. See error (may be thrown an exception or just app crash)

### Expected Behavior

App should not crash

### Screenshots

![Screenshot_20231229-114655_Symphony](https://github.com/zyrouge/symphony/assets/76881681/c7603187-bdb9-4e80-b910-d224efccac9d)

### Device

-   Device: Samsung A20s
-   OS: Android 11
-   Version 2023.08.105

### Checklist

-   [X] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
Can you check if it occurs in the nightly version? I'm pretty sure the dropdown will close once you tap re-scan.

**Comment by LokKol17** [comment]
It works, after install v2023.11.107, the dropdown menu closes and don't allow me click quickly!
