### ISSUE TITLE
[Bug] FLAC Track and Disc number switched

### ISSUE THREAD

**Issue by dezponia** [zyrouge/symphony#387]
### Description

FLAC Track and Disc number are switched in the "details" view. The values are otherwise correct so most likely its just variables being switched?

### Steps to Reproduce

1. Go to a FLAC track with track and disc tags that displays as track 1001+ in the track list.
2. Click on the "..." next to the track.
3. Click on "Details".
4. Notice how "Disc number" and "Track number" are switched.

### Expected Behavior

If the tag is 1004 then track number should be 4 and disc number should be 1.

### Screenshots

Album view with track numbers being 1001+
![01 Symphony FLAC Track and Disc number switched](https://github.com/zyrouge/symphony/assets/150628177/990d6d98-4e9f-468d-814a-315a69ef881c)
Details for track 1004 show disc and track numbers are switched.
![02 Symphony FLAC Track and Disc number switched](https://github.com/zyrouge/symphony/assets/150628177/fe2a8ca1-db51-4bef-8268-185cee5e8cd0)

### Device

-   Device: Fairphone 5
-   OS: Android 13 
-   Version: Symphony v2023.12.108

### Additional Context

I haven't checked but I suspect the behavior is the same for any file using the Vorbis tag format.
Probably related to this change?
https://github.com/zyrouge/symphony/commit/c1b01f42cfeaada6e1c8c026b151594c891b3e9e

Additional issue that is probably related but maybe should get its own bug ticket: FLAC files that DON'T have a Disc Number tagged just get "?" as in their track number when viewing an album.

### Checklist

-   [Y] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
I messed up, my bad.
