### ISSUE TITLE
[ Button alignment]

### ISSUE THREAD

**Issue by Shivamhobbyist** [zyrouge/symphony#388]
Plz add a toggle to switch navigation button (◀️ ⏸️ ▶️) on right side and don't make app edge to edge nowadays smartphone became longer and wider so its slightly hard to navigate with right hand and most of people are right handed

![Screenshot_20231231_095002_Symphony.png](https://github.com/zyrouge/symphony/assets/78287172/7797ffa1-2980-40b9-8a10-ba0c8e4e94df)

**Comment by zyrouge** [comment]
This already exists (Settings -> Now Playing -> Controls layout -> Traditional). Closing this. Already what do you mean by edge to edge here?
