### ISSUE TITLE
[Bug] Incorrect song displayed in notification

### ISSUE THREAD

**Issue by CubeOfCheese** [zyrouge/symphony#393]
### Steps to Reproduce

1. Play a song "songA"
2. Close Symphony
3. Open Symphony
4. Play a different song "songB"
5. Open notifications 
6. See songA album art and title in control panel notification instead of the currently playing songB

### Expected Behavior

The control panel notification should display the current track being played at all times

### Device

-   Device: Samsung Galaxy S22
-   OS: Android 13
-   Version 2023.11.106

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
I cannot seem to reproduce this issue. I'll keep this open since multiple people seems to experience this.

**Comment by zyrouge** [comment]
Closing this as stale. Feel free to re-open.

**Comment by CubeOfCheese** [comment]
I am still experiencing this on v2024.11.114

**Comment by zyrouge** [comment]
> I am still experiencing this on v2024.11.114

Does the app have notifications permission? You could check using the nightly version as well.

**Comment by CubeOfCheese** [comment]
Ohh. Yeah that must be the issue. It's working for me now. I originally blocked the notifications permission because I didn't realize the media player was technically a notification.

Thanks!
