### ISSUE TITLE
[Bug] Some album songs aren't showed

### ISSUE THREAD

**Issue by AttentionGrabber** [zyrouge/symphony#395]
### Description

I think there is a problem with processing so some albums are shown as unknown (below screenshots)

### Expected Behavior

It should show my album songs correctly 

### Screenshots

Symphony:

![Screenshot_20240101-165726](https://github.com/zyrouge/symphony/assets/150506323/fe3c2115-ee55-4904-a76e-7f9082a28171)

Other app:

![Screenshot_20240101-165741](https://github.com/zyrouge/symphony/assets/150506323/76f5dd02-a5a8-4b93-9f33-0b43544ba712)

### Device

-   Device: [e.g. Google Pixel 7 pro]
-   OS: [e.g. Android 14]
-   Version [e.g. 2023.12.108]

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
Could you send that song here?

**Comment by AttentionGrabber** [comment]
> Could you send that song here?

Sure.

[The Neighbourhood - Unfair.flac.zip](https://github.com/zyrouge/symphony/files/13804736/The.Neighbourhood.-.Unfair.flac.zip)
