### ISSUE TITLE
now playing screen and minimized player doesn't limit strings on the title of the song

### ISSUE THREAD

**Issue by k3rnelPan1c228** [zyrouge/symphony#4]
minimized player displays the whole title of the song even if it would even cover the entire screen if the title is big enough and it completely breaks the player in full screen

screenshots:
[minimized player](https://drive.google.com/file/d/1ZaBChGD3_P3VfU7lPBn-UkzKIjX2mmHD/view?usp=drivesdk)

[Full player](https://drive.google.com/file/d/1ZX3tJLgn6zBD6TWu-6J4zj4oSdsxdudu/view?usp=drivesdk)

**Comment by zyrouge** [comment]
Pretty rare case, but I'll implement a fix.

**Comment by zyrouge** [comment]
Implemented as of [v2022.11.31](https://github.com/zyrouge/symphony/releases/tag/untagged-fa63c224af245e14d157).
