### ISSUE TITLE
[Feature Request] Ability to view all artists

### ISSUE THREAD

**Issue by Switch123456789** [zyrouge/symphony#40]
When showing tags of audio-files with multiple artist-entries, only one gets shown. I noticed this across several file-formats.

**Comment by zyrouge** [comment]
> When showing tags of audio-files with multiple artist-entries, only one gets shown. I noticed this across several file-formats.

This is handled by the MediaStore API baked into Android. This is also occur with other player which use the built-in APIs. As far as I know, there is no way to bypass this. I'll be closing this since this is something I cannot fix. Let me know if you have other questions.

**Comment by Switch123456789** [comment]
I know that [Auxio](https://github.com/OxygenCobalt/Auxio) is also using the MediaStore API (at least partially) but it is showing all tags. Maybe you can make use of whatever they did to archive this. I like Symphony but it is unusable with tons of missing artists in the library.

**Comment by zyrouge** [comment]
> I know that [Auxio](https://github.com/OxygenCobalt/Auxio) is also using the MediaStore API (at least partially) but it is showing all tags. Maybe you can make use of whatever they did to archive this. I like Symphony but it is unusable with tons of missing artists in the library.

Are all songs displayed under the songs list with correct artist? Could you attach screenshots of it?

**Comment by Switch123456789** [comment]
Sure, here is a comparison:
Symphony:
![Screenshot_20230222-085054_Auxio](https://user-images.githubusercontent.com/25269380/220557392-4815ab21-0b2e-4255-8f16-1a92b5cfd208.png)
Auxio:
![Screenshot_20230222-085115_Trebuchet_1](https://user-images.githubusercontent.com/25269380/220557357-da91315b-2fc4-4eb0-b473-c9fa966eab60.png)

**Comment by zyrouge** [comment]
> Sure, here is a comparison: Symphony: ![Screenshot_20230222-085054_Auxio](https://user-images.githubusercontent.com/25269380/220557392-4815ab21-0b2e-4255-8f16-1a92b5cfd208.png) Auxio: ![Screenshot_20230222-085115_Trebuchet_1](https://user-images.githubusercontent.com/25269380/220557357-da91315b-2fc4-4eb0-b473-c9fa966eab60.png)

That's not really a bug, I'll look into to and probably add a feature where you can view all artists.

**Comment by zyrouge** [comment]
Could you probably attach a song with such metadata? My music library does not seem to have any such issues, might need further investigation.

**Comment by zyrouge** [comment]
I'm pretty sure MediaStore/MediaMetadataRetriever does not parse multiple values in Vorbis comments. This might require custom parsing which is currently not viable. PRs are welcomed.

**Comment by Switch123456789** [comment]
> Could you probably attach a song with such metadata?

Sure! I packed some silent audio-files with diverse audio-formats in [this zip-file](https://github.com/zyrouge/symphony/files/13799228/files.zip).
I created them with tenacity & puddletag, they consist of only 3 artist-tags, as shown in this puddletag-screenshot.
![image](https://github.com/zyrouge/symphony/assets/25269380/ec35ad4f-a808-4ce9-9bae-a3beb7c66fae)

**Comment by zyrouge** [comment]
> > Could you probably attach a song with such metadata?
> 
> Sure! I packed some silent audio-files with diverse audio-formats in [this zip-file](https://github.com/zyrouge/symphony/files/13799228/files.zip). I created them with tenacity & puddletag, they consist of only 3 artist-tags, as shown in this puddletag-screenshot. ![image](https://private-user-images.githubusercontent.com/25269380/293481257-ec35ad4f-a808-4ce9-9bae-a3beb7c66fae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5ODkzMzMsIm5iZiI6MTcwMzk4OTAzMywicGF0aCI6Ii8yNTI2OTM4MC8yOTM0ODEyNTctZWMzNWFkNGYtYTgwOC00Y2U5LTliYWUtYTNiZWI3YzY2ZmFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDAyMTcxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwZDcyYmRmY2JkNjZjOGZlNGM3NGI4ZTE4OTlmMmI4MTFiNjk3ZWU2YmIxOGY5NTA1NmMxYjMxMWQyNDIxYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RlDBNoqhTjFDILQHeNo2Tg3xthr94wg9kh4-L3pWV1U)

Seems like metadata of `.wav` and `.flac` are parsed correctly and delimited with `~`. I guess `.mp3` and `.m4a` used ID3v4 which was not parsed correctly by MediaStore? Anyhow, it seems like I myself have to implement a solution for this which might take some time since I don't know how these tags are embedded.

**Comment by zyrouge** [comment]
This should be fixed along with the implementation of metadata decoder.
