### ISSUE TITLE
[Bug] Track numbers have stopped working after update

### ISSUE THREAD

**Issue by Naul06** [zyrouge/symphony#401]
### Description

Instead of the track numbers showing as usual, there are '?' in their place after the v2023.12.108 update. I downgraded to the previous version and it works fine.

### Steps to Reproduce

1. Have v2023.11.107 installed
2. Update to v2023.12.108
3. Tap to view an album

### Expected Behavior

Track numbers should appear as usual in the track cover's bottom and the album should be sorted by track number.

### Screenshots

[Screenshot](https://github.com/zyrouge/symphony/assets/79797669/c042623c-21aa-4500-b5cc-ea1b3658d19f)

### Device

-   Device: Motorola One
-   OS: Android 10
-   Version: v2023.12.108

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
How was the album number displayed in previous v107?

**Comment by Naul06** [comment]
![Screenshotworking](https://github.com/zyrouge/symphony/assets/79797669/ee6253d8-8e5b-4f03-92c1-56d5ca8e4ac1)

**Comment by Naul06** [comment]
![Screenshotworking](https://github.com/zyrouge/symphony/assets/79797669/43b8779c-bcdd-4062-907e-eef130eedd3e)
