### ISSUE TITLE
[Bug] App crashes when click search button and can't swipe down in setting 

### ISSUE THREAD

**Issue by Banh7** [zyrouge/symphony#402]
### Description

Click on search button make app crash immediately 

https://drive.google.com/file/d/16Bc2D9dokj0g7JLDwONc2TrFwzhoRzZm/view?usp=drivesdk

### Device

-   Device: Oppo A77s
-   OS: Android 13
-   Version: v2024.1.109-nightly+e44b7b6

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
Yes, I'm aware of this, will fix it tomorrow.
