### ISSUE TITLE
[Bug] Track Number sorting is reversed when looking at an Album 

### ISSUE THREAD

**Issue by paulhoea** [zyrouge/symphony#409]
### Description

When going to the Album view sorted by "Custom", upward arrow (descending? - shows most recently added first), and clicking on an album, the tracks in the album are ordered descending, starting with the last track (instead of ascending, starting with the first track, which would be expected).

### Steps to Reproduce

1. Go to the "Albums" tab
2. Click on the sort buttons
3. Sort by "Custom", upward arrow
4. Click on an album

### Expected Behavior
Order of Album tab should not affect order within an album, which should default to either last set value, or to order by Track number, starting with the first.

### Screenshots

-

### Device

-   Device: Samsung Galaxy A52s
-   OS: Android 14
-   Version: Oni UI 6.0, Security Patch 1.12.23

### Additional context

-

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
Do you mean that by default the sorting is in descending instead of ascending?

**Comment by paulhoea** [comment]
It is in the same order within the Album as the Order set on the album tab. If I have the order set as described, this leads to unexpected behaviour (starting with the last track). I would also like to add for reproducibility that the bug only happens once the app is restarted.

**Comment by zyrouge** [comment]
Yup, thank for the info.
