### ISSUE TITLE
[Feature Request] recentrly added: add to sort options and show as albums

### ISSUE THREAD

**Issue by ildar** [zyrouge/symphony#411]
### Description

Recently added music should be easily reacheable: as the sorting option for Albums and Artists.
And also plz show recently added tracks grouped in albums, not separately.

### Solution

Change sorting and the "Recently added" section

### Alternatives

Using the player with restricted Recents is painful.

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
Also, what you are asking in regards to recently added is also pretty confusing. Kindly, create a new issue with exact requirements.

**Comment by ildar** [comment]
Thank you for considering my FRs so fast.

On Tue, Jan 9, 2024 at 5:35 PM Zyrouge wrote:

> And also plz show recently added tracks grouped in albums, not separately.
>
> Recently added *tracks* shouldn't be grouped in *albums*.
>
Recently added shows just tracks of one or two albums I added recently.
That's not optimal. Showing those grouped would allow to extend the number.

> Recently added music should be easily reacheable: as the sorting option
> for Albums and Artists
>
> Albums do not have "added at" attribute, this does not make sense.
> Hypothetically, sorting albums with their recently added tracks is also
> heavy on performance.
>
using the "added at" time of any track in the album sounds really
reasonable. I'm not sure how that would hurt the performance. But looking
at albums in alphabetical order is movetone.

Before creating the new issue: what you think on the above, please?

**Comment by ildar** [comment]
Though I just tried "Custom" sort order and surprisingly it looks very much
like it: recently added.
I wonder what is it really but anyway I'm satisfied already.
Thanks

**Comment by zyrouge** [comment]
> Recently added shows just tracks of one or two albums I added recently.
That's not optimal. Showing those grouped would allow to extend the number.

Again, that's why it is named "Recently added songs" and not "Recently added albums".

> using the "added at" time of any track in the album sounds really
reasonable. I'm not sure how that would hurt the performance. But looking
at albums in alphabetical order is movetone.

Sorting using "added at" might have complexity of `O(n^2)` or greater if considering the algorithm itself. But, anyhow it does sound like a reasonable request.

**Comment by zyrouge** [comment]
> Though I just tried "Custom" sort order and surprisingly it looks very much like it: recently added. I wonder what is it really but anyway I'm satisfied already. Thanks

"Custom" doesn't apply sort. MediaStore returned the result in the order of modified time.
