### ISSUE TITLE
[Bug] Occasional hangs

### ISSUE THREAD

**Issue by ildar** [zyrouge/symphony#412]
### Description

in the middle of navigation

### Device

-   Device: AGM H3
-   OS: LineageOS 20 GSI

### Additional Context

[adb log](https://github.com/zyrouge/symphony/files/13875509/1.txt)

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
Does it occur often? Stack trace seems to indicate something went wrong inside Compose. It should be safe to ignore if this doesn't occur frequently.

**Comment by ildar** [comment]
I'm sorry for inaccurate description. The app doesn't crash but hangs.
Quite often, I'd say. When this happens several times while one discovers
and tunes the app — it leaves bad impression.

**Comment by zyrouge** [comment]
> I'm sorry for inaccurate description. The app doesn't crash but hangs. Quite often, I'd say. When this happens several times while one discovers and tunes the app — it leaves bad impression.

Maybe could you provide information about when it mostly occurs? I had zero crashes in the last few months, so I don't really know what you might be facing.

**Comment by ildar** [comment]
allright. I'll look at it some more then come back to you.
I suspect that it happens if I do something while scan isn't yet finished.
But I need to check that again.

**Comment by zyrouge** [comment]
Closing this as stale.
