### ISSUE TITLE
[Bug] Symphony can't handle sorting albums with more than one disc

### ISSUE THREAD

**Issue by ghost** [zyrouge/symphony#421]
### Description

When sorting by track number in an album's page, tracks of different discs are mixed together

### Steps to Reproduce

1. Go to an album which has more than one disc
2. Sort by track number

### Expected Behavior

Tracks are ordered so all disc 1 tracks are in order of track number followed  all disc 2 tracks also in order of track number.

### Screenshots

![Screenshot](https://github.com/zyrouge/symphony/assets/79797669/e66016e6-fd05-4ff8-9981-2294f9fac34e)

### Device

-   Device: Motorola One
-   OS: Android 10
-   Version v2024.1.109

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
Seems like the metadata does no have disc number or the Metadata reader failed to do it. Usually, if the track number has disc number it will be indicated as `<disc-num><padded track-num>`>. For example, `1001` means disc 1, track 1. What kind of file is that? Metadata of ID3 are parsed correctly.

**Comment by Naul06** [comment]
They are MP3 files, ID3v2.3, both mp3tag and tone recognize the metadata and windows media player shows them correctly.

**Comment by zyrouge** [comment]
> They are MP3 files, ID3v2.3, both mp3tag and tone recognize the metadata and windows media player shows them correctly. Edit: The only thing that stands out is that all of this is shown as disc 1 or disc 2 with the track number being in a separate string.

Is it shown like that in song information dialog?

**Comment by Naul06** [comment]
No, it's shown like that in mp3tag and tone. On Symphony, it's not even mentioned:
![Screenshot_20240116-143554](https://github.com/zyrouge/symphony/assets/79797669/cdba8fc2-d8ba-437b-8909-d6a78eb61973)

**Comment by zyrouge** [comment]
> No, it's shown like that in mp3tag and tone. On Symphony, it's not even mentioned: ![Screenshot_20240116-143554](https://private-user-images.githubusercontent.com/79797669/297141094-cdba8fc2-d8ba-437b-8909-d6a78eb61973.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MjcwOTYsIm5iZiI6MTcwNTQyNjc5NiwicGF0aCI6Ii83OTc5NzY2OS8yOTcxNDEwOTQtY2RiYThmYzItZDhiYS00MzdiLTg5MDktZDZhNzhlYjYxOTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDE3Mzk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzYzk3NGJkN2ZkZDg5NGIzOThkMDA3M2RmZDJlMjRjNDVlNjNiYTQ5NmU3YmVmNTJhZTA1ZWJiNjg0MWVkMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kAVJVsGxECdXmNLoigsYT3XIWBl3tPll48iUh0TG774)

Probably because of MediaStore/MediaMetadataRetriver. It is bad at certain things and this is one out that. It works for some ID3 versions but not on others. Probably, #417 will fix this.
