### ISSUE TITLE
[Feature Request] Sort by album artist in albums view

### ISSUE THREAD

**Issue by bbenne10** [zyrouge/symphony#427]
### Description

I have a relatively large music collection of popular music with multiple artists featured on a song. An example might be "Galleons feat. Garret Rapp" or "Killer Mike feat. Curren$y". I also listen almost exclusively to albums. With the current artist list, it is imppssible for me to "drill down" from artist > album, which seems to me to be most natural.

### Solution

I can see one of two solutions being useful: either prefer sorting on thr "album artist" tag, if it exists for any file. This should be backwards compatible with the current view, so long as one does not have that tag populated. Alternatively, a new setting could allow users to toggle this sprting on or off.

### Alternatives

A survey of FOSS Android media players seems to indicate that Symphony isnt alone in this behavior. Vinyl, PhonographPro, Auxio, VibeYou, and one or two others show off this same behavior. I don't know how best to alleviate this wothout retagging my library and I VRRY MUCH dont want to do that

### Additional Context

N/A

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
Sorting by album artist already exists in songs view. Are you asking the same for albums view!

**Comment by bbenne10** [comment]
I think that is a fair assessment of my request.

**Comment by zyrouge** [comment]
It seems like the "artist" sorting actually sorts by "album artist". Feel free to re-open if mean something else.
