### ISSUE TITLE
[Feature Request] Option to disable case-sensitive sorting

### ISSUE THREAD

**Issue by culots** [zyrouge/symphony#445]
### Description

Filenames/titles are sorted case-sensitively throughout the app. For example, say I have an album by an artist named 'smalldoghead', who for silly artistic reasons refuses to acknowledge the existence of uppercase letters. Due to the title's lowercase beginnings, when the list is sorted it'll be placed way at the bottom after the Zs instead of with all the fancy uppercase Ss.

### Solution

I would like an option to disable case-sensitive sorting/enable case-insensitivity in sorting.

### Alternatives

Acceptance is the only other option. I am entirely ready to live with it as is. It is a minor niggle. We are still in the bargaining phase though, so here I bargain.

### Additional Context

n/a

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by sevonj** [comment]
I personally don't think this even needs to be an option. Is there any use case for case-sensitive sorting?
