### ISSUE TITLE
[Bug] Search-box should bring up keyboard again when re-selected

### ISSUE THREAD

**Issue by dezponia** [zyrouge/symphony#447]
### Description

After searching for something using the search-bar and then scrolling the results you may want to refine your search. Re-selecting the search-bar at this point does not bring up the keyboard again if you've closed/hidden the keyboard. At this point it appears you have to back out of the current search and open a new one to try again.

### Solution

When re-selecting the search-box text field it should bring up the keyboard again.

### Alternatives

Less alternatives but small workarounds for users that often write longer searches and that find this issue after running into this behavior.

- You can still select the search-box and choose "Select all" and "Copy". Then back out and "Paste" your old search on the second try and refine it further. This way you don't have to re-write the entire search string a second time.
- You can select one of the items it returned, for example you can enter one of the Albums the search suggested and then back out from the Album. This will return you to the search view with your old search string intact and bring up the keyboard again so you can refine it.

### Additional Context

It appears the text cursor is always active in the search-bar, indicating it never loses focus when doing other things like scrolling the result? Perhaps this is related to why its not triggering the keyboard when re-selected?

This might be more classified as a bug in the current behavior if its unintended?

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by BlastboomStrice** [comment]
I think this is fixed now, right?

**Comment by zyrouge** [comment]
> I think this is fixed now, right?

Not really, this bug is caused due to how Compose handles input focus. Unfortunately, there are no fixes that I can implement.

**Comment by BlastboomStrice** [comment]
Ah ok, I said that because I think it got fixed on my device after the last update (android 11, miui 12.6, xiaomi mi 10)

**Comment by zyrouge** [comment]
Oh, it seems like it is. Closing this as fixed.
