### ISSUE TITLE
[Bug] Play queue is gone when BT Headphones are disconnected

### ISSUE THREAD

**Issue by Skivling** [zyrouge/symphony#460]
### Description

I am listening to a song via Bluetooth headphones, and then I turn Bluetooth off. I then lose the current song and play queue. 

### Steps to Reproduce

1. Listen to music via Bluetooth headphones
2. Turn bluetooth off via the phone
3. After it disconnects, the current playing song and play queue will be lost.

### Expected Behavior

It should keep the play queue but pause the current song.

### Screenshots

I don't have any screenshots.

### Device

-   Device: Samsung Galaxy A12
-   OS: Android 13
-   Version: Symphony v2024.1.109

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
I cannot seem to reproduce this issue. Feel more to re-open with additional information.
