### ISSUE TITLE
[Bug] Importing a .m3u playlist does not include the tracks

### ISSUE THREAD

**Issue by DragoniteChamp** [zyrouge/symphony#461]
### Description

When attempting to import an external m3u playlist, the playlist will be added, but no tracks will be added to said playlist.

### Steps to Reproduce

1. Create your m3u playlist. Mine specifically was created using MusicBee.
2. Attempt to import it.
3. Open said playlist. No tracks will be included.

### Expected Behavior

The playlist should include any tracks, assuming they are on device.

### Screenshots

A video will be included.

https://github.com/zyrouge/symphony/assets/76917579/effcac51-fa26-4156-8f99-59ec7a6bde62

### Device

-   Device: Google Pixel 7 Pro
-   OS: Android 14
-   Version 2024.1.109

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by DragoniteChamp** [comment]
After checking the m3u by converting it to a txt, it does appear to be correct.
![image](https://github.com/zyrouge/symphony/assets/76917579/e4823c90-083e-4bad-b3ec-2e73d86f018c)
![image](https://github.com/zyrouge/symphony/assets/76917579/4f1a3742-4407-401f-aa8b-f7ef9cd73da2)

**Comment by zyrouge** [comment]
The path starts with `/Music` which not equivalent of `/storage/emulated/0/Music`. Using relative paths is recommended to not face these issues.

**Comment by JetpackJackson** [comment]
Hi, I'm having this same issue with absolute paths. I have a Linux script that generates my playlists for me by listing the music files and then prepending `/storage/emulated/0/Music/`. However, VLC plays them fine while Symphony does not. I did a test where I created a one song playlist in Symphony and then opened it up to see how it was written. I noticed a `#EXTM3U` at the beginning of the file and then two lines for the song, one with an absolute path and one with what I guess is a relative path (it has `#EXTINF:0,` followed by the song filename).

However, is there a way to get it to work with just a list of absolute paths? I don't want to try to recreate my playlists in the app as my collection is large enough to make it a tad time consuming lol.

**Comment by zyrouge** [comment]
> Hi, I'm having this same issue with absolute paths. I have a Linux script that generates my playlists for me by listing the music files and then prepending `/storage/emulated/0/Music/`. However, VLC plays them fine while Symphony does not. I did a test where I created a one song playlist in Symphony and then opened it up to see how it was written. I noticed a `#EXTM3U` at the beginning of the file and then two lines for the song, one with an absolute path and one with what I guess is a relative path (it has `#EXTINF:0,` followed by the song filename).
> 
> However, is there a way to get it to work with just a list of absolute paths? I don't want to try to recreate my playlists in the app as my collection is large enough to make it a tad time consuming lol. Thanks in advance, and thanks for the app!

Alright, I'll do that.
