### ISSUE TITLE
[Bug] Themed Icons Support Got Broken

### ISSUE THREAD

**Issue by JayXT** [zyrouge/symphony#463]
### Description

It looks like with the last release(s) the support for this Android feature has disappeared.

When themed icons are enabled, the Symphony icon doesn't change as other apps do:

![image](https://github.com/zyrouge/symphony/assets/8045344/3f8030a2-5175-43f9-b0bd-3bac43719ae9)

### Device

-   Device: Google Pixel 6a
-   OS: Android 14 (Graphene OS)

### Checklist

-   [ x ] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
This has already been fixed in nightly.
