### ISSUE TITLE
[Bug] "Artist tag value separators" don't apply to Album Artists

### ISSUE THREAD

**Issue by dezponia** [zyrouge/symphony#470]
### Description

The values defined in the setting "Artist tag value separators"  do not apply to the "Album Artist" tags, only the "Artists" tags.

This was previously discussed in the below issue comment and resolved for Artists in that issue:
https://github.com/zyrouge/symphony/issues/93#issuecomment-1675692109

### Steps to Reproduce

1. Add a album from an artist with a "value separator" in both "Artist" and "Album Artist" tags. For example "`AB/CD`".
2. Remove slash (`/`) from the "Artist tag value separators" list in settings.
3. Navigate to one of the album tracks and open the "Details" view for the track.
4. Note that "Artists" and "Album Artist" are displayed differently, with one including the slash and the other displaying `AB` and `CD` as different "Album Artists".

5. Optional extra steps:
6. Enable the "Album Artists" navigation view and scroll through the list to the affected Album Artist.
7. Note that the Album Artist is split here as well, creating both an AB and CD Album Artist in this view.

### Expected Behavior

Artist and Album Artist should share the same "Artist tag value separators" settings and behavior. Alternatively they can have separate "tag value separator" settings but I don't think this is necessary?

### Device

-   Device: Fairphone 5
-   OS: Android 13
-   Version: Symphony v2024.1.109

### Additional Context

Different file formats have different rules for metadata tags. Some explicitly state that "Album Artists" should not contain multiple values, while this is ok for the "Artists" tag. I think its probably safe to assume that no setting will please everyone so therefor I suggest letting the one "Artist tag value separators" setting control both "Artist" and "Album Artist" tags.

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
Seems like this has already been implemented. Feel free to re-open if you have any issues.
