### ISSUE TITLE
[Bug] Smooth scrolling does not work while animations are off

### ISSUE THREAD

**Issue by quintus3236** [zyrouge/symphony#48]
Hello!

I use my phone with animations off (makes it faster to navigate imo) and smooth scrolling does not work while they are off.

**Comment by zyrouge** [comment]
As far as I know, Compose still has poor support for scrolling. This is not yet controllable within the code. I'll be putting this on hold until then.

**Comment by zyrouge** [comment]
I don't think this could be implemented due to restrictions of Compose. I might be wrong but I cannot find any valid solution to fix this. Feel free to PR this if anyone has a solution for this.

**Comment by zyrouge** [comment]
Closing this since there has not been any viable solution.
