### ISSUE TITLE
[Feature Request] Filter songs shorter than 3 seconds.

### ISSUE THREAD

**Issue by Wjxfi** [zyrouge/symphony#49]

**Comment by RustoMCSpit** [comment]
3 seconds shouldnt be static, a dynamic variable is better

**Comment by sevonj** [comment]
I can do this, unless some obstacle comes up with metadata, or how songs are imported.

**Tasks:**
- Add a value to settings for the time limit. Value is optional, null means the setting is off. Defaults to off.
- Add UI item under Settings/Groove
- When importing a song, bail out if the limit exists and duration is under it.

There is probably no need to go through the library to remove songs, rescan will handle it?

**Comment by zyrouge** [comment]
> I can do this, unless some obstacle comes up with metadata, or how songs are imported.
> 
> **Tasks:**
> 
> * Add a value to settings for the time limit. Value is optional, null means the setting is off. Defaults to off.
> * Add UI item under Settings/Groove
> * When importing a song, bail out if the limit exists and duration is under it.
> 
> There is probably no need to go through the library to remove songs, rescan will handle it?

Yup, rescan will handle it.
