### ISSUE TITLE
[Feature Request] Grid size and artist cover art

### ISSUE THREAD

**Issue by HanaO00** [zyrouge/symphony#498]
### Description

The size of the artists and albums grid cannot be changed

### Solution

Being able to change the size of the artist grid which is currently two columns, but also being able to modify the image of the artists who are currently using album cover art would be great

### Alternatives

N/A

### Additional Context

N/A

### Checklist

-   [X] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by sevonj** [comment]
Hi, I just tried the app, and the massive grid size immediately bothers me. My proposed solution is to add a control roughly like this:
![image](https://github.com/user-attachments/assets/85f33134-0521-4b27-ae73-15dda392d471)

I haven't really looked at the source code yet, but I can probably build this feature.

This issue tracks two unrelated features, the other one should probably be split off this.
