### ISSUE TITLE
Use a gesture as a button

### ISSUE THREAD

**Issue by Wjxfi** [zyrouge/symphony#50]
![321155.jpg](https://user-images.githubusercontent.com/113500363/222758106-bde0bdbf-2348-4305-a1a7-39d5cb2f8d2a.jpg)

https://user-images.githubusercontent.com/113500363/222758126-fa4507df-0426-470f-8ccc-c6997a4a57ff.mp4

(From top to bottom anywhere)

**Comment by zyrouge** [comment]
Merging with #37.
