### ISSUE TITLE
[Bug] Crash due to "Concurrent Modification Exception" when playing music and browsing through library

### ISSUE THREAD

**Issue by Currrupted** [zyrouge/symphony#504]
### Description

Recently, Symphony has been crashing and showing fatal errors, occasionally. Today, when I was inside the app while playing music, the app crashed again and the error screen popped up. It showed the error "java.util.ConcurrentModificationException" (see below).

I had to close and restart the app, after which everything worked fine again. 

### Steps to Reproduce

Unfortunately, I could not find a way to cause the error again. It seems to be unrelated to anything I was doing. However, this is what I did:

1. Open the application and start playing any track or playlist
2. Stay in the application
3. Browse inside the app and through the library
4. The app crashes, throwing the error shown below

### Expected Behavior

The error and crash, which happened here, shouldn't occur. Using the app to play files and browse through the library should work without anything going wrong.

### Screenshots

![photo_2024-04-02_15-30-55](https://github.com/zyrouge/symphony/assets/13292623/08c168b8-2b9c-4d4b-beb7-10a495f08c10)

### Device

-   Device: Sony Xperia XA2
-   OS: Android 12 (LineageOS 19.1)
-   Version: 2024.3.110

### Additional Context

I have tried to obtain the logs through adb, however I couldn't get them for the time in question. If it is of any help, I can try again.

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
I'm not sure where that error is from due to obfuscation. I'll be attaching log-symbols from the next release, will be looking into this after that.

**Comment by varun325** [comment]
It's similar for my device as well, though it occurs when the application is in background, I usually start a lofi playlist and let the phone stay in background. After a while at some point this happens and when I unlock the phone, I see this error. It does seem that the crash occurs while tracks change from one to the next, that's after one song in the queue ends and a new one starts.

**Comment by zyrouge** [comment]
Is this still relevant?

**Comment by Currrupted** [comment]
> Is this still relevant?

Yes, as far as I can tell. It still seems to occur on the newest version (2024.11.114), however not on another device I recently switched to. I am not using the old one anymore, on my new phone it seems to be resolved. Both are running on LineageOS 21. The new device has more RAM available however, and I feel like it was mainly related to that before.

**Comment by zyrouge** [comment]
Unfortunately, the error traced to `kotllin.collections` which was not really helpful. I assume that the error occurred when the queue was being iterated. Thus, the custom `ConcurrentList` implementation was switched up for `CopyOnWriteArrayList`. Hopefully, this fixes it.

**Comment by madmini** [comment]
Just got this on v2024.12.115 during background play track change ([as described by varun325 above](https://github.com/zyrouge/symphony/issues/504#issuecomment-2106163923))

![Image](https://github.com/user-attachments/assets/4113ead4-3a45-4cd6-be47-e1e81957d565)
