### ISSUE TITLE
[Feature request] Round up or remove the white highlighting when you click on settings

### ISSUE THREAD

**Issue by Wjxfi** [zyrouge/symphony#51]
![321159.jpg](https://user-images.githubusercontent.com/113500363/222759633-7826f562-3793-48ed-a735-45c0947e09f6.jpg)

it's not pretty compared to the rest of the interface.

**Comment by zyrouge** [comment]
That's something related to Material Design. That ripple is found all over the design. This app does follow Material Design in basic components. Also, that's just a subtle thing since it basically only occurs for less than a second. Closing this.
