### ISSUE TITLE
[Bug] Bad convertion CP1251 name

### ISSUE THREAD

**Issue by Doumor** [zyrouge/symphony#513]
### Description

Bad convert CP1251 name.
Like this:
![изображение](https://github.com/zyrouge/symphony/assets/76202525/537545a9-2629-4ecf-b651-b5089141c150)
Ideally there should be readable Cyrillic words there.

I assume there should be a check for CP1251 in the code and a proper conversion for it. Right now it looks like CP1251 is being translated to ISO-8859-1. Люди -> Ëþäè and e.t.c.

### Steps to Reproduce

Try to add song with CP1251 name.

### Device

-   Device: Infinix Note 30
-   OS: Android 13
-   Version: Current from F-Droid

### Checklist

-   [+] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
Unfortunately, MediaStore does not parse them correctly. A possible solution would be #417.

**Comment by zyrouge** [comment]
Possible fixed as a side-effect of #567.
