### ISSUE TITLE
[Feature Request] Adjust monet theme/accent based on album artwork

### ISSUE THREAD

**Issue by Mnky313** [zyrouge/symphony#516]
### Description

Option to have the app/now playing screen's colours change based on the currently playing song's album artwork.

### Solution

Adding an option to dynamically change theme colours based on currently playing song's album artwork

### Alternatives

Not sure, changing just the now playing screen if possible?

### Additional Context

An example of what I'm talking about from Metro/Retro:
https://github.com/zyrouge/symphony/assets/23646586/7c1d0290-fcf9-4b08-8202-6ddf6c3ec1a0

### Checklist

-   [X] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by Currrupted** [comment]
I think this would be neat. Even a subtle color change (e.g. by using gradients) would also make an impression.

**Comment by zyrouge** [comment]
Closing this in favor of #102.
