### ISSUE TITLE
[Bug] The latest code cannot be compiled and run.

### ISSUE THREAD

**Issue by Orchid-Lee** [zyrouge/symphony#518]
### Description

Hello,  I pulled the latest code, but when I ran it, I got an error, showing that there is no `_Translation` class, and the `AddToPlaylist` under `context.symphony.t` could not be found. Is the current code complete, or there is something wrong with my configuration?

### Steps to Reproduce
Pull the latest code and run.

### Screenshots
![1713367885245](https://github.com/zyrouge/symphony/assets/93301186/61eb6552-b0e2-4107-88e3-cca0fa9da293)
![image](https://github.com/zyrouge/symphony/assets/93301186/4ea23ad9-06fa-4ab9-9530-74fe6d5468a8)

### Device
-   Android Studio 
-   Compile Sdk Version: 34
-   Gradle Version: 8.2

**Comment by zyrouge** [comment]
Follow the [developers guide](https://github.com/zyrouge/symphony/wiki/Developer-Guide). Let me know if you face any trouble.

**Comment by Orchid-Lee** [comment]
Thanks, I didn't notice this guide before.

________________________________
