### ISSUE TITLE
[Bug] App crashes

### ISSUE THREAD

**Issue by Vardhannn** [zyrouge/symphony#519]
### Description

Music player crashes and malfunctions frequently in my android phone when every i try to play the next song.

### Solution

I was casually listening songs in app when i press the play next button app crashes all of a sudden

### Alternatives

Maybe i have an old version of android, please mention some system requirements.

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
Closing this as stale.
