### ISSUE TITLE
[Feature request] Add a repeat song/playlist button in the notification

### ISSUE THREAD

**Issue by Wjxfi** [zyrouge/symphony#52]
![321167.jpg](https://user-images.githubusercontent.com/113500363/222763160-e6dbcab6-bdd8-4c53-a572-7cb862ae5682.jpg)

![321168.jpg](https://user-images.githubusercontent.com/113500363/222763161-b45351f9-ae78-4ea3-8f4f-9a3586cda6f4.jpg)

![321169.jpg](https://user-images.githubusercontent.com/113500363/222763159-f8f01563-8257-44b5-873f-edb9f4ae28df.jpg)

![321171.jpg](https://user-images.githubusercontent.com/113500363/222763209-e37c8561-6d82-49da-86a9-9cff189e6e92.jpg)

**Comment by zyrouge** [comment]
Playlist button?

**Comment by zyrouge** [comment]
Media Notification does not allow more than 5 actions. It's impossible to add two more actions to it. The notification currently has basic actions. I don't think I should try and bloat it.
