### ISSUE TITLE
[Bug] Crash while playing music in the background

### ISSUE THREAD

**Issue by gradha** [zyrouge/symphony#525]
### Description

A playlist was playing in the background with the device screen locked. At the end of the song the music stopped. After unlocking the screen I saw the following crash report. After restarting the app I was able to play the same playlist without problem and haven't had any more crashes with version v2024.3.110.

```
Error: java.util.NoSuchElementException: Collection is empty.
java.util.NoSuchElementException: Collection is empty. 
 at b5.q.k1(Unknown Source:35) 
 at r4.k.a(Unknown Source:270)
 at r4.j.t(Unknown Source:12) 
 at g5.a.o(Unknown Source:8) 
 at co.r.t(Unknown Source:6)
 at x5.a.o(Unknown Source:22) 
 at g5.a.o(Unknown Source:31)
 at x5.i0.run(Unknown Source:114) 
 at do.a.run(Unknown Source:91)
Suppressed: c6.f: [slCancelling}@15fddc2,
```

![Screenshot_2024-04-18-19-01-14-779_io github zyrouge symphony](https://github.com/zyrouge/symphony/assets/101927/85a1ba6e-21eb-4b91-81c7-8ce8a6fa30af)

**Comment by zyrouge** [comment]
Unfortunately the stack trace cannot be used since it's obfuscated. Let me know if this happens in the next version.
