### ISSUE TITLE
[Bug] App does not adapt to the Material You palette

### ISSUE THREAD

**Issue by justpanchi** [zyrouge/symphony#532]
### Description

The app doesn't utilize the correct colors when enabling Material You theming, consistently adhering to the same color scheme regardless of the background. This issue is specific to Symphony in my experience (as of [v2024.2.110-nightly+91b949f](https://github.com/zyrouge/symphony/releases/tag/v2024.2.110-nightly%2B91b949f)).

### Steps to Reproduce

1. Open the app.
2. Navigate to the settings menu.
3. Enable the Material You theme option.

### Expected Behavior

The colors should be accurately reflected throughout the app, aligning with the system's chosen palette.

### Screenshots

![Symphony_2024 1 109](https://github.com/zyrouge/symphony/assets/140990709/a3f07dcc-0be4-40d9-903e-e2b162926125)
![Symphony_2024 3 110](https://github.com/zyrouge/symphony/assets/140990709/aa6b8e19-5592-4fa2-a86b-bdb3b48b6bc4)

### Device

-   Device: Samsung Galaxy S21 FE 5G
-   OS: Android 14, One UI 6.0
-   Version: 2024.3.110

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
This might be specific to you. I or any other users have not faced/reported this issue.

**Comment by zyrouge** [comment]
Or, do you mean that the color is not adapted to the song's cover?

**Comment by zyrouge** [comment]
Could you check with the latest nightly build?

**Comment by zyrouge** [comment]
I don't seem to be facing this issue. Feel free to re-open this still persists.
