### ISSUE TITLE
[Feature Request] Edit Imported Playlist

### ISSUE THREAD

**Issue by NayamAmarshe** [zyrouge/symphony#543]
### Description

I just imported my playlists but was surprised to see there's no option to edit them. Earlier, I was using Metro Player and it allowed editing imported playlists, and most other music apps do as well. I think it'd be great if Symphony can allow editing imported playlists. There's no downside to having this feature.

### Solution

Add an option to edit the playlist. Remove and add tracks.

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
It boils down to how Symphony treats imported playlists as. Important playlists are fetched externally everytime and is not saved internally. This allows Symphony to adapt changes to those playlists made externally. The solution for you would be to duplicate it. You can edit playlists created within Symphony. Export it to an M3U playlist when you need. I'll close this for now, feel free to drop your thoughts.

**Comment by NayamAmarshe** [comment]
> It boils down to how Symphony treats imported playlists as. Important playlists are fetched externally everytime and is not saved internally. This allows Symphony to adapt changes to those playlists made externally. The solution for you would be to duplicate it. You can edit playlists created within Symphony. Export it to an M3U playlist when you need. I'll close this for now, feel free to drop your thoughts.

Ah got it. If Duplicating the playlist works, that's a good enough solution for me :) Thanks!

**Comment by NayamAmarshe** [comment]
Wait, I don't see any duplicate option though 😅 I have hundreds of songs, how can I duplicate the playlist?

**Comment by zyrouge** [comment]
> Wait, I don't see any duplicate option though 😅 I have hundreds of songs, how can I duplicate the playlist?

Click the three-dots on the playlist tile -> add to playlist -> create new playlist.
