### ISSUE TITLE
[Bug] Random song covers not loading

### ISSUE THREAD

**Issue by Daenges** [zyrouge/symphony#55]
Seemingly random songs are rendered without their cover image **despite their file having one included in their metadata**. 
(I checked this on my PC)

Strangely the amount of missing covers is higher in the first half of the list than in the second one, where nearly every cover is present. A cache clear does not fix this. The songs missing their cover are always the same.

Version: **v2023.3.73**

<details>
<summary>Show Screenshot</summary>

![Screenshot_20230304-152557](https://user-images.githubusercontent.com/57369924/222908029-85902480-3ae4-49a8-a737-825d72d49c78.png)

</details>

**Comment by zyrouge** [comment]
This is probably an issue with MediaStore. Currently, the app does not parse the metadata by itself, rather it just asks MediaStore to fetch them. There are also no good ID3 readers currently so I'm hesitant on doing it myself. For me, this issue doesn't occur 99% of times, but seems like you suffer from it. I'll look around for a way to do it.

**Comment by Daenges** [comment]
Thank you for the quick response. I had it working at some point. But then I deleted a copy of my music folder on my Phone, that I used to copy it to the SD card and suddenly covers were missing... Despite this folder being in the blacklist and having nothing to do with my actual files.

**Comment by zyrouge** [comment]
Copying might have broke the Media Storage service which ended up not fetching the albums. Maybe you could try to refresh your MediaStore cache but I don't think there is a reliable way to do it.

**Comment by Daenges** [comment]
Problem just fixed itself somehow. Maybe an internal reset of said library. :)

**Comment by zyrouge** [comment]
> Problem just fixed itself somehow. Maybe an internal reset of said library. :)

I guess that sums it all up. With no real reliable solution, I'll just close until someone faces the same issue. Thanks you for your prompt responses.

**Comment by Daenges** [comment]
Another idea would be that 600+ songs at once may have exceeded some API limit.
