### ISSUE TITLE
[Feature Request] Add repeat control in Notification

### ISSUE THREAD

**Issue by Wjxfi** [zyrouge/symphony#56]
I asked you to add one button, not two. If you add it, you're not over the limit. Right now there are only four buttons. I'm asking you to add a fifth.

my answer is from there:

you don't get it. I'm only asking you to add 1 button. It has three modes. 
![321180.jpg](https://user-images.githubusercontent.com/113500363/222765615-654bae44-c469-4e57-827c-0aa7d9b0962d.jpg)

https://user-images.githubusercontent.com/113500363/222770612-210c4386-af39-4d47-ac2c-e7efa998cf87.mp4

youtube (yt music), newpipe, all normal music players have this button. Add it so you don't fall behind

If you add this button you won't go beyond.

**Comment by zyrouge** [comment]
Well, then Spotify doesn't do this. I don't feel the necessity of having the repeat button in the notification among the basic playback controls. It doesn't make sense to have it. Again, unless there is a demand, I won't add this. Not being rude, but this is just something I don't think will be that useful. I'll keep this open for further discussion.

**Comment by zyrouge** [comment]
Being subjective isn't going to work.

**Comment by zyrouge** [comment]
Closing this since it will not be implemented.
