### ISSUE TITLE
[Feature Request] Please add sorting options in songs view

### ISSUE THREAD

**Issue by sdazero** [zyrouge/symphony#582]
![IMG_20240801_190335](https://github.com/user-attachments/assets/d093dbc4-5e85-4f9c-8986-de72bed30bfb)
(This pic is showing an example in german from metro player.)

Last added tracks, Size, Bitrate, Componist, Interpret, Year, Album would be nice.

[ x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by sdazero** [comment]
Please delete.

**Comment by zyrouge** [comment]
> Please delete.

Issues cannot be deleted. Let me know if you need something to be implemented.

**Comment by sdazero** [comment]
Okay. I found the option inside symphony.

**Comment by sdazero** [comment]
Okay. I found the option inside symphony.
