### ISSUE TITLE
[Feature Request] Add Left-Handed Play/Prev/Next buttons

### ISSUE THREAD

**Issue by LeftyDextrous** [zyrouge/symphony#586]
### Description

The default player buttons look cool and are very convenient for people who hold their phone with their left hands. I, being a lefty, do not benefit from this but would like to.

### Solution

Mirror the buttons. Add an option to put them on the right side. I personally would prefer it so that the play button is closest to the edge (i.e. a mirror image), but an option may also be considered for it being close to the center (i.e. right justification).

### Alternatives

Assuming that the technical difficulties are minimal, an option to mirror the entire "Now Playing" page may be considered as an extention of this feature, but that would be more of an aesthetic choice than a practical one. Note also that the "Traditional" setting for button placement is ambidextrous, but it is a compromise rather than a full solution.

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by sevonj** [comment]
I propose changing the layout enum to three options:

NowPlayingControlsLayout:
- Compact left (currently known as Default)
- Compact right 
- Traditional

I prefer calling it Compact because Default vs Traditional tells nothing about what they ui is actually like.

Left-handed button order would be a separate setting.

**Comment by sevonj** [comment]
I can make this once I'm done with other pr's. This is how it'd look:

![image](https://github.com/user-attachments/assets/83531126-09d1-4c5a-8cfe-7f8c4262fe18)
