### ISSUE TITLE
[Feature Request] Add info about the year an album was released.

### ISSUE THREAD

**Issue by LeftyDextrous** [zyrouge/symphony#587]
### Description

There is no easy way to find the year an album was released.

### Solution

Add information about the year an album was realized on the "Now Playing" and Album screen, perhaps on the Artist line, separated by a dot.

### Alternatives

This is by far the simplest means of solving this problem.

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by scytho** [comment]
That would be great, I missed that, too, recently.

**Comment by sevonj** [comment]
I kind of touched this in #666, but I'll write it down here.

I think the album view header is a great place to show this kind of metadata.

Mockup:

![image](https://github.com/user-attachments/assets/ac33b0bb-09ee-4522-b399-b981418414a6)

**Comment by sevonj** [comment]
Since the last comment, there are new considerations.

Album year is (possibly) a range. I guess the way to go is to format it as a range if start and end years differ, or a single year if not.

("2000-2002" / "2002")
