### ISSUE TITLE
[Bug] App is incorrectly displaying dates for songs in info section

### ISSUE THREAD

**Issue by SunBreaker1** [zyrouge/symphony#59]
I'm not sure if im the only one who has this issue or has noticed this, but I find it kind of weird.

This app shows the wrong date, while another shows the right date, this also appiles to pretty much all my songs download locally on my phone.

While not important, its still a bug, so I thought I would bring it up if it hasn't already been.

![Screenshot_20230306-234446_Symphony.jpg](https://user-images.githubusercontent.com/85519676/223282289-7a5c996c-4f94-43c9-b03a-d2dc6654abc8.jpg)

**Comment by SunBreaker1** [comment]
Damn, I guess when 70's were really different than what the history books taught us. VTubers existing and dropping beats in FLAC, wild times.

**Comment by zyrouge** [comment]
Same for me.

**Comment by zyrouge** [comment]
:tada: Fixed as of v2023.3.79!
