### ISSUE TITLE
[Feature Request] Support gapless playback

### ISSUE THREAD

**Issue by JuxGD** [zyrouge/symphony#594]
### Description

Some tracks, especially in LPs, end transitioning seamlessly into another track (segues). Symphony has a pretty short time between track but it's not instant, breaking the "seamlessness" of it. Spotify supports this for albums only. foobar200 also does this (don't know the details, @scytho mentioned this)

### Solution

We could have a "gapless into next track" setting for individual tracks and playlists/albums, when it's enabled it loads the beginning of the next track ahead of time (some time before the current track ends) so it can start playing it the instant the current track ends.

### Alternatives

Have it happen globally, without a setting for specific tracks and playlists/albums, this would be configured with a "time between tracks" setting

### Additional Context

- [Aetherborne LP from Chime](https://youtu.be/Nik2BE958lI) is an album that uses segues for its tracks, you can notice it more starting from the 3rd track (Homeworld). This album is better experienced with gapless playback.

- This issue used to be called "Support seamless transitions (segues)"

### Checklist
-   [x] I have read the [Contribution Guidelines]

**Comment by scytho** [comment]
I think, this is called gapless playback. foobar2000 does this. It is one of the few features I am missing. Otherwise Symphony is the best and the most logically behaving player I have found so far.

**Comment by scytho** [comment]
I recently noticed that gapless playback isn’t (always) working.

**Comment by JuxGD** [comment]
> I recently noticed that gapless playback isn’t (always) working.

I opened an issue on this, #720 (edit half a year later, i didn't open it mb i just participated in it)

**Comment by JuxGD** [comment]
Wait,

> (always)

? When *does* it work? @scytho

**Comment by scytho** [comment]
Sorry, it just doesn’t. I thought I had noticed it only sometimes. I have just tested it with FLAC and Vorbis files. No gapless playback.
