### ISSUE TITLE
[Bug] Rewind and fast-forward buttons missing in traditional layout

### ISSUE THREAD

**Issue by sojusnik** [zyrouge/symphony#598]
### Description
When selecting the "default" layout, then the rewind and fast-forward buttons are present in the "now playing" window, but not when using "traditional" (Settings -> Now Playing -> Controls layout -> Traditional).

### Expected Behavior
Rewind and fast-forward buttons should be present in both the default and traditional layout.

### Device
-   OS: Android 13
-   Version: 2024.3.110

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
Seems to be fixed in the nightly. Feel free to open if you face any issue.
