### ISSUE TITLE
[Bug] can't import playlist

### ISSUE THREAD

**Issue by Ar9791** [zyrouge/symphony#603]
Hi I have some playlists on my samsung music app and when I'm trying to import them the songs in that playlist doesn't show up but the playlists I made in that app works fine.
Can you fix it?
Thanks

**Comment by zyrouge** [comment]
Check the content of the playlist created by Samsung music app. Symphony can only import playlists that use extended m3u format.

**Comment by Ar9791** [comment]
![Screenshot_20241001_164715_Symphony](https://github.com/user-attachments/assets/d6914e1a-c5bf-4a28-ac48-b0018426b08a)
![Screenshot_20241001_164642_Samsung Music](https://github.com/user-attachments/assets/5ca75972-866d-4227-95f8-0cac666f369a)
Like this

**Comment by zyrouge** [comment]
You should check the content of the exported .m3u file.

**Comment by Ar9791** [comment]
Well when I'm importing the m3u files to other music player they have no issue.

**Comment by zyrouge** [comment]
Closing this as stale. Feel free to reopen if this still persists.
