### ISSUE TITLE
[Bug] App stopped

### ISSUE THREAD

**Issue by AykhanUV** [zyrouge/symphony#604]
### Description

I don't know what causes this bug but it happened after i re-opened app from recent apps menu

### Expected Behavior

Normal opening
### Screenshots

![Screenshot_2024-10-11-20-55-13-107_io github zyrouge symphony](https://github.com/user-attachments/assets/51af5ee2-52fb-4c8d-939c-1833857f7cd6)

### Device

-   Device: Poco x6 pro
-   OS: Android 14
-   Version 2024.03.110

### Additional Context

-

### Checklist

-   [x ] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
This is something that Android does when notifications are not created within the time limit. This shouldn't happen often and can be safely ignored, let me know if it does.
