### ISSUE TITLE
Enable predictive back gesture support (android 14+)

### ISSUE THREAD

**Issue by rayyanmm** [zyrouge/symphony#606]
### Description

 it is not a major problem, it is just a feature to help integrate with newer versions of android that's all. It is very minor and I understand that you may have "bigger fish to fry" as they say.

### Solution

in AndroidManifest.xml, in the tag, set the android:enableOnBackInvokedCallback flag to true.

```
<application
    ...
    android:enableOnBackInvokedCallback="true"
    ... >
...
</application>
```

### Alternatives

none

### Additional Context

link to android developer page explaining this feature: https://developer.android.com/guide/navigation/custom-back/predictive-back-gesture

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
It has already been enabled ([source](https://github.com/zyrouge/symphony/blob/main/app/src/main/AndroidManifest.xml#L18)). I have not tested this.

**Comment by zyrouge** [comment]
I can confirm that predictive back gestures are working.
