### ISSUE TITLE
[Feature Request] In app music downloader

### ISSUE THREAD

**Issue by AykhanUV** [zyrouge/symphony#614]
### Description

It would be great if there was feature to download music right in app

### Solution

You could look at YTDLnis app they use yt-dlp and they have a search function that searches from youtube

### Alternatives

-

### Additional Context

-

### Checklist

-   [x ] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
Nope. Symphony is purely focused on offline features. Marking this as out of scope of this project.
