### ISSUE TITLE
[Bug] App crash when opening settings

### ISSUE THREAD

**Issue by wanzh5** [zyrouge/symphony#617]
### Description

Trying to open the settings will cause a crash (even after a fresh installation).

### Steps to Reproduce

1. install the app
2. open settings
3. app crashes

### Expected Behavior

The app no ​​longer crashes.

### Screenshots

here is the log.
![1000046246](https://github.com/user-attachments/assets/f37e2331-4534-4114-bf5f-d7e52cc6ceea)
![1000046247](https://github.com/user-attachments/assets/efae22a1-d115-4635-a0bd-c105673afac1)
![1000046248](https://github.com/user-attachments/assets/bcbc146d-927e-4678-9e41-bc5871aef864)

### Device

oneplus11

### OS

crdroid10 (android14)

### Version

v2024.10.112-nightly+42faa35

### Contribution Guidelines

- [X] I agree to follow the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
I did notice this issue. Will be fixed shortly.
