### ISSUE TITLE
[Bug] Unrelated results for search queries

### ISSUE THREAD

**Issue by Lucifer25x** [zyrouge/symphony#621]
### Description

When I try to search for an artist/song/album title, there's almost always unrelated results. Sometimes those results bury the real result. I don't if it's a feature that I misunderstood. But I think normally this functionality shouldn't work that way.

### Steps to Reproduce

1. Open the app
2. Search for something
3. Look at the results

### Expected Behavior

The results should be related to search query.

### Screenshots

![Screenshot_2024-10-31-08-48-18-720_io github zyrouge symphony](https://github.com/user-attachments/assets/c8b747e7-8159-4631-80c3-748dcf69ae66)

### Device

Redmi Note 12 4G (topaz)

### OS

Android 14

### Version

2024.3.110

### Contribution Guidelines

- [X] I agree to follow the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
I did not filter the search results since they might not always be unrelated search even if they don't match. At best, the first few results are the best possible matches to the search result. It's better to reveal more information than abstract them in this case.

**Comment by Lucifer25x** [comment]
> I did not filter the search results since they might not always be unrelated search even if they don't match. At best, the first few results are the best possible matches to the search result. It's better to reveal more information than abstract them in this case.

Thanks for answering, is there any way to search for an exact title (like regular expression etc.) currently in the app?

**Comment by zyrouge** [comment]
> > I did not filter the search results since they might not always be unrelated search even if they don't match. At best, the first few results are the best possible matches to the search result. It's better to reveal more information than abstract them in this case.
> 
> Thanks for answering, is there any way to search for an exact title (like regular expression etc.) currently in the app?

No. But, ability to search using regex might be a really good option.

**Comment by Lucifer25x** [comment]
> > > I did not filter the search results since they might not always be unrelated search even if they don't match. At best, the first few results are the best possible matches to the search result. It's better to reveal more information than abstract them in this case.
> > 
> > 
> > Thanks for answering, is there any way to search for an exact title (like regular expression etc.) currently in the app?
> 
> No. But, ability to search using regex might be a really good option. Open a new issue so it can be tracked.

Thanks, I'll open it now.
