### ISSUE TITLE
[Feature] Edit Music Metadata

### ISSUE THREAD

**Issue by obakha** [zyrouge/symphony#628]
### Description

The app currently lacks the ability to edit the metadata of music files, such as title, artist, album, and genre. This limits users' ability to organize and customize their music library effectively.

### Solution

Implement a feature that allows users to edit the metadata of their music files directly within the app, providing options to modify fields like title, artist, album, and genre for better organization and personalization.

### Contribution Guidelines

- [X] I agree to follow the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
This requires a lot of work to done, it is better to let the dedicated apps do this. Closing this as out of scope.
