### ISSUE TITLE
[Bug] Importing playlists does not work

### ISSUE THREAD

**Issue by Wjxfi** [zyrouge/symphony#633]
### Description

Just 0 tracks.

### Steps to Reproduce

https://github.com/OxygenCobalt/Auxio

### Expected Behavior

Amazing import and use.

### Device

Samsung A35

### OS

Android 14

### Version

v2024.11.113

### Contribution Guidelines

- [X] I agree to follow the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
This should hopefully be fixed. Feel free to reopen if it isn't.
