### ISSUE TITLE
[Bug] Incorrect number of tracks while indexing progress.

### ISSUE THREAD

**Issue by Wjxfi** [zyrouge/symphony#634]
### Description

Incorrect number of tracks while indexing progress. Like that: 1,2,3,230,233. after slow update or stop is followed by explosive growth, not displayed before, can not instantly appear 200-300 tracks. this happens in almost every update. Happens after comprehensive update.

### Steps to Reproduce

Update.

### Expected Behavior

true progress without stops and explosive growth.

### OS

Android 14.

### Version

v2024.11.113

### Contribution Guidelines

- [X] I agree to follow the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
This is controlled by how Compose handles updates and how fast the scanner can use multiple threads to index the storage. This more or less does not have a fix.
