### ISSUE TITLE
Embedded or Synchronised Lyrics does not work

### ISSUE THREAD

**Issue by Eliya-Manoj** [zyrouge/symphony#638]
Latest version does not shows any lyrics.

Version 2024.11.113
Android 12

**Comment by zyrouge** [comment]
Could you attach a sample file for which this occurs?

**Comment by Eliya-Manoj** [comment]
All files does not show lyrics. All my music files contain embedded and synchronised lyrics

**Comment by Eliya-Manoj** [comment]
It shows lyrics with other music players and symphony


https://github.com/user-attachments/assets/abbd5413-7b0c-4647-aa67-198603096351

https://github.com/user-attachments/assets/4f4557f0-78c3-4411-b15c-f865acd7c7a9

**Comment by zyrouge** [comment]
Closing this in favor of #646.
