### ISSUE TITLE
[Bug] app regularly loses "favourite" tags

### ISSUE THREAD

**Issue by blind-confused** [zyrouge/symphony#649]
### Description

it seems to forget which songs I added to "favourites", as well as refresh it's whole database whenever the app is restarted. I should also point out that, after the newest update, it failed to recognize any songs at all (had empty library) until I manually opened directories in the settings. I don't know if it's supposed to be like that, just saying in case it isn't.

### Steps to Reproduce

1. Open the app, use it for a bit
2. Close it (by opening the list of open apps and removing it from there, or by just using lots of other apps, so Symphony is forced to close itself)
3. Open the app again
4. See that it says "loading" in the corner, refreshing the song database, and all your favourites are unfavourited

### Expected Behavior

"favourite" tags are not removed

### Additional Context

I'm using the latest version from F-Droid (IzzyOnDroid F-Droid Repo).

### Device

Redmi Note 8

### OS

Android 13, MIUI 14

### Version

2024.11.113

### Contribution Guidelines

- [X] I agree to follow the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
Has already been fixed in latest release. Let me know if it still happens.
