### ISSUE TITLE
[Feature Request] Scroll animation for the song title in bottom bar

### ISSUE THREAD

**Issue by Wjxfi** [zyrouge/symphony#65]
https://user-images.githubusercontent.com/113500363/223866946-614c7cac-c9d9-4c37-ab98-2863fff4cd1a.mp4

![338990.jpg](https://user-images.githubusercontent.com/113500363/223866945-11abb4a7-3f28-44c1-a120-6e7af6276272.jpg)

**Comment by zyrouge** [comment]
:tada: Implemented as of v2023.3.79!
