### ISSUE TITLE
[Bug] It doesn't load my audio files

### ISSUE THREAD

**Issue by AEGhost013** [zyrouge/symphony#654]
### Description

It doesn't show my audio files on Android 13

### Steps to Reproduce

Open app 😅

### Expected Behavior

Añadir permiso para acceder a archivos multimedia en Android 13 

### Screenshots

![Screenshot_20241111-194223](https://github.com/user-attachments/assets/941c1730-2f7a-4884-a5ab-11028a612c58)

### Device

Tecno Spark Go 2024

### OS

Android 13

### Version

2024.11.113

### Contribution Guidelines

- [X] I agree to follow the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
Go to Settings -> Media Folders and import folders there.

**Comment by AEGhost013** [comment]
Thank you
