### ISSUE TITLE
[Feature] Add an equalizer and a tag editor to the app

### ISSUE THREAD

**Issue by AEGhost013** [zyrouge/symphony#658]
### Description

 It's inconvenient to have to exit the app to edit my song tags and to have to use my system's equalizer that doesn't follow the aesthetics of the player.

### Solution

Add a multi-band equalizer (for example 10 bands ) following the aesthetics of the application and a tag editor to edit multiple tags at once

### Contribution Guidelines

- [X] I agree to follow the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
Adding a tag editor requires a lot of effort and it is better off to allow dedicated apps to do that. Changes in equalizer are coming soon. Closing this as out of scope.

**Comment by zyrouge** [comment]
> @zyrouge
> 
> > Changes in equalizer are coming soon. Closing this as out of scope.
> 
> oh bad =C
> 
> can keep a version without equalizer ?

The equalizer can he enabled/disabled.
