### ISSUE TITLE
feature req. Ability to delete a song from the device, as in retro music

### ISSUE THREAD

**Issue by Wjxfi** [zyrouge/symphony#66]
Here
![338994.jpg](https://user-images.githubusercontent.com/113500363/223867507-6e338f60-b327-4afa-a03b-f733eefe9def.jpg)

https://apt.izzysoft.de/fdroid/index/apk/code.name.monkey.retromusic

**Comment by zyrouge** [comment]
Any filesystem related operation will not be added into the app. Closing this as unplanned.
