### ISSUE TITLE
[Bug] Timeline

### ISSUE THREAD

**Issue by Monstanner** [zyrouge/symphony#662]
### Description

The timeline no longer works. Also the display of how long a song goes on and how far advanced the song is. In Benarchitigung, the timeline runs, but when you jump forward in a song, it resets.

### Steps to Reproduce

1. Play a song
2. You can see that the timeline and song duration no longer work

(Tested with `.m4a`- & `.mp3`-Songs)

### Expected Behavior

Die Zeitleiste und Dauer sollte wie in der vorherigen Version funktionieren.

### Device

Nokia X1

### OS

Android 14 Vanilla

### Version

v2024.11.115-nightly+6dcd5c4

### Contribution Guidelines

- [X] I agree to follow the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
Fixed in recent nightly.
