### ISSUE TITLE
[Feature] Unintended behavior: Redundand update checking on repository installs

### ISSUE THREAD

**Issue by sevonj** [zyrouge/symphony#667]
### Description

At initial launch the app asked me about checking for updates. It was a bit confusing as I got it from F-Droid, which should be responsible for that.

I dived into the source code to see what's actually going on here, and it seems to be intended for direct apk downloads only. This is redundant and slightly confusing when installed from an app repository, like play store or f-droid.

### Solution

On builds distributed through app repositories:
- Disable update checking
- Disable relevant UI

### Contribution Guidelines

- [X] I agree to follow the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
Please read about this decision. (https://github.com/zyrouge/symphony/issues/119)

**Comment by sevonj** [comment]
The point of this issue isn't with permissions and trust, but rather on janky user experience. That part can be fixed **without separate builds,** by matching the install source.

**Comment by zyrouge** [comment]
> The point of this issue isn't permissions and trust, but rather janky user experience. That part can be fixed without separate builds, by matching the install source.

How exactly would you find the install source?

**Comment by zyrouge** [comment]
> The function is called ~getInstallerPackageName~ `getInstallSourceInfo`
> 
> I can investigate exact implementation further.

And what if the user wants to be notified if there are any updates?

**Comment by sevonj** [comment]
The user would get notifications or auto-updates from play store or f-droid.

Self-check is on by default, but disabled if the install source is an explicit match to one we know to handle updates.
