### ISSUE TITLE
Folder view

### ISSUE THREAD

**Issue by Giorgio-Germani** [zyrouge/symphony#688]
### Description

I saw there is a button for folder view when you swipe up from the bottom, but this view doesnt seem to do anthing.
Here is what i have: I went to settings and selected my Music folder. In this folder there several other folders that contain Mp3 files. 
What i want: Being able to switch to "folder view" and simply select the folders withing my music folder as if it would be an album. The player should then play all songs within this one specific folder. 

right now neither the button browser, folder, treeview seem to have a function

### Steps to Reproduce

1 swipe up from the bottom of the player
2 select folder
3 see nothing happening

### Expected Behavior

1 swipe up from the bottom of the player
2 select folder
3 see folders to be able to play one

### Device

Redmi Note 10

### OS

Andriod 13

### Version

2024.11.114

### Contribution Guidelines

- [X] I agree to follow the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
Could you be more clear? If you mean "to play a folder", it is already possible.

**Comment by Giorgio-Germani** [comment]
I try to show what i mean in this video: https://youtu.be/MmJIs4JAtfE
i guess a picture is better to explain.

**Comment by MoetheLone** [comment]
I have the same problem. The swipe up menu just isn't functional. It brings you to the first tab in the regular view. 

https://github.com/user-attachments/assets/ceb02621-ac87-48ff-997f-a2bbaf883f6d

I tapped on "playlists" there.

**Comment by zyrouge** [comment]
Oh. That issue has been fixed in nightly and should be pushed in next version.
