### ISSUE TITLE
[Bug] Half of playlists are non-persistent

### ISSUE THREAD

**Issue by Holbormon** [zyrouge/symphony#689]
### Description

I have around 20 playlists, all in .m3u format, consisting of a simple list of relative paths to tracks. They all work in other players, so I know the formatting is correct. However, if I (successfully) import them, despite being all functional, about half of the playlists disappear on app restart. 

It's always the same ones, and after a quick inspection of the files I could not find any common pattern in the faulty playlists. No CLRF/LF differences, no empty last line differences.

### Steps to Reproduce

Import playlists. Close the app. Open the app. Go to the playlist tab. Some playlists are gone.

### Expected Behavior

Playlists stay imported

### Device

Pixel 8

### OS

Android 15

### Version

2024.11.114 but also present on the latest nightlies

### Contribution Guidelines

- [X] I agree to follow the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
Fixed as part of 423715c. Feel free to re-open if it hasn't fixed.
