### ISSUE TITLE
[Bug] Likes don't work

### ISSUE THREAD

**Issue by Wjxfi** [zyrouge/symphony#69]
https://user-images.githubusercontent.com/113500363/223868742-ba4e06e8-7b06-4a5e-b436-7a352d4eb4a2.mp4

**Comment by SunBreaker1** [comment]
I haven't had this issue, try going into your favorites manage playlist inside the options and see if it can be added that way.

**Comment by zyrouge** [comment]
Also, check if you are using the latest version.

**Comment by zyrouge** [comment]
Could you clear all data and check?

**Comment by zyrouge** [comment]
Could you try reinstalling? It seems like it's working.

**Comment by SunBreaker1** [comment]
> Could you try reinstalling? It seems like it's working.
Recently upgraded to S23+ with android 13, One UI 5.1. The issue still persists after a clean re-install

**Comment by SunBreaker1** [comment]
New update seems to have fixed this on my end

**Comment by zyrouge** [comment]
:tada: Fixed as of v2023.5.89.

**Comment by zyrouge** [comment]
> > 🎉 Fixed as of v2023.5.89.
> 
> nothing has changed. For example, for this and many others do not work https://upload.disroot.org/r/h8kZNb2W#m53iwNjWDjmlH5qGgn9tbkglzOJ24OGBT7SLck1VDLI=
> 
> almost everything (or everything) downloaded via [seal](https://www.f-droid.org/packages/com.junkfood.seal/) is not liked
> 
> @zyrouge

Umm, could you elaborate please?
