### ISSUE TITLE
[Bug] Big cover art size can make bitrate deceiving.

### ISSUE THREAD

**Issue by Zany-Jokengineer** [zyrouge/symphony#724]
### Description

It looks like the bitrate is calculated as the total file size in bytes divided by the total track length in seconds.
This causes files with high-quality cover arts to display a higher bit rate than they should.
Here is a result of me using an 11 MB PNG file as cover art:
(The real bit rate is ~120 kbps; the file size without the cover art is ~3.6 MB.)

![image](https://github.com/user-attachments/assets/035aff04-a5d8-4364-9b38-73adca2f527b)

### Steps to Reproduce

Replace the cover art of any song with a substantially big file using any tag editing software. Add the song to a configured folder. Play the song and verify that the displayed bitrate is much higher than real.

### Expected Behavior

The displayed bitrate is the bitrate of the audio itself; size of the metadata should not affect the bitrate.

### OS

Android 14

### Version

2024.12.115

### Contribution Guidelines

- [X] I agree to follow the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment]
This should be fixed by #721.
