### ISSUE TITLE
[Feature Request] Auto translate Song Titles/Artists/Album names

### ISSUE THREAD

**Issue by SunBreaker1** [zyrouge/symphony#75]
Very niche feature, but since a lot of people have songs/artist/albums in different languages, it would be a nice Quality of Life feature if it would be possible to take advantage of Google Translate's API (if available/possible) or use a open source translator from github to translate languages into others, while keeping the system language the same.

**Comment by zyrouge** [comment]
Not sure about this, have to find ways to do this. Also, chances of titles being translated into misleading titles are very high.

**Comment by zyrouge** [comment]
Closing this since it's not plausible.
