### ISSUE TITLE
Crash on Opening (evox Android 13)

### ISSUE THREAD

**Issue by slipsby** [zyrouge/symphony#8]
time: 1669869857014
msg: java.lang.RuntimeException: setDataSource failed: status = 0x80000000
stacktrace: java.lang.RuntimeException: setDataSource failed: status = 0x80000000
	at android.media.MediaMetadataRetriever._setDataSource(Native Method)
	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:310)
	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:334)
	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:383)
	at e4.p$b.a(Unknown Source:466)
	at e4.r.k(Unknown Source:124)
	at u4.a.q(Unknown Source:7)
	at j5.g0.run(Unknown Source:100)
	at p5.a$a.run(Unknown Source:81)
	Suppressed: p3.e: [m1{Cancelling}@67b7500, Dispatchers.Default]

**Comment by slipsby** [comment]
Better crash log format(just incase):https://paste.evolution-x.org/5pcubQ

**Comment by zyrouge** [comment]
Seems like `MediaMetadataRetriever` crashed. This could be a Android 13 issue. I'll get back with fix.

**Comment by senolfndk** [comment]
crashing 😕

**Comment by zyrouge** [comment]
> crashing 😕

I sadly could not hotfix it right now. I don't have an Android 13 device to check whats wrong. So, I'll have to switch to 13 to fix this.

**Comment by zyrouge** [comment]
Implemented a partial fix in v2022.11.39. This is temporary fix since some songs might not some metadata fields like `albumartist`, `genre` and `bitrate`. I'll keep this open until a full fix is implemented.

**Comment by slipsby** [comment]
understood, as of now there is no crashing and music plays fine thank you

**Comment by senolfndk** [comment]
crashes again device samsung android 12

**Comment by zyrouge** [comment]
> crashes again device samsung android 12

Could you send the logs?

**Comment by senolfndk** [comment]
> > tekrar çöküyor cihaz samsung android 12
> 
> Logları gönderir misiniz?
I don't know how to send logs, I'm very new to this

**Comment by zyrouge** [comment]
> > > tekrar çöküyor cihaz samsung android 12
> > 
> > 
> > Logları gönderir misiniz?
> > I don't know how to send logs, I'm very new to this

Could you say when it crashes?

**Comment by senolfndk** [comment]
when opening

**Comment by zyrouge** [comment]
> when opening

Have you tried clearing app cache?

**Comment by senolfndk** [comment]
> > açarken
> 
> Uygulama önbelleğini temizlemeyi denediniz mi?

yes

**Comment by slipsby** [comment]
New crashing issue with logs here: https://paste.evolution-x.org/cPzrLO

**Comment by zyrouge** [comment]
> New crashing issue with logs here: https://paste.evolution-x.org/cPzrLO

When did this occur? Also, it seems like an issue with Android Compose. `LazyColumn` often throws that when it is rapidly updated.

**Comment by zyrouge** [comment]
Transferrred to #10.
