### ISSUE TITLE
Feature req. Sections of playlists and artists, as in retro music

### ISSUE THREAD

**Issue by Wjxfi** [zyrouge/symphony#80]
here
![IMG_20230309_030740.jpg](https://user-images.githubusercontent.com/113500363/223881503-0cb6e4a8-ed1d-4dd1-956d-02d65448abae.jpg)

It's done well there. Take the style from there
https://github.com/RetroMusicPlayer/RetroMusicPlayer

**Comment by zyrouge** [comment]
Current bottom bar uses the Material 3 implementation, this is not going to change unless the library updates the bottom bar. Closing this since it's subjective.
