### ISSUE TITLE
[Feature Request] Better playlist sort

### ISSUE THREAD

**Issue by Offerel** [zyrouge/symphony#81]
Hi there. Found your app via F-droid and would give it a try. I like the way you display albumartist and artist, which is exactly what I need for DK mixes. But I have a problem importing a *.m3u playlist with relative paths. In the playlist, I have 597 DJ mixes and single song's. When I import or open this playlist with other apps like "Vinyl" or "Samsung Music", all songs are imported as they should. The song sorting is fine with this other apps and all songs are included. When I do the same with Symphony, I miss around 200 songs (got different song count on my trys) and sorting of the songs is not as expected. I have to change sorting to "Custom", to get the sorting from the list, except for the missing song's. If I look in the songs tab, all songs are available... but not in the playlist.

**Comment by zyrouge** [comment]
> Hi there. Found your app via F-droid and would give it a try. I like the way you display albumartist and artist, which is exactly what I need for DK mixes. But I have a problem importing a *.m3u playlist with relative paths. In the playlist, I have 597 DJ mixes and single song's. When I import or open this playlist with other apps like "Vinyl" or "Samsung Music", all songs are imported as they should. The song sorting is fine with this other apps and all songs are included. When I do the same with Symphony, I miss around 200 songs (got different song count on my trys) and sorting of the songs is not as expected. I have to change sorting to "Custom", to get the sorting from the list, except for the missing song's. If I look in the songs tab, all songs are available... but not in the playlist.

Changing to "custom" would use the playlist order and it is expected behaviour. Could you possibly upload the M3U file and point some songs that was not imported? This could possibly be a path related issue.

**Comment by Offerel** [comment]
Many thx. Indeed, it seems to be a path issue. For some reason, the path changed slightly during transfer. Maybe a auto organizing issue in Strawberry application. I have manually fixed the paths and the importing was successful for all files. 

I have tried meantime a other app called "Oto Music" this one could import also successful from the broken playlist file. I guess Oto does some searching during import process. Maybe this would be a nice addition for your app to.

Regarding the sorting, can you please try to default sort order to "Custom" in a playlist to keep the sorting order from the playlist? Currently it is always set to "Title" as default.

**Comment by zyrouge** [comment]
> Many thx. Indeed, it seems to be a path issue. For some reason, the path changed slightly during transfer. Maybe a auto organizing issue in Strawberry application. I have manually fixed the paths and the importing was successful for all files.
> 
> I have tried meantime a other app called "Oto Music" this one could import also successful from the broken playlist file. I guess Oto does some searching during import process. Maybe this would be a nice addition for your app to.
> 
> Regarding the sorting, can you please try to default sort order to "Custom" in a playlist to keep the sorting order from the playlist? Currently it is always set to "Title" as default.

I'd just add individual sort selection for playlists.

**Comment by zyrouge** [comment]
:tada: Implemented as of v2023.3.79!

**Comment by ildar** [comment]
still the M3U playlists with relative paths inside are imported empty. Should I open a separate issue for that?
Example of an M3U file (example.m3u)
```
kahvi.org/kahvi303a_john_novak-you_cannot_get_there_from_here.ogg
kahvi.org/kahvi208a_pece-stormy_night.ogg
```

**Comment by zyrouge** [comment]
> still the M3U playlists with relative paths inside are imported empty. Should I open a separate issue for that? Example of an M3U file (example.m3u)
> 
> ```
> kahvi.org/kahvi303a_john_novak-you_cannot_get_there_from_here.ogg
> kahvi.org/kahvi208a_pece-stormy_night.ogg
> ```

Do you have a folder named `kahvi.org` inside the same directory as the M3U file?

**Comment by ildar** [comment]
exactly. That's what the "relative path" means.

**Comment by zyrouge** [comment]
> exactly. That's what the "relative path" means.



> exactly. That's what the "relative path" means.

Could you post the exact M3U file? There is no issues for me.

**Comment by ildar** [comment]
[1.zip](https://github.com/zyrouge/symphony/files/13873406/1.zip)

**Comment by zyrouge** [comment]
> [1.zip](https://github.com/zyrouge/symphony/files/13873406/1.zip)

You can go ahead and open a issue, it would be easier to track.
