### ISSUE TITLE
[Feature Request] Center controls on "Now Playing"

### ISSUE THREAD

**Issue by SunBreaker1** [zyrouge/symphony#82]
I feels just a little off that the play/pause is off to one side and that all the controls aren't centered in the middle of the screen.

Changes:
Play/pause - move to middle/center

Rest of controls - equal spacing around the play/pause with extra spacing around them to spread out the controls on screen 

![Screenshot_20230311-215252_Symphony.jpg](https://user-images.githubusercontent.com/85519676/224513044-3973c03f-bc47-4b11-9dfa-2354b5a8f68f.jpg)

**Comment by sojusnik** [comment]
play/pause button placement was also discussed here: https://github.com/zyrouge/symphony/issues/34

I also think that play/pause in the middle is the most intuitive position, although I understand that this is subjective and @zyrouge wants to leave it on the left

**Comment by zyrouge** [comment]
Implemented as of v2023.4.82.
