### ISSUE TITLE
[Feature Request] Monochrome icon support

### ISSUE THREAD

**Issue by tsiflimagas** [zyrouge/symphony#83]
Hi, I recently found your app and I really like it! The look of it is very pleasing, especially the Material You support, hence my request for monochrome icon support, which will add to the md3 appearance. Thanks!

**Comment by zyrouge** [comment]
:tada: Added as of v2023.5.89.

**Comment by tsiflimagas** [comment]
Thanks for implementing it! It doesn't reflect to the launcher though, reason being, I think, that the monochrome icon should be added to `ic_launcher_round.xml` too.

**Comment by zyrouge** [comment]
Maybe I should have unspecified `roundIcon` in the manifest. Will be patching this soon.

**Comment by zyrouge** [comment]
Should be fixed as of v2023.5.92.
