### ISSUE TITLE
I think you missed ITranslations & EnTranslations, it wont build now

### ISSUE THREAD

**Issue by Icarus-Xu** [zyrouge/symphony#86]

**Comment by zyrouge** [comment]
Did you run `npm run i18n:build`? That should generate the translation files.

**Comment by Icarus-Xu** [comment]
nope, did not notice that, will try tonight

**Comment by zyrouge** [comment]
> nope, did not notice that, will try tonight

Unfortunate enough that was just added. You must have Node.js installed with require packages installed using `npm install`. Then run `npm run i18n:build`.

**Comment by Icarus-Xu** [comment]
confirmed, closing issue
