### ISSUE TITLE
[Bug] Pixelated album art

### ISSUE THREAD

**Issue by Senjosei** [zyrouge/symphony#9]
Album art in notification drawer is pixelated
Android 13
Version 2022.11.39
![Screenshot_20221202-200541_Symphony](https://user-images.githubusercontent.com/17807328/205299637-6fdaa850-35db-4da5-a9f0-89a41e711ae7.png)

**Comment by zyrouge** [comment]
As of v2022.12.41, the original resolution of the cover is used.

**Comment by timothykumm** [comment]
Bug still occurs for me.

It should look like:
![Screenshot_20230227-234508~2](https://user-images.githubusercontent.com/27158937/221715547-9079cc07-4805-42e0-8253-98384846bb55.png)

But it looks like:
![Screenshot_20230227-234540~2](https://user-images.githubusercontent.com/27158937/221715627-5bab1de6-fddb-48b2-950d-658d04ade52f.png)

**Comment by zyrouge** [comment]
Fixed as of v2023.2.71.
