### ISSUE TITLE
[Bug] Random Crash

### ISSUE THREAD

**Issue by timothykumm** [zyrouge/symphony#90]
I was just playing a song, turned off my screen and it crashed. 

![Screenshot_20230317-142906](https://user-images.githubusercontent.com/27158937/225976492-e8483b45-1baa-4805-9e79-faae6a14380a.png)

**Comment by zyrouge** [comment]
Seems like it is caused due to the notification service. Does this always occur?

**Comment by timothykumm** [comment]
> Seems like it is caused due to the notification service. Does this always occur?

No. First time in 3 month of actively using symphony. So pretty rare

**Comment by zyrouge** [comment]
There is no way to prevent foreground errors. It should be bearable since it doesn't occur frequently. Closing this. Let me know this occurs frequently.
