### ISSUE TITLE
[Feature Request] Add ability to swipe right/left on album art in player to prev/next song

### ISSUE THREAD

**Issue by NUCLEARxDYNAMO** [zyrouge/symphony#91]

**Comment by NUCLEARxDYNAMO** [comment]
Add the ability to swipe right or left to skip or play previous song. 

Uploading Screenrecorder-2023-03-18-17-56-25-977.mp4…

**Comment by fillwithjoy1** [comment]
What does the please PR label mean?

**Comment by zyrouge** [comment]
> What does the please PR label mean?

It means somebody should probably contribute and open a pull request for it.

**Comment by zyrouge** [comment]
Closing this in favor of #37.
