### ISSUE TITLE
[Documentation] Document build process

### ISSUE THREAD

**Issue by kraus98772** [zyrouge/symphony#92]
I'm not sure if I just don't understand something or if the file is missing, but i can't find io.github.zyrouge.symphony.services.i18n.translations.ITranslations, which seems to be missing, but is used by the Translator and Symphony class.

**Comment by zyrouge** [comment]
Refer #86. I'll update the wiki with a guide sooner. Until then I'll keep this open.

**Comment by zyrouge** [comment]
Closing this since the wiki has most of the critical documentation. Feel free to re-open this if needed.
