### ISSUE TITLE
[Feature request] Support multiple artists per track

### ISSUE THREAD

**Issue by adaliaramon** [zyrouge/symphony#93]
Coming from the Vinyl music player, what I miss the most is being able to handle multiple artists per track by having them separated by a new line in the artist tag. Would that be possible? In Vinyl, clicking on "See Artist" leads to the first artist in the list. I can't think of any other details that would result from this.

**Comment by zyrouge** [comment]
> Coming from the Vinyl music player, what I miss the most is being able to handle multiple artists per track by having them separated by a new line in the artist tag. Would that be possible? In Vinyl, clicking on "See Artist" leads to the first artist in the list. I can't think of any other details that would result from this.

I'm planning on rewriting the internal categorizer, which will also include this feature. Also, I'm not sure if I can implement new line as a delimiter because MediaStore uses `/` to concatenate artist names. I'll look into possible solutions.

**Comment by chocmake** [comment]
Just thought I'd add that from what I understand Oto Music handles this by being able to set a custom delimiters in the settings (such as `;`, `,`, `/`, `\\`). The latter is the default for the popular Mp3Tag tag editor, which I use.

Symphony looks promising :) Only just discovered it while looking at F-Droid. Have been interested in finding some FOSS app that can handle multi-artist track tags.

**Comment by zyrouge** [comment]
> Just thought I'd add that from what I understand Oto Music handles this by being able to set custom delimiters in the settings (such as `;`, `,`, `/`, `\\`). The latter is the default for the popular Mp3Tag tag editor, which I use.
> 
> Symphony looks promising :) Only just discovered it while looking at F-Droid. Have been interested in finding some FOSS app that can handle multi-artist track tags.

I guess that might be a solution. But, it wouldn't work for artists like "Au/Ra" which is why I did not implement it.

**Comment by chocmake** [comment]
> but, it wouldn't work for artists like "Au/Ra" which is why I did not implement it.

To clarify, from what I've seen in Oto Music those delimiter choices are customizable and can be singular rather than either/or. Ie: one could exclusively use `\\` for the sole delimiter and nothing else, if all other delimiter characters were removed (screenshot showing the setting):

![Oto Music delimiters](https://github.com/zyrouge/symphony/assets/34178938/51eaa819-57a9-4376-aca7-d44467f44281)

The reason Mp3Tag's `\\` default delimiter is useful is it allows correctly parsing separate artists for those like your example (so `Au/Ra` is considered one artist, rather than two), avoiding parsing forwardslashes, commas, semi-colons and spaces. All my collection uses it.

Example of how Mp3Tag and foobar2000 (desktop) handles it, using test artist names that include otherwise 'tricky' characters:

![Mp3Tag delimiters parsing](https://github.com/zyrouge/symphony/assets/34178938/bac500a8-4355-4a21-9972-dc3179df91a6)

For the foobar2000 example I'm using the [Title Formatting Sandbox](https://www.foobar2000.org/components/view/foo_tfsandbox) plugin to demonstrate how each track artist is correctly distinguished thanks to the `\\` delimiter.

**Comment by zyrouge** [comment]
I'll try implementing this as much as possible.

**Comment by RustoMCSpit** [comment]
Vorbis Comments too, different system

**Comment by RustoMCSpit** [comment]
@zyrouge did you also get vorbis comments or just id3?

**Comment by zyrouge** [comment]
> @zyrouge did you also get vorbis comments or just id3? #293

I'm not sure about Vorbis comments since I don't use them. If it was previously working or is supported by MediaStore, the results will be same for Vorbis and ID3.

**Comment by RustoMCSpit** [comment]
> > @zyrouge did you also get vorbis comments or just id3? #293
> 
> I'm not sure about Vorbis comments since I don't use them. If it was previously working or is supported by MediaStore, the results will be same for Vorbis and ID3.

i can pull request a vorbis tagged song if needed

**Comment by zyrouge** [comment]
> > > @zyrouge did you also get vorbis comments or just id3? #293
> > 
> > 
> > I'm not sure about Vorbis comments since I don't use them. If it was previously working or is supported by MediaStore, the results will be same for Vorbis and ID3.
> 
> i can pull request a vorbis tagged song if needed

Unfortunately this patch doesn't affect Vorbis comments since Android does not parse multi-valued tags. No good alternative libraries are also available to make this possible. You could go ahead and create an issue for possible future implementation.

**Comment by RustoMCSpit** [comment]
> > > > @zyrouge did you also get vorbis comments or just id3? #293
> > > 
> > > 
> > > I'm not sure about Vorbis comments since I don't use them. If it was previously working or is supported by MediaStore, the results will be same for Vorbis and ID3.
> > 
> > 
> > i can pull request a vorbis tagged song if needed
> 
> Unfortunately this patch doesn't affect Vorbis comments since Android does not parse multi-valued tags. No good alternative libraries are also available to make this possible. ~You could go ahead and create an issue for possible future implementation.~ Nevermind, issue already exists.

Auxio already does this? Maybe check their implementation

**Comment by zyrouge** [comment]
> > No good alternative libraries are also available to make this possible.
> 
> Auxio already does this? Maybe check their implementation https://github.com/OxygenCobalt/Auxio/issues?q=is%3Aissue+vorbis+is%3Aclosed

Seems like it uses Media3 and it has it's own implementation of `MediaMetadata`. Might try to use Media3's extractor alone without migrating to Exoplayer. I'll look into possible implementations.

**Comment by RustoMCSpit** [comment]
> > > No good alternative libraries are also available to make this possible.
> > 
> > 
> > Auxio already does this? Maybe check their implementation https://github.com/OxygenCobalt/Auxio/issues?q=is%3Aissue+vorbis+is%3Aclosed
> 
> Seems like it uses Media3 and it has it's own implementation of `MediaMetadata`. Might try to use Media3's extractor alone without migrating to Exoplayer. I'll look into possible implementations.

whats wrong with exoplayer / if you want you can ask oxygencobalt how they did it

**Comment by zyrouge** [comment]
> > > > No good alternative libraries are also available to make this possible.
> > > 
> > > 
> > > Auxio already does this? Maybe check their implementation https://github.com/OxygenCobalt/Auxio/issues?q=is%3Aissue+vorbis+is%3Aclosed
> > 
> > 
> > Seems like it uses Media3 and it has it's own implementation of `MediaMetadata`. Might try to use Media3's extractor alone without migrating to Exoplayer. I'll look into possible implementations.
> 
> whats wrong with exoplayer / if you want you can ask oxygencobalt how they did it

Nothing's wrong with Exoplayer. Migrating to it needs significant effort and possibly huge internal changes.
