### ISSUE TITLE
[Feature Request] Smoother Scroll Animations

### ISSUE THREAD

**Issue by SunBreaker1** [zyrouge/symphony#94]
While not necessarily a feature, I have noticed the with longer list of albums, short swipes while scrolling look a bit jerky.

It's a bit off putting especially on modern high refresh screens, where the whole point of high refresh is smoothness.

To be fair, I'm not discounting the possibility that this I caused by the variable refresh rate of modern phones combined with human eyesight

**Comment by zyrouge** [comment]
The currently implementation is the best implementation in Compose. I do agree that it is not smooth as Recycle View. This is something that is currently in my hand. I'll just leave this open until no further optimization can be done.

**Comment by zyrouge** [comment]
I don't think any more optimization can be done after this. Performance are currently bound to Compose and no further things can be done from my side. Closing this.
