### ISSUE TITLE
[Feature Request] I want more than 5 home tabs

### ISSUE THREAD

**Issue by Wjxfi** [zyrouge/symphony#99]
![b7dbe71c-3ec5-4d5f-afb6-a74cbd0c52e6.jpg](https://user-images.githubusercontent.com/113500363/228353481-a9eedf32-ffce-4aec-97ea-d9b4f0081a94.jpg)

**Comment by zyrouge** [comment]
Compose Bottom Bar doesn't allow that. Also, it breaks the Material Design guidelines. Maybe an alternative approach might help with this.

**Comment by zyrouge** [comment]
You can swipe up/tap on active icon to view all options. Closing this as an alternative solution has been implemented.
